### ISSUE TITLE
core : crash server

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#100]
theramore:
http://www.wowhead.com/zone=15/dustwallow-marsh
action
http://fr.wowhead.com/npc=4952/mannequin-dentrainement-de-theramore
debug screen shot
https://dl.dropboxusercontent.com/u/82706346/crash/Image1.jpg
debug vs2015
https://dl.dropboxusercontent.com/u/82706346/crash/CallStack1.dgml
the source 
https://dl.dropboxusercontent.com/u/82706346/crash/ark.434.rar

**Comment by gpn39f** [comment]
it's a Training dummy.. 
dummy is not using coreScript and not smartScript 
and fighting with no Crash. used human Paladin lvl 60, no bot..

**Comment by firelook** [comment]
the person thought it was that who make the crash, but anyway do you have any information to correct the origin of the crash ?

**Comment by graham79** [comment]
something odd in the dummys creature_template, has minlevel =20, maxlevel=60 which is wrong according to https://cata-twinhead.twinstar.cz/?npc=4952  same as wowhead.
update creature_template set minlevel=1,maxlevel=1 where entry=4952;

**Comment by gpn39f** [comment]
values from @graham79 imported.. 
is Crash gone??

**Comment by firelook** [comment]
I close it, no maange to reproduce it so ...
