### ISSUE TITLE
table : censor_bad_words

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#102]
I do not know if it is a real issue but this table should be in the main database of autorisation (or worst characters database) 
I  think this table should be independant, and also can be maintained outside wow specific environnement

**Comment by gpn39f** [comment]
the data are not character depended.. so the place on world table are ok..
the data itself are loaded on server-load.. maybe a admin-command to reload table are welcome..
the content in database can easely be edited from php.. 
mostly Forum Software have possibility for Import own php scripts for those behavior..

**Comment by firelook** [comment]
my problem is the database is maintained by you. So if I erase my database and remplace by yours I lose my table ;)
this table is outside the logic of maintenance for wow regarding my point of view

**Comment by gpn39f** [comment]
this is correct..
but this is for some other tables true to..
all world.custum**\* tables..
the creature_template_outfits..
mostly locale are not filled completely.. and only german are maintained..
no other one are push new locale to the database..
no other one are push missing BroadcastTextIDs 

so you have to store several own tables, that hold you personal Server data, and Import them after using snapshoot..

and to outsource the world-list to a extern text-file, then you have people, that not know how to create a Textfile in utf8.. 

with using of forum and php it is easy to let user edit database wordtable. 
using a stored Textfile on youre hdd  is not as simple.
and you have more security problem's using text files, insted using mysql.. 

you see.. there are many things to know before changing..

**Comment by firelook** [comment]
yes I have no problems to do an insert ;) , thius is waht I do to insert french data
It was just to open the discussion !

**Comment by graham79** [comment]
We have enough REAL issues without people opening NON-issues.

**Comment by firelook** [comment]
oh ! what a beautiful comment ;) take a breath, it is just a game ;)
