### ISSUE TITLE
Sister Almyra <Priest Trainer> npc 44468

### ISSUE THREAD

**Issue by gpn39f** [Arkania/ArkCORE-NG#105]
npc 
http://www.wowhead.com/npc=44468/sister-almyra
found in gilneas City, greymane court

on some YouTube Videos you can see that she are healing periodic friends around..
someone know the spell she use ???

https://www.youtube.com/watch?v=YSHJmAOYNxc
it's the short Moment before Player enter the horse..

**Comment by graham79** [comment]
This is not a sniff. but renew=139 is priest spell and ticks at +31 for 15 secs.
all the other HoT spells i found give to much per tick. I see in video that player is healed +21 per tick but if the video was made on blizz it may be blizz nerf renew spell in later patch ?

https://cata-twinhead.twinstar.cz/?spell=139

**Comment by gpn39f** [comment]
imported.. thanks..
