### ISSUE TITLE
Worgen second quest

### ISSUE THREAD

**Issue by graham79** [Arkania/ArkCORE-NG#106]
Player cannot hand in https://cata-twinhead.twinstar.cz/?quest=14091
player is in wrong phase or map and cannot see quest ender. The first Prince Liam Greymane is still visible and player is in phase 1 map 654 zone 4755 area 4756 ?? Am I missing DB data?

**Comment by gpn39f** [comment]
after uploading gilneas startarea level 1-5, there is uploaded new snapshot to, 
please update youre database.. incl changed zip folder 02/2016!!!

**Comment by graham79** [comment]
Ok, updated and now first quest hub works fine. after getting sent to the military quarter and picking up the class quest from Gwen Armstead "The wind knows your name" druid quest. get to the quest hub in military quarter and player still in phase 2, quest hub npc's are in phase 8. is this mistake or do I need to add data too the phase_area table?

**Comment by gpn39f** [comment]
all 4 phase tables are now necassary..
phase_area, phase_definition, spell_area, spell_phase
i have expanded the phaseMgr with the new world swap datas, so now we can script new areas like gilneas.. 
maybe the way trinity uses phases is more the way bliz**\* does phases.. 
but trinity has not completely finished this work. last 2 Years.. so maybe the way is a dead end??
i have not reworked or testet smartscript related commands. 
i have not reworked or testet conditions related commands. 
if someone are using this and see failure, please open issues with good description and all used code parts.
