### ISSUE TITLE
db : spell

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#107]
I have this strange error
Player::addSpell: Non-existed in SpellStore spell #75461 request.
any ideas ?

**Comment by firelook** [comment]
a delete, quite easy ;)

**Comment by gpn39f** [comment]
None of the other databases are using spell named flame shock.. 
and this spell id are not used in dbc.. so it's not avaible and no typo or copy/past failure..
best alternative is: deleting :-)
