### ISSUE TITLE
characters db fix

### ISSUE THREAD

**Issue by warlokowla** [Arkania/ArkCORE-NG#108]
/*
SQLyog Ultimate v11.11 (64 bit)
MySQL - 5.7.11-log : Database - characters

---

*/

/*!40101 SET NAMES utf8 */;

/_!40101 SET SQL_MODE=''_/;

/_!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/_!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 _/;
/_!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' _/;
/_!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 _/;
CREATE DATABASE /_!32312 IF NOT EXISTS_/`characters` /_!40100 DEFAULT CHARACTER SET utf8 */;

USE `characters`;

/*Table structure for table `character_npcbot` */

DROP TABLE IF EXISTS `character_npcbot`;

CREATE TABLE `character_npcbot` (
  `owner` int(10) DEFAULT NULL,
  `entry` int(10) DEFAULT NULL,
  `race` int(3) DEFAULT NULL,
  `class` int(3) DEFAULT NULL,
  `istank` int(3) DEFAULT NULL,
  `equipMhEx` int(10) DEFAULT NULL,
  `equipOhEx` int(10) DEFAULT NULL,
  `equipRhEx` int(10) DEFAULT NULL,
  `equipHead` int(10) DEFAULT NULL,
  `equipShoulders` int(10) DEFAULT NULL,
  `equipChest` int(10) DEFAULT NULL,
  `equipWaist` int(10) DEFAULT NULL,
  `equipLegs` int(10) DEFAULT NULL,
  `equipFeet` int(10) DEFAULT NULL,
  `equipWrist` int(10) DEFAULT NULL,
  `equipHands` int(10) DEFAULT NULL,
  `equipBack` int(10) DEFAULT NULL,
  `equipBody` int(10) DEFAULT NULL,
  `equipFinger1` int(10) DEFAULT NULL,
  `equipFinger2` int(10) DEFAULT NULL,
  `equipTrinket1` int(10) DEFAULT NULL,
  `equipTrinket2` int(10) DEFAULT NULL,
  `equipNeck` int(10) DEFAULT NULL,
  `active` int(3) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `character_npcbot` */

/_!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/_!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS _/;
/_!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS _/;
/_!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

other sql not work :v

**Comment by gpn39f** [comment]
why shold we delete the Primary key???
the key over ownerGuid and creatureEntry is needed for prevent double entrys..
better is: you tell: what do you have for a problem   ??
