### ISSUE TITLE
Linux Compile Error 

### ISSUE THREAD

**Issue by Jiinx** [Arkania/ArkCORE-NG#11]
/home/jiinx/repo/arkcore/src/server/scripts/Kalimdor/zone_echo_isles.cpp: In member function ‘void npc_wildmane_cat::npc_wildmane_catAI::DoWork()’:
/home/jiinx/repo/arkcore/src/server/scripts/Kalimdor/zone_echo_isles.cpp:238:67: error: taking address of temporary [-fpermissive]
/home/jiinx/repo/arkcore/src/server/scripts/Kalimdor/zone_echo_isles.cpp:238:119: error: taking address of temporary [-fpermissive]
/home/jiinx/repo/arkcore/src/server/scripts/Kalimdor/zone_echo_isles.cpp:243:73: error: taking address of temporary [-fpermissive]
make[2]: **\* [src/server/scripts/CMakeFiles/scripts.dir/Kalimdor/zone_echo_isles.cpp.o] Error 1
make[1]: **\* [src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
make: **\* [all] Error 2

using the -fpermissive flag works to resolve.. but really shouldn't have to

**Comment by gpn39f** [comment]
I'm not a Linux user, so I can't answer this. 
there are several forums talking about this error, but none has a solution I can user here on the server..
all you find is to use the  -fpermissive flag on user site
it's really welcome if somewhere can help us..

**Comment by Jiinx** [comment]
where to post solutions?

**Comment by gpn39f** [comment]
fixed..
