### ISSUE TITLE
Quest - The Wolf and The Kodo

### ISSUE THREAD

**Issue by Wexez** [Arkania/ArkCORE-NG#110]
Quest - The Wolf and The Kodo lacks scripting. It seems to not be scripted at all (not smart scripts, nor c++) / waypoints missing, and the story missing as well.
Quest - http://cata.openwow.com/quest=25205

Check it here - https://www.youtube.com/watch?v=cQMTdejp_bM

**Comment by gpn39f** [comment]
roger/@graham79 is working on this quest.

**Comment by Wexez** [comment]
@gpn39f Sounds good :)

**Comment by graham79** [comment]
I was, I got diverted into fixing other stuff, I still have some part work done. Just need a c++ script for the kodo at the end, then it will be complete. :+1:

**Comment by graham79** [comment]
@gpn39f 
This is what I have gathered so far.

[the wolfs tail.txt](https://github.com/Arkania/ArkCORE-NG/files/190930/the.wolfs.tail.txt)
