### ISSUE TITLE
[BUG] Quest: Gasping for Breath

### ISSUE THREAD

**Issue by cooler-SAI** [Arkania/ArkCORE-NG#111]
I know that Gilneas in Progress, anyway I wanna report
Gossip doesn't work, Quest Gasping for Breath bugged

http://www.wowhead.com/quest=14395/gasping-for-breath

**Comment by gpn39f** [comment]
i'm ready with zone 2..
i'm now working on last commited issues..
then i will start with Zone 3.. and first quest is yours :-)

**Comment by cooler-SAI** [comment]
awesome job! I really respect you! I will continue bug reports about other Quests from other zones

**Comment by gpn39f** [comment]
it's welcome :-)
