### ISSUE TITLE
[BUG] Report Pack

### ISSUE THREAD

**Issue by cooler-SAI** [Arkania/ArkCORE-NG#112]
1) http://www.wowhead.com/npc=48619/therisa-sallow
 Can't teach player

2) Quest Ever So Lonely doesn't work
http://www.wowhead.com/quest=24974/ever-so-lonely

3) http://www.wowhead.com/npc=10666/gordo
Can't repair and trade

**Comment by graham79** [comment]
http://www.wowhead.com/npc=10666/gordo
Gossip values missing, 
update gossip_menu_option  set option_id=3,npc_option_npcflag=128 where menu_id=11159;

**Comment by graham79** [comment]
http://www.wowhead.com/npc=48619/therisa-sallow
her creature_template is missing trainer value in trainer_type.
Update creature_template set trainer_type=2 where entry =48619;

**Comment by gpn39f** [comment]
therisa-sallow is a proferssion Trainer for all professions..
using gossip 12180 is a good Idee..

**Comment by cooler-SAI** [comment]
```sql
-- Ever So Lonely (Fixed Part 1)
UPDATE `quest_template` SET `RequiredNpcOrGo2`=0, `RequiredNpcOrGoCount2`=0 WHERE  `Id`=24974;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=1543;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=1544;

DELETE FROM `smart_scripts` WHERE  `entryorguid`=1543;
DELETE FROM `smart_scripts` WHERE  `entryorguid`=1544;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(1543, 0, 0, 0, 8, 0, 100, 0, 73108, 0, 0, 0, 33, 38923, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'On Spellhit - Give credit'),
(1543, 0, 1, 0, 8, 0, 100, 0, 73108, 0, 0, 0, 2, 35, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'On Spellhit - Change factin'),
(1543, 0, 2, 0, 8, 0, 100, 0, 73108, 0, 0, 0, 41, 2000, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'On Spellhit - Despawn after 2 sec'),
(1544, 0, 0, 0, 8, 0, 100, 0, 73108, 0, 0, 0, 33, 38923, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'On gossip select - Give credit'),
(1544, 0, 1, 0, 8, 0, 100, 0, 73108, 0, 0, 0, 2, 35, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'On Spellhit - Change factin'),
(1544, 0, 2, 0, 8, 0, 100, 0, 73108, 0, 0, 0, 41, 2000, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'On Spellhit - Despawn after 2 sec');
```

**Comment by gpn39f** [comment]
to spawn the new murloc it is the spell 73109/73433
what i'm missing is the spell that give visual rope between murloc and player

**Comment by graham79** [comment]
cast the spell the spell thats in the item template.  item=52059, spell=73108 creates the aura of rope between player and target. 73108 casts spell=94266 aura spell.
look at 73108 in Spellwork and you will see below the interrupt flags "Ex Caster Aura Spell (94266) Vile fin Guardian Aura.

**Comment by gpn39f** [comment]
using spell 73108 give me allways a : "you can't do that" back..
and the  grey DOT in spell_icon is never green..

**Comment by gpn39f** [comment]
using sniffer.. the client is not sending a packet for our click on spell_icon..
the Client is prevent for using the item??
i think: maybe the values of the item in db are wrong???

**Comment by graham79** [comment]
have you checked for incorrect values in "Conditions" ? casting the spell on any creature with the gm command, .cast 73108 always gives aura. It says in the quest log that health of murloc must be reduced before item will cast spell, also. although that doesn't stop you when using gm command .cast.

also, i looked at the aura spell 94266 and in spellworks i see "Allowed Areas:" 85 - Tirisfal Glades (Map 0).

**Comment by gpn39f** [comment]
i'm on map 0, Zone 85 area 169
the spell "cant be done" as GM to..
the conditions have no entries for 73108, 52079, 1543, 1544

and please, do not forget:
there are no packet send from Client to Server, so it's not the Server that deny use of spell..
and it's not the Server that send the "cant be done"

**Comment by graham79** [comment]
hmmm, it works with my client? maybe you have 73108 disabled in disables in your db? other then that I have no clue why the spell casts for me and not you?

**Comment by graham79** [comment]
I havent tried it on a murloc, the first mob I tested it on was a ghoul near the bridge on the way to brill perhaps a setting in the murlocs template?

**Comment by graham79** [comment]
![wowscrnshot_032516_124657](https://cloud.githubusercontent.com/assets/2817044/14044504/6fcd28dc-f289-11e5-9236-b90c95f3a2b2.jpg)
![wowscrnshot_032516_124751](https://cloud.githubusercontent.com/assets/2817044/14044508/78efa174-f289-11e5-9c7d-b55f96f5e571.jpg)
![wowscrnshot_032516_124839](https://cloud.githubusercontent.com/assets/2817044/14044509/7c90b58e-f289-11e5-9722-d4d03b5fa914.jpg)

**Comment by gpn39f** [comment]
ok.. deleted my old char.. created new.. added quest.. 
ok.. now spell is castable and is done the rope..
i will script the rest :-)

**Comment by graham79** [comment]
great, probably need to add a conditions entry so players can't do what I did in the screen captures. :)

**Comment by gpn39f** [comment]
it's not so easy..
1.) as far you have aura 94266, the spell is inactive..
(this was my Problem in the morning.. if Aura is present, the spell can't be castet..)
2.) if you cast spell 73108, the rope is shown a short secound.. and disappear.. on movement the rope disapears before shown..

i have scripted the quest really near blizz.. but the missing of the rope, bothers me...
maybe someone else can make it better..
