### ISSUE TITLE
[NPC] Rampaging Worgen

### ISSUE THREAD

**Issue by Dokman** [Arkania/ArkCORE-NG#118]
It doesn't have any kind of aggro and it need's too when you are close to his he has to attack you...

http://www.wowhead.com/npc=34884/rampaging-worgen

**Comment by gpn39f** [comment]
wow has data not for 434.. look here
https://wow.freakz.ro/npc_finder.php?npc=34884
you see the state for npc is yellow.. so he is not hate you, but you can attack him..

**Comment by Dokman** [comment]
in Net servers attack you if you are in his range of aggro i have tested the worgen zone and done a worgen at level 20
@gpn39f  How i can sniff it?
i will give you the sniffs i can do it another time

**Comment by gpn39f** [comment]
this is one thing blizz*\* is doing every versions step..
many older areas becomes lower level, damage and more, so newbees can level faster..
so you can't compare a server realm with 434 content with current 6.xx
try to Play vanilla on a server with Client Version 1.12.. there you will use 2-3 weeks to level up to 20.. 
on current 6.xx you are on level 20 after 5-8 hour..

look at forum from trinity.. there you can download a sniffer and a packetparser for current 6.xx

**Comment by Dokman** [comment]
that's true hahahaha

**Comment by Dokman** [comment]
ok if it's neutral it will be nuetral i think hahaha

So one question when you will finnish the worgen zone? hahaha if i can help i will do it.. but in class now we are doing Functions... a few days ago finnished arrays so my level for programming is not good at all...

**Comment by graham79** [comment]
can we close this issue now?
