### ISSUE TITLE
[Loc6] A.K.A Spanish... bad ported

### ISSUE THREAD

**Issue by Dokman** [Arkania/ArkCORE-NG#119]
spanish is bad ported, it need utf8 and is all fucked...
A lot of words need accent mark, but is all fucked...

**Comment by gpn39f** [comment]
yes.. i have seen this for german to..
at home i have a simple SQL patch to change the wrong char's to utf8..
but this is not for public use..

now i will check: what is happen..

**Comment by gpn39f** [comment]
ok.. i found my mistake..

1.) on working, i use navicat.. this is a easy to use gui..
navicat is used to export the database for snapshoot to.

2.) on some really big SQL base files, navicat is using many hours for import those sql file. therefor i use mysql.exe from the mySQL lib folder to import them.

3.) and here is the problem. Navicat is not include the string SET NAMES "UTF8"; to exported file.
but mysql need it, to make a correct utf8 import of globalisation chars.. 
so our snapshoot database file need added the flag: SET NAMES "UTF8";

in future i will take notice for this behavior..
i'm uploading now the new snapshoot for you

**Comment by Dokman** [comment]
thank you hahahah

**Comment by Dokman** [comment]
@gpn39f  any news about the new snapshot? hahaha
