### ISSUE TITLE
[Quest] Quest Id 62 doesnt give the credit

### ISSUE THREAD

**Issue by SunnyTheCool** [Arkania/ArkCORE-NG#12]
So if you're enter the mine it wont give you the credit you need to complete the quest.

http://www.wowhead.com/quest=62/the-fargodeep-mine

**Comment by SunnyTheCool** [comment]
Maybe this will help https://github.com/TrinityCore/TrinityCore/issues/12172

**Comment by gpn39f** [comment]
you can go from 2 side in the mine.. there is a way between them.. 10 % from left side are the position you must reach.. ca. X:-9843 Y:130  Z:5
