### ISSUE TITLE
[Quest] The Warchief Cometh

### ISSUE THREAD

**Issue by cooler-SAI** [Arkania/ArkCORE-NG#120]
The Warchief Cometh doesn't work
http://www.wowhead.com/quest=26965/the-warchief-cometh

**Comment by gpn39f** [comment]
is on work.. summon warchief and talking is ready..
what i'm now searching, is all about the agathe spell 83173..
she cast the initiate spell, but 
1.) the lightning is missing.. (what spell/aura is it???)
2.) no human receive the spell-cast.. (one thing i found, the spell use 0 meter range, is fixed..)
3.) no human receive spell 83150, 83163-83168 for Change to forsaken
4.) and at last trigger: no human receive spell 83149

note:
ok.. Setting range and filter for human, now the lightning is present.., but human are not "hover".. on sniff i see a move opcode.. so i use a move with pos.z++ on apply Aura..

**Comment by graham79** [comment]
http://www.wowhead.com/spell=83993/raise-forsaken
I found this spell worked fine on any dead alliance human and had the sparkly lightning effect.
in the video the spell is being cast by several invis bunnys, hence the mass lightning effect :)
