### ISSUE TITLE
error compile linux

### ISSUE THREAD

**Issue by warlokowla** [Arkania/ArkCORE-NG#121]
cmake ../ -DPREFIX=/home/`echo $USER`/server -DTOOLS=1
CMake Error at CMakeLists.txt:18 (cmake_policy):
  Policy "CMP0043" is not known to this version of CMake.

-- Detected 64-bit platform
-- UNIX: Using jemalloc
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- GCC: Enabled c++11 support
-- GCC: Enabled C99 support
-- GCC: SFMT enabled, SSE2 flags forced
-- Found ACE library: /usr/local/lib/libACE.so
-- Found ACE headers: /usr/local/include
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient_r.so
-- Found MySQL headers: /usr/include/mysql
-- Found Readline library: /usr/lib/x86_64-linux-gnu/libreadline.so
-- Include dir is: /usr/include
-- Found git binary : /usr/bin/git
- ArkCore revision       : 42d97eab9510 2016-03-30 16:00:07 +0200 (master branch)
- ArkCore buildtype      : Release
- Install core to        : /home/root/server
- Install libraries to   : /home/root/server/lib
- Install configs to     : /home/root/server/etc
- Build world/auth       : Yes (default)
- Build with scripts     : Yes (default)
  -- Found Readline library: /usr/lib/x86_64-linux-gnu/libreadline.so
- Build map/vmap tools   : Yes
- Build core w/PCH       : Yes (default)
- Build scripts w/PCH    : Yes (default)
- Show compile-warnings  : No  (default)
- Use coreside debug     : No  (default)
- Use GIT revision hash  : Yes
  -- SCRIPT PREPARATIONS
  -> Prepared: Spells
  -> Prepared: Commands
  -> Prepared: Examples
  -> Prepared: Custom
  -> Prepared: World
  -> Prepared: Outdoor PVP Zones
  -> Prepared: Eastern Kingdoms
  -> Prepared: Kalimdor
  -> Prepared: Outland
  -> Prepared: Northrend
  -> Prepared: The Maelstrom
  -> Prepared: Events
  -> Prepared: Pet
  -- SCRIPT PREPARATION COMPLETE
  -- Configuring incomplete, errors occurred!
  See also "/home/ArkCORE-NG/build/CMakeFiles/CMakeOutput.log".
  See also "/home/ArkCORE-NG/build/CMakeFiles/CMakeError.log".

ubuntu 14.04

**Comment by gpn39f** [comment]
the change you make, is in conflict with windows visual studio 2013 update 4.. and vs 2015 with cmake 3.4.0 
you are using old ubuntu / cmake..pls. upgrade youre gc++ and cmake and all tools depends..
and check again..

**Comment by warlokowla** [comment]
I've updated everything but the problem is, I have been solved by changing the version of cmake in cmakelist.txt

**Comment by warlokowla** [comment]
this is other error, fater starting to compile

new problem

/home/ArkCORE/src/server/scripts/Spells/spell_mage.cpp: In member function ‘void spell_mage_ring_of_frost_freeze
::spell_mage_ring_of_frost_freeze_SpellScript::FilterTargets(std::list&)’:
/home/ArkCORE/src/server/scripts/Spells/spell_mage.cpp:1319:52: error: no matching function for call to ‘std::li
st::erase(std::_List_const_iterator::_Self)’
targets.erase(itr--);
^
/home/ArkCORE/src/server/scripts/Spells/spell_mage.cpp:1319:52: note: candidates are:
In file included from /usr/include/c++/4.8/list:64:0,
from /home/ArkCORE/src/server/shared/Common.h:76,
from /home/ArkCORE/src/server/game/Scripting/ScriptMgr.h:23,
from PrecompiledHeaders/ScriptPCH.h:8:
/usr/include/c++/4.8/bits/list.tcc:108:5: note: std::list<_Tp, _Alloc>::iterator std::list<_Tp, _Alloc>::erase(s
td::list<_Tp, _Alloc>::iterator) [with _Tp = WorldObject; _Alloc = std::allocator<WorldObject>; std::list<_Tp,
_Alloc>::iterator = std::_List_iterator]
list<_Tp, _Alloc>::
^
/usr/include/c++/4.8/bits/list.tcc:108:5: note: no known conversion for argument 1 from ‘std::_List_const_iter
ator::_Self {aka std::_List_const_iterator}’ to ‘std::list::iterator {
aka std::_List_iterator}’
In file included from /usr/include/c++/4.8/list:63:0,
from /home/ArkCORE/src/server/shared/Common.h:76,
from /home/ArkCORE/src/server/game/Scripting/ScriptMgr.h:23,
from PrecompiledHeaders/ScriptPCH.h:8:
/usr/include/c++/4.8/bits/stl_list.h:1193:7: note: std::list<_Tp, _Alloc>::iterator std::list<_Tp, _Alloc>::erase(std::list<_Tp, _Alloc>::iterator, std::list<_Tp, _Alloc>::iterator) [with _Tp = WorldObject; _Alloc = std::allocator<WorldObject>; std::list<_Tp, _Alloc>::iterator = std::_List_iterator]
erase(iterator __first, iterator __last)
^
/usr/include/c++/4.8/bits/stl_list.h:1193:7: note: candidate expects 2 arguments, 1 provided
[ 32%] Building CXX object src/server/game/CMakeFiles/game.dir/Chat/Chat.cpp.o
make[2]: **\* [src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_mage.cpp.o] Error 1
make[1]: **\* [src/server/scripts/CMakeFiles/scripts.dir/all] Error 2

**Comment by gpn39f** [comment]
last 2 years some Linux Distributors has a changed syntax of Gnu c++.. 
unusual use of some commands are denyed from this c++
i have changed to spell to a allowed form.. (i hope)
please test it..
