### ISSUE TITLE
[Quest] Save Krennan Aranas - Spell Not working

### ISSUE THREAD

**Issue by Dokman** [Arkania/ArkCORE-NG#124]
http://www.wowhead.com/quest=14293/save-krennan-aranas

**Comment by cooler-SAI** [comment]
Disagree! walk under this man and then press button, all works good, I tested

**Comment by Dokman** [comment]
@cooler-SAI i was testing it with a warlock and get this bug... when i click him it doesn't do anything

**Comment by gpn39f** [comment]
you should not click *_HIM *_

you should move horse so you stay with horse **under**him  and click the spell Icon..

**Comment by Dokman** [comment]
but it will be the same no? hahahaha the horse is automatic but... when i click Krennan is bugged hahaha

**Comment by cooler-SAI** [comment]
@Dokman the horse doesn't automatic when you UNDER him, press spell on panel
