### ISSUE TITLE
db & core : Darkmoon Faire Made Easy

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#125]
http://www.wowhead.com/guide=1461/darkmoon-faire-made-easy

the portal doesn't appears : checked with Just outside Thunder Bluff in Mulgore
and activated with the event to check it

P.S.
also unfortunately a lot of quest at the faire doesn't work
(it is less important than the portal)

**Comment by gpn39f** [comment]
i see we have more problems here.. 
there are 3 old darkmoon game_events, from client before 4.3, with position short outside a town
and we have the new darkmoon Island.. from patch 4.3 up

**Comment by firelook** [comment]
ok good news if you have an idea of the solution

**Comment by firelook** [comment]
P.S.
As soon as you give your go, I will do also the quest around the portal to give you the ones who doesn't work

**Comment by firelook** [comment]
I have done event start 4 and 5 to begin testing/debugging but I do not see it => I am doing the right way to help you ?

**Comment by gpn39f** [comment]
the darkmoon Event is only present first week in month, starting on first sunday in month..
so you have to edit table game_event, eventEntry 75,  column: length and insert here 43200 = 1 month length..(60 Minute \* 24 Hour \* 31 days)
the eventEntry 3,4,5 are old values that could be deleted (later)
new Darkmoon Faire has eventEntry 75, only this Event is active in future..
then the Event is present 1 month in length..

**Comment by firelook** [comment]
ok I will use the 75 event (I will start manually)

**Comment by gpn39f** [comment]
i'm filling the Island with missing npc and gameobjects.
if there are more failure, we have to open new issue.. ;-)
