### ISSUE TITLE
db quest problem

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#129]
http://fr.wowhead.com/quest=14098/levacuation-de-la-place-des-marchands
this quest doesn't work and make the server crashing

> `D:\users_sys\games\wow\mangos\git\arkania_ng_434\src\server\game\Spells\Spell.cp
> p:1456 in Spell::SelectImplicitTargetObjectTargets ASSERTION FAILED:
>   (m_targets.GetObjectTarget() || m_targets.GetItemTarget()) && "Spell::SelectIm
> plicitTargetObjectTargets - no explicit object or item target available!"
> Spell::SelectImplicitTargetObjectTargets() d:\users_sys\games\wow\mangos\git\ark
> ania_ng_434\src\server\game\spells\spell.cpp: 1456 + 0x1f
> Spell::SelectEffectImplicitTargets() d:\users_sys\games\wow\mangos\git\arkania_n
> g_434\src\server\game\spells\spell.cpp: 927 + 0x0
> Spell::SelectSpellTargets() d:\users_sys\games\wow\mangos\git\arkania_ng_434\src
> \server\game\spells\spell.cpp: 770 + 0x0
> Spell::cast() d:\users_sys\games\wow\mangos\git\arkania_ng_434\src\server\game\s
> pells\spell.cpp: 3177 + 0x0
> Spell::prepare() d:\users_sys\games\wow\mangos\git\arkania_ng_434\src\server\gam
> e\spells\spell.cpp: 3025 + 0x0
> Unit::CastSpell() d:\users_sys\games\wow\mangos\git\arkania_ng_434\src\server\ga
> me\entities\unit\unit.cpp: 923 + 0x0
> Unit::CastSpell() d:\users_sys\games\wow\mangos\git\arkania_ng_434\src\server\ga
> me\entities\unit\unit.cpp: 951 + 0x36
> Spell::EffectTriggerSpell_160() d:\users_sys\games\wow\mangos\git\arkania_ng_434
> \src\server\game\spells\spelleffects.cpp: 7601 + 0x28
> Spell::HandleEffects() d:\users_sys\games\wow\mangos\git\arkania_ng_434\src\serv
> er\game\spells\spell.cpp: 4747 + 0x0
> Spell::_handle_immediate_phase() d:\users_sys\games\wow\mangos\git\arkania_ng_43
> 4\src\server\game\spells\spell.cpp: 3416 + 0x0
> Spell::handle_immediate() d:\users_sys\games\wow\mangos\git\arkania_ng_434\src\s
> erver\game\spells\spell.cpp: 3312 + 0x0
> Spell::cast() d:\users_sys\games\wow\mangos\git\arkania_ng_434\src\server\game\s
> pells\spell.cpp: 3256 + 0x0
> Spell::prepare() d:\users_sys\games\wow\mangos\git\arkania_ng_434\src\server\gam
> e\spells\spell.cpp: 3025 + 0x0
> Unit::CastSpell() d:\users_sys\games\wow\mangos\git\arkania_ng_434\src\server\ga
> me\entities\unit\unit.cpp: 923 + 0x0
> Unit::CastSpell() d:\users_sys\games\wow\mangos\git\arkania_ng_434\src\server\ga
> me\entities\unit\unit.cpp: 951 + 0x36
> GameObject::CastSpell() d:\users_sys\games\wow\mangos\git\arkania_ng_434\src\ser
> ver\game\entities\gameobject\gameobject.cpp: 1773 + 0x32
> GameObject::Use() d:\users_sys\games\wow\mangos\git\arkania_ng_434\src\server\ga
> me\entities\gameobject\gameobject.cpp: 1737 + 0x10
> WorldSession::HandleGameObjectUseOpcode() d:\users_sys\games\wow\mangos\git\arka
> nia_ng_434\src\server\game\handlers\spellhandler.cpp: 307 + 0x0
> WorldSession::Update() d:\users_sys\games\wow\mangos\git\arkania_ng_434\src\serv
> er\game\server\worldsession.cpp: 357 + 0x0
> World::UpdateSessions() d:\users_sys\games\wow\mangos\git\arkania_ng_434\src\ser
> ver\game\world\world.cpp: 2717 + 0x10
> World::Update() d:\users_sys\games\wow\mangos\git\arkania_ng_434\src\server\game
> \world\world.cpp: 2077 + 0x0
> WorldRunnable::run() d:\users_sys\games\wow\mangos\git\arkania_ng_434\src\server
> \worldserver\worldthread\worldrunnable.cpp: 62 + 0x0
> ACE_Based::Thread::ThreadTask() d:\users_sys\games\wow\mangos\git\arkania_ng_434
> \src\server\shared\threading\threading.cpp: 190 + 0x0
> ACE_OS_Thread_Adapter::invoke() d:\users_sys\games\wow\mangos\git\arkania_ng_434
> \dep\acelite\ace\os_thread_adapter.cpp: 103 + 0x5
> crt_at_quick_exit()+0x7d [0x6be1d]
> BaseThreadInitThunk()+0x1a [0x1842]
> RtlUserThreadStart()+0x21 [0x14f45]
> `

**Comment by Dokman** [comment]
http://www.wowhead.com/quest=14098/evacuate-the-merchant-square

**Comment by gpn39f** [comment]
last upload has wrong title.. is fix for this issue,  #129

**Comment by firelook** [comment]
so I close it.
