### ISSUE TITLE
Deadmines - Defias Gunpowder Missing.

### ISSUE THREAD

**Issue by Dopescope** [Arkania/ArkCORE-NG#13]
inside the instance Deadmines the Defias Gunpowder (http://www.wowhead.com/item=5397/defias-gunpowder) is missing for both my characters.
25/07/2015.

**Comment by gpn39f** [comment]
all the instance is alpha. 
there are to many mops spawned, all phases are broken..
I need a sniffing file from this area/instace.. pls, if someone can help us here..
I will try to start with youtube..

**Comment by gpn39f** [comment]
the Gunpowder  is not used anymore to open door. the new script open the door correct with cannon..
