### ISSUE TITLE
db quest: evacuation

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#134]
http://www.wowhead.com/quest=14397/evacuation

you can not give it back to the npc, you have no npc
you have to do 
.npc add 36452

**Comment by Dokman** [comment]
@firelook you are french i am spansih, so PNJ or "Personaje no jugador" or "Personage Non Jouer" is the same as Non Player Character or NPC
it's only a hint for a good english hahaha i don't want to hurt your feels ok?
if we use a understandable english we can work better together

**Comment by firelook** [comment]
oups you are right !!!! no offense ;)

**Comment by firelook** [comment]
ok
