### ISSUE TITLE
 [Into the Maw!] Quest

### ISSUE THREAD

**Issue by Dopescope** [Arkania/ArkCORE-NG#14]
http://www.wowhead.com/quest=25617/into-the-maw

possible to grab this quest twice.

**Comment by gpn39f** [comment]
fixed 10% = removed the questtaker as queststarter. 
this quest sequence is buggy at all.. both ghost( for ally/horde) should be spawned by items, 
the items
http://www.wowhead.com/item=52853/totem-of-goldrinn
http://www.wowhead.com/item=52854/totem-of-logosh
should be provided by quest
https://cata-twinhead.twinstar.cz/?quest=25353  and 25355

there are 4 quest into the maw..
https://cata-twinhead.twinstar.cz/?quest=25618
you should only take one..

**Comment by gpn39f** [comment]
with upload now the quest serie Horde/Alliance is fixed..
several autocompleted quest are now working.
items and gameobject working..
loot working..
issue #14 fixed.. pls check.. and close this issue if solved..
