### ISSUE TITLE
db : intriguing-specimens

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#149]
http://www.wowhead.com/quest=29574/intriguing-specimens

has been killed and can not be given back

**Comment by graham79** [comment]
you need to loot the items from the 2 boss's to complete this quest. 
http://www.wowhead.com/item=72127/tavaroks-heart
http://www.wowhead.com/item=72126/pandemonius-essence
@gpn39f  the loot for the quest items is missing from creature_loot_template.

**Comment by PiskelDEV** [comment]
``` sql
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Chance`, `QuestRequired`, `Comment`) VALUES
(18343, 72127, 17.92, 1, 'Tavarok\'s Heart'),
(18343, 72126, 17.61, 1, 'Pandemonius\' Essence');
```

**Comment by gpn39f** [comment]
fixed with issue 148 and 149
