### ISSUE TITLE
Instances crashing almost every time

### ISSUE THREAD

**Issue by ghost** [Arkania/ArkCORE-NG#15]
If this is my problem and not a generalized error please forgive me for being such a dumbass
![captura de pantalla 2015-07-25 a las 4 20 51](https://cloud.githubusercontent.com/assets/6758615/8889190/3e725cae-32d0-11e5-8da3-609252251b03.png)
Just using master branch "as it is". I'm playing and testing with other 10 people and by the time we tried to enter instances it just blowed up.
This error never happened to me with the game master's (level 3) account...

If you need more details i could test nearly anything

Thanks and nice work, i expect to collaborate in anything I can since I would love to use ArkCORE-NG as the base to my project. In the next few days I'll introduce myself in the forum.

Everything was going sooo well xD... BTW i tried to look at the map.cpp (the line described in the console) but i just... can't do it since I'm learning very very slowly... And starting to smash my head with the keyboard just ain't fix anything.

**Comment by ghost** [comment]
In a preview version (I tested 30/06) this does not happen :D

**Comment by gpn39f** [comment]
pls tell me: what instance you enter

the error say me: player is stored intern and could not enter the instance twice.. so why or when are the player leaving the instance.. brunching or AFK or death???
in what time interval are the player trying to enter the "old" instance..

**Comment by ghost** [comment]
Instances 229 that must be Blackrock caverns and 632 throne of the tides, as you can see in the picture. But i don't think that the bug is in any specific dungeon (Intuition)

What you are saying is irrelevant for when I'm getting the error. Both are new players and new instance saves. And the crash occurs entering the instance, not leaving it xDD

I hope that helps

**Comment by gpn39f** [comment]
mmhh.. I was use 2 unused human chars.. using gm account to level them to 90.. reach with this 3 chars the blackrock caverns. enter with 3 chars the cavern.. the core created 3 instance, one for each of us.. gm stay on his instance, player chars exits.. their build a group with 2 chars.. enter the instance.. now the 2 chars in group are in same instance.. no crash at all..
maybe...?????
a chrash has destroyed stored information on db??? table instance on character db show you the id of instance (on youre crash id2 and id5) and the map229 and 632.. at end of the line is the data area.. first make a backup of the db(of corse!!), then clear first the data and test it, then the row and test it..

**Comment by ghost** [comment]
maybe...?????
a chrash has destroyed stored information on db??? table instance on character db show you the id of instance (on youre crash id2 and id5) and the map229 and 632.. at end of the line is the data area.. first make a backup of the db(of corse!!), then clear first the data and test it, then the row and test it..

**Comment by ghost** [comment]
I'm researching right now about this

**Comment by ghost** [comment]
The bug still exists in previus versions with the same chars database
Sorry for putting an issue in here and made you test it :S

**Comment by ghost** [comment]
What you meant is that I should truncate those tables?
Seriously making work a characters database from TC2 in 2009 with 1500 players in ArkCORE had been a fucking odyssey. I thought that it was completely fixed...
If you helped me i can complete a good tutorial and post it in arkania :D
I'm going to try it out.

**Comment by gpn39f** [comment]
its first time I see this error so I can only guess
if the instance has wrong data inside, maybe a short help is to reset the instance

**Comment by ghost** [comment]
GPN39f i already have tried (yesterday with the ArkCORE's last commit) to truncate every info about the instances in my database but that didn't solved the issue.

I cleaned this tables: 
account_instance_times
character_instance
instance
instance_reset

I just went to TC's wiki and looked for the tables that could have relation to this

But now in a second look I'm seeing this tables (just the name) that could have relations to this
item_instance (977 rows in here)
item_refund_instance

I think this issue occurs because of the massive update to trinitycore 4.3.4, then to arkcore4 and then to arkcoreNG... But the core is sensitive to this and if something were really wrong i couldn't even start the core, finally i think that is well made...
Additionaly, some columns that should be NOT NULL, aren't. But I don't think that this have something to do

**Comment by ghost** [comment]
This happens every time two players or more enter a instance
And also happened ten minutes ago when I entered with some friends in a wotlk instance. When the server got up and i tried to enter the same instance, individually, but being in the same group, it crashed with the same error again

**Comment by gpn39f** [comment]
there are some console commands..
if I read it correct:

.instance listbinds    ( list all active maps)
.instance unbinds 229  ( delete  one map from store )
.instance unbinds all  ( removel all stored instance data )

**Comment by ghost** [comment]
Hey i didn't forgot about this.
It seems that reloading the instances is a MUST for updating from the past like that. 
The emu creates new time resets for instances when you place it in another located zone (from france to americas for example)

Anyway, I'm done with this. I'll just start over again and post what i did in arkania forums... so if anyone who finds it usefull can use it. Thanks a lot

**Comment by ghost** [comment]
Instances keep crashing with a new characters and auth dbs...

**Comment by gpn39f** [comment]
pls. read this tutorial..
http://community.trinitycore.org/topic/37-the-trinitycore-issuetracker-and-you/#comment-56305
to see what is wrong, we need a correct crash report. 
but I'm using windows. I can't use Linux or mac reports..
then I can see deeper in the error

**Comment by ghost** [comment]
Fixed in last commit!
