### ISSUE TITLE
Created new branch legacy434. This works with TrinityCoreLegacy. Added prepatch and LordPsyanBots (playerbots, randombots, New NPCBots)

### ISSUE THREAD

**Issue by sd3494702** [Arkania/ArkCORE-NG#155]
https://bitbucket.org/lordpsyan/lordpsyan-patches/src/c7860f9924063f4ff22e881530b4e7330dccb0a8?at=legacy434

**Comment by firelook** [comment]
sorry but I am lost , what is the purpose of this issue please ?

**Comment by gpn39f** [comment]
this is done on the github entry of LordPsyan. 
but nothing more is happens there..
we using a variant of this NpcBot.. maybe therefor we are linked there..
i think we can close this on our issue db
