### ISSUE TITLE
Greymane Manor Gate

### ISSUE THREAD

**Issue by graham79** [Arkania/ArkCORE-NG#158]
On entering the driveway, the gate closes after you enter, after getting the quest to take the coach to the crash site you cannot access the coach as it stands outside the gate and the gate has no gearwheel to interact with. So character is stuck in Greymane Manor grounds.
Gate Guid:166771

**Comment by gpn39f** [comment]
you are on phase 8192 if you go from duskhaven up to manor.. in this phase the door is open..
on the kings teleskop you receive quest from king: exodus.. on quest accept you come to phase 16384 and you stand near the car.. the door is now closed..
you enter the car.. and now its started the waypoints. on first waypoint it's open the door..
maybe this is too late.. the door is on the way, to open its first mm, if i cross the door
i can set the event open door to waypoint 0, as start moment
and i close the door one movepoint later.. 
its more pretty..:-)

**Comment by graham79** [comment]
you missed my point, after doing the telescope quest and taking the follow up you go down the ramp to get aboard the coach, but this is not possible because the coach is spawned outside the gates. and your inside the closed gates :)

**Comment by gpn39f** [comment]
is there a second door?? a second ramp??.. i will look..

**Comment by graham79** [comment]
No second way down to the gate as far as i know. I'll post a picture if you like. The coach and horses are spawned just out of reach when the gate is closed :)
