### ISSUE TITLE
Quests problem

### ISSUE THREAD

**Issue by graham79** [Arkania/ArkCORE-NG#159]
Problems
1: he offers a quest to talk to himself, is allready offered by another npc.
quest id: 14336. Kill or be Killed.
2: The 2 quests he offers are linked by an ExclusiveGroup ID...If you accept one you cannot take the other, even if you complete the first one. As far as I know your supposed to be able to get and complete both quests.
quest A: http://www.wowhead.com/quest=14347/hold-the-line
quest B: http://www.wowhead.com/quest=14348/you-cant-take-em-alone
quest starter  http://www.wowhead.com/npc=36140/prince-liam-greymane

**Comment by gpn39f** [comment]
1.) two  questgiver.. removed wrong npc
2.) questline not correct..

`
Series 1
1. Hold the Line            14347
2. Holding Steady           14366
3. The Allens' Storm Cellar 14367

requires 14336
Series 2
1. You Cant Take 'Em Alone  14348
2. Holding Steady           14366
3. The Allens' Storm Cellar 14367

so we have two questline, 
you cant take only one of the quests 14347 or 14348

14336X
14347A or 14348C
14366D
14367E

entry = questA      PrevQuestId = X        NextQuestId = questD    ExclusiveGroup = questA    NextQuestInChain = questD  
entry = questC      PrevQuestId = X        NextQuestId = questD    ExclusiveGroup = questA    NextQuestInChain = questD
entry = questD      PrevQuestId = 0        NextQuestId = 0         ExclusiveGroup = 0         NextQuestInChain = questE
entry = questE      PrevQuestId = questD   NextQuestId = 0         ExclusiveGroup = 0         NextQuestInChain = 0

`
formula taken from https://trinitycore.atlassian.net/wiki/display/tc/quest_template
