### ISSUE TITLE
Error Compile linux

### ISSUE THREAD

**Issue by warlokowla** [Arkania/ArkCORE-NG#16]
root@instance-1:~/home/ArkCORE-NG/build# make
[  2%] Built target jemalloc
[  6%] Built target g3dlib
[  6%] Built target Detour
[  7%] Built target Recast
## [  7%] Built target gsoap

```
Could not find a proper repository signature (hash) - you may need to pull tags with git fetch -t
Continuing anyway - note that the versionstring will be set to "unknown 1970-01-01 00:00:00 (Archived)"
```

[  7%] Built target revision.h
[  7%] Built target sharedPCH.cpp_dephelp
[  7%] Built target generate_sharedPCH.cpp
[ 11%] Built target shared
[ 11%] Built target gamePCH.cpp_dephelp
[ 11%] Built target generate_gamePCH.cpp
[ 30%] Built target game
[ 30%] Built target collisionPCH.cpp_dephelp
[ 31%] Built target generate_collisionPCH.cpp
[ 32%] Built target collision
[ 32%] Built target authPCH.cpp_dephelp
[ 32%] Built target generate_authPCH.cpp
Linking CXX executable authserver
/usr/bin/ld: ../shared/libshared.a(Threading.cpp.o): undefined reference to symbol 'pthread_kill@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: **\* [src/server/authserver/authserver] Error 1
make[1]: **\* [src/server/authserver/CMakeFiles/authserver.dir/all] Error 2
make: **\* [all] Error 2

Ubuntu 14.04 LTS

**Comment by gpn39f** [comment]
Google give me a link:
http://stackoverflow.com/questions/8198056/having-a-libpthread-so-linking-trouble-on-ubuntu
and here same error trinity 2013!!!
https://github.com/TrinityCore/TrinityCore/issues/9740

**Comment by warlokowla** [comment]
It is a syntax error

**Comment by gpn39f** [comment]
pls close issue if solved.. (and pls. report what you have done wrong)

**Comment by warlokowla** [comment]
stay tuned to the solution.

**Comment by Jiinx** [comment]
The core does not support (currently) > cmake 2.8.9. Ubuntu 14.04 comes with cmake 2.8.12.2 and is not able to be downgraded. 

This is a know issue and has more to do with the ./cmake than the actual core.

**Comment by gpn39f** [comment]
I'm using windows and cmake 3.2.0 RC1 without errors..

**Comment by Jiinx** [comment]
cmake for windows and linux are different (unfortunately).  I use cmake 3.2.3 on windows and 2.8.9 on linux
