### ISSUE TITLE
Script: zone_gilneas_city3 Can't compile

### ISSUE THREAD

**Issue by blakeymort** [Arkania/ArkCORE-NG#164]
Cant compile scripts
![image](https://cloud.githubusercontent.com/assets/20445370/16928826/5abb287e-4cfa-11e6-921b-3f1313df0a4c.png)

**Comment by gpn39f** [comment]
it seem's that vs2013 has a old syntax..
i will install vs2013 tomorrow and see how we can solve this..

**Comment by Dev-zeros** [comment]
just gives the same error on linux (gcc (Debian 4.7.2-5 ) 4.7.2 and cmake version 2.8.9
