### ISSUE TITLE
Make error under debian, GNU/Linux. zone_gilneas_city3.cpp

### ISSUE THREAD

**Issue by ghost** [Arkania/ArkCORE-NG#166]
[ 58%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/EasternKingdoms/TheStockade/instance_the_stockade.cpp.o
[ 58%] [ 59%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/EasternKingdoms/Gilneas/zone_gilneas_city1.cpp.o
Building CXX object src/server/scripts/CMakeFiles/scripts.dir/EasternKingdoms/Gilneas/zone_gilneas2.cpp.o
[ 59%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/EasternKingdoms/Gilneas/zone_gilneas_city3.cpp.o
/home/arkcore/ArkCORE-NG/src/server/scripts/EasternKingdoms/Gilneas/zone_gilneas_city3.cpp: In member function ‘virtual void npc_sister_almyra_38466::npc_sister_almyra_38466AI::UpdateAI(uint32)’:myra_38466AI::UpdateAI(uint32)’:
/home/arkcore/ArkCORE-NG/src/server/scripts/EasternKingdoms/Gilneas/zone_gilneas_city3.cpp:1311:61: error: taking address of temporary [-fpermissive]
       if (GetWavePosition().GetExactDist2d(&me->GetPosition()) > 3.0f)
                                                             ^
/home/arkcore/ArkCORE-NG/src/server/scripts/EasternKingdoms/Gilneas/zone_gilneas_city3.cpp: In member function ‘virtual void npc_prince_liam_greymane_38218::npc_prince_liam_greymane_38218AI::UpdateAI(uint32)’:
/home/arkcore/ArkCORE-NG/src/server/scripts/EasternKingdoms/Gilneas/zone_gilneas_city3.cpp:1981:61: error: taking address of temporary [-fpermissive]
       if (GetWavePosition().GetExactDist2d(&me->GetPosition()) > 3.0f)
                                                             ^
/home/arkcore/ArkCORE-NG/src/server/scripts/EasternKingdoms/Gilneas/zone_gilneas_city3.cpp: In member function ‘virtual void npc_myriam_spellwaker_38465::npc_myriam_spellwaker_38465AI::UpdateAI(uint32)’:
/home/arkcore/ArkCORE-NG/src/server/scripts/EasternKingdoms/Gilneas/zone_gilneas_city3.cpp:2386:61: error: taking address of temporary [-fpermissive]
       if (GetWavePosition().GetExactDist2d(&me->GetPosition()) > 3.0f)
                                                             ^
/home/arkcore/ArkCORE-NG/src/server/scripts/EasternKingdoms/Gilneas/zone_gilneas_city3.cpp: In member function ‘virtual void npc_lorna_crowley_38426::npc_lorna_crowley_38426AI::UpdateAI(uint32)’:
/home/arkcore/ArkCORE-NG/src/server/scripts/EasternKingdoms/Gilneas/zone_gilneas_city3.cpp:2760:61: error: taking address of temporary [-fpermissive]
       if (GetWavePosition().GetExactDist2d(&me->GetPosition()) > 3.0f)
                                                             ^
/home/arkcore/ArkCORE-NG/src/server/scripts/EasternKingdoms/Gilneas/zone_gilneas_city3.cpp: In member function ‘virtual void npc_lord_darius_crowley_38415::npc_lord_darius_crowley_38415AI::UpdateAI(uint32)’:
/home/arkcore/ArkCORE-NG/src/server/scripts/EasternKingdoms/Gilneas/zone_gilneas_city3.cpp:3202:61: error: taking address of temporary [-fpermissive]
       if (GetWavePosition().GetExactDist2d(&me->GetPosition()) > 3.0f)
                                                             ^
/home/arkcore/ArkCORE-NG/src/server/scripts/EasternKingdoms/Gilneas/zone_gilneas_city3.cpp: In member function ‘virtual void npc_king_genn_greymane_38470::npc_king_genn_greymane_38470AI::UpdateAI(uint32)’:
/home/arkcore/ArkCORE-NG/src/server/scripts/EasternKingdoms/Gilneas/zone_gilneas_city3.cpp:3525:61: error: taking address of temporary [-fpermissive]
       if (GetWavePosition().GetExactDist2d(&me->GetPosition()) > 3.0f)
                                                             ^
[ 59%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/EasternKingdoms/Gilneas/zone_duskhaven.cpp.o
[ 59%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/EasternKingdoms/ThroneOfTheTides/boss_lady_nazjar.cpp.o
[ 59%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/EasternKingdoms/ThroneOfTheTides/boss_commander_ulthok.cpp.o
[ 59%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/EasternKingdoms/ThroneOfTheTides/boss_mindebender_ghursha.cpp.o
[ 59%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/EasternKingdoms/ThroneOfTheTides/boss_ozumat.cpp.o
[ 59%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/EasternKingdoms/ThroneOfTheTides/instance_throne_of_the_tides.cpp.o
[ 59%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/EasternKingdoms/ThroneOfTheTides/throne_of_the_tides.cpp.o
src/server/scripts/CMakeFiles/scripts.dir/build.make:7138: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/EasternKingdoms/Gilneas/zone_gilneas_city3.cpp.o' failed
make[2]: **\* [src/server/scripts/CMakeFiles/scripts.dir/EasternKingdoms/Gilneas/zone_gilneas_city3.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
CMakeFiles/Makefile2:1046: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/all' failed
make[1]: **\* [src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by blakeymort** [comment]
get pull, problem fixed

**Comment by gpn39f** [comment]
again this compiler flag: -fpermissive
grmpf..
ok.. is changed.. i hope all is fine now..

**Comment by ghost** [comment]
It's fixed now
