### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Pigpriest** [Arkania/ArkCORE-NG#171]
Hallo, ich habe heute die Core endeckt und wollte sie testen.
beim Compilen kam folgende Fehlermeldung. 
Ich arbeite auf einem Root mit Debian 8.
Ich hoffe du kannst mir helfen.
Danke

[ 28%] [ 28%] [ 28%] Building CXX object src/server/game/CMakeFiles/game.dir/Events/GameEventMgr.cpp.o
Building CXX object src/server/game/CMakeFiles/game.dir/Entities/AreaTrigger/AreaTrigger.cpp.o
Building CXX object src/server/game/CMakeFiles/game.dir/Entities/Corpse/Corpse.cpp.o
/root/ArkCORE-NG/src/server/game/Entities/Corpse/Corpse.cpp:29:18: fatal error: util.h: Datei oder Verzeichnis nicht gefunden
 #include "util.h"
                  ^
compilation terminated.
src/server/game/CMakeFiles/game.dir/build.make:2285: recipe for target 'src/server/game/CMakeFiles/game.dir/Entities/Corpse/Corpse.cpp.o' failed
make[2]: **\* [src/server/game/CMakeFiles/game.dir/Entities/Corpse/Corpse.cpp.o] Error 1
make[2]: **\* Warte auf noch nicht beendete Prozesse...
[ 28%] [ 28%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Kalimdor/zone_tanaris.cpp.o
Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_server.cpp.o
CMakeFiles/Makefile2:675: recipe for target 'src/server/game/CMakeFiles/game.dir/all' failed
make[1]: **\* [src/server/game/CMakeFiles/game.dir/all] Error 2
make[1]: **\* Warte auf noch nicht beendete Prozesse...
/root/ArkCORE-NG/src/server/scripts/Kalimdor/zone_tanaris.cpp: In member function ‘void npc_beam_target_bunny_46661::npc_beam_target_bunny_46661AI::DespawnCaravan()’:
/root/ArkCORE-NG/src/server/scripts/Kalimdor/zone_tanaris.cpp:952:83: warning: iteration 5u invokes undefined behavior [-Waggressive-loop-optimizations]
                 if (Creature\* npc = sObjectAccessor->GetCreature(_me, sandPugmy[i]))
                                                                                   ^
/root/ArkCORE-NG/src/server/scripts/Kalimdor/zone_tanaris.cpp:951:13: note: containing loop
             for (uint32 i = 0; i < 6; i++)
             ^
/root/ArkCORE-NG/src/server/scripts/Kalimdor/zone_tanaris.cpp: In member function ‘virtual void npc_beam_target_bunny_46661::npc_beam_target_bunny_46661AI::Reset()’:
/root/ArkCORE-NG/src/server/scripts/Kalimdor/zone_tanaris.cpp:697:33: warning: iteration 5u invokes undefined behavior [-Waggressive-loop-optimizations]
                 sandPugmy[i] = 0;
                                 ^
/root/ArkCORE-NG/src/server/scripts/Kalimdor/zone_tanaris.cpp:696:13: note: containing loop
             for (uint32 i = 0; i < 6; i++)
             ^
Linking CXX static library libscripts.a
[ 83%] Built target scripts
Makefile:117: recipe for target 'all' failed
make: *_\* [all] Error 2

**Comment by gpn39f** [comment]
ok fehler gefunden und geupdatet.. 
#include "util.h" richtig ist #include "Util.h"

**Comment by Pigpriest** [comment]
Danke für den schnellen Fix. Hat Top geklappt.
