### ISSUE TITLE
Server Start

### ISSUE THREAD

**Issue by Pigpriest** [Arkania/ArkCORE-NG#172]
Ich nochmal ;)

Ich kann den Authserver ohne Probleme starten
Wenn ich den Worldserver starte kommt immer das selbe.

World initialized in 0 minutes 14 seconds
ArkCORE>ArkCORE>Failed to open acceptor, check if the port is free
Failed to start network
ArkCORE4-NG rev. 1970-01-01 00:00:00 +0000 (unknown) (Unix, Release) (worldserver-daemon) ready...

Der Port ist auf jedenfall frei.
Ich habe einen 335 Trinityserver der startet ohne Probleme über die standard Port Einstellungen.
Den Root habe ich neu gestartet das wirklich alles aus ist und dann den Cata Server ganz allein gestartet und es kommt die selbe Meldung.
Habe den RealmServerPort = 3724 in der Auth config, den WorldServerPort = 8085 in der World config und sogar die Realm ID gewechselt. 
Und natürlich die Realmlist immer dementsrechend angepasst.
Ich weiß echt nicht mehr weiter. 
Hab den 335 Server und 548 Server gleichzeitig laufen gehabt, ok 548 fliegt wieder ;) zu viele Bugs.

Hoffe du kannst mir helfen.

Gruß Paladinhunter

**Comment by gpn39f** [comment]
also die fehlermeldung gehört zum welt-server
normaler port 8085, steht zum einen in world.conf (mit bind addr 0.0.0.0)
aber auch in der tabelle auth.realmlist.. hier sind aber manchmal komische sachen je nach OS..
die externe ip ist der hostername von dyndns oder ähnlich
die interne ip ist 127.0.0.1 oder z.b 192.168.1.1
möglich das linux hier auch localhost annimmt..

das der kanal nicht geöffnet werden kann, bedeutet entweder port 8085 wird von einem anderen programm belegt, oder die gewählte ip ist nicht gültig.. also hier einfach alle 3 möglichkeiten ausprobieren.

**Comment by Pigpriest** [comment]
Ok danke hat geklappt.
Der wollte die BindIP nicht mit meiner IP Adresse. da muss die 0.0.0.0 in der world datenbank stehen.
nun klappt es.
Was ich bis jetzt gesehen habe hast du top arbeit gemacht.

**Comment by gpn39f** [comment]
vielen dank..
du bist doch auch schon einige jahre dabei.. vielleicht kannst du mir helfen..
das vehicle system ist bei uns irgendwie fehlerhaft.
ich schaff es nicht in kezan bei dem auto Hot Rod.. neben dem player auch die 3 helfer einzuladen.
vielleicht hast du eine idee..

und dann: wenn das auto gespawn ist, kann ich die ESC taste nicht mehr drücken.. dann stürzt der Client ab.. ( ich erinnere mit im rotkamm gebirge, wenn das paket Carmoflage geladen wurde, gab es bei der esc taste auch einen crash vom client..)
