### ISSUE TITLE
authserver running error

### ISSUE THREAD

**Issue by hero2880** [Arkania/ArkCORE-NG#182]
TrinityCore rev. 32b780bffd31+ 2016-09-23 01:41:44 +0200 (4.3.4 branch) (Win64, Release, Static) (authserver)
<Ctrl-C> to stop.

Using configuration file E:/434-ArkCORE/core/authserver.conf.
Using SSL version: OpenSSL 1.0.2d 9 Jul 2015 (library: OpenSSL 1.0.2d 9 Jul 2015)
Using Boost version: 1.60.0
Automatic database updates are disabled for all databases!
Opening DatabasePool 'auth'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 5.6.27
MySQL server ver: 5.5.5-10.0.16-MariaDB 
Connected to MySQL database at 127.0.0.1
MySQL client library: 5.6.27
MySQL server ver: 5.5.5-10.0.16-MariaDB 
Connected to MySQL database at 127.0.0.1
DatabasePool 'auth' opened successfully. 2 total connections running.
In mysql_stmt_prepare() id: 11, sql: "SELECT a.id, a.username, a.locked, a.lock_country, a.last_ip, a.failed_logins, ab.unbandate > UNIX_TIMESTAMP() OR ab.unbandate = ab.bandate, ab.unbandate = ab.bandate, aa.gmlevel, a.token_key, a.sha_pass_hash, a.v, a.s, a.battlenet_account FROM account a LEFT JOIN account_access aa ON a.id = aa.id LEFT JOIN account_banned ab ON ab.id = a.id AND ab.active = 1 WHERE a.username = ?"
Unknown column 'a.battlenet_account' in 'field list'
In mysql_stmt_prepare() id: 17, sql: "SELECT a.id, a.sessionkey, a.last_ip, a.locked, a.lock_country, a.expansion, a.mutetime, a.locale, a.recruiter, a.os, a.id, aa.gmLevel, bab.unbandate > UNIX_TIMESTAMP() OR bab.unbandate = bab.bandate, ab.unbandate > UNIX_TIMESTAMP() OR ab.unbandate = ab.bandate, r.id FROM account a LEFT JOIN account r ON a.id = r.recruiter LEFT JOIN battlenet_accounts ba ON a.battlenet_account = ba.id LEFT JOIN account_access aa ON a.id = aa.id AND aa.RealmID IN (-1, ?) LEFT JOIN battlenet_account_bans bab ON ba.id = bab.id LEFT JOIN account_banned ab ON a.id = ab.id AND ab.active = 1 WHERE a.username = ? ORDER BY aa.RealmID DESC LIMIT 1"
Table 'auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 45, sql: "UPDATE account SET last_attempt_ip = ? WHERE username = ?"
Unknown column 'last_attempt_ip' in 'field list'
In mysql_stmt_prepare() id: 72, sql: "INSERT INTO logs_ip_actions (account_id,character_guid,type,ip,systemnote,unixtime,time) VALUES (?, ?, ?, (SELECT last_ip FROM account WHERE id = ?), ?, unix_timestamp(NOW()), NOW())"
Table 'auth.logs_ip_actions' doesn't exist
In mysql_stmt_prepare() id: 73, sql: "INSERT INTO logs_ip_actions (account_id,character_guid,type,ip,systemnote,unixtime,time) VALUES (?, ?, ?, (SELECT last_attempt_ip FROM account WHERE id = ?), ?, unix_timestamp(NOW()), NOW())"
Table 'auth.logs_ip_actions' doesn't exist
In mysql_stmt_prepare() id: 74, sql: "INSERT INTO logs_ip_actions (account_id,character_guid,type,ip,systemnote,unixtime,time) VALUES (?, ?, ?, ?, ?, unix_timestamp(NOW()), NOW())"
Table 'auth.logs_ip_actions' doesn't exist
In mysql_stmt_prepare() id: 75, sql: "INSERT INTO logs_ip_actions (account_id,character_guid,type,ip,systemnote,unixtime,time) VALUES ((SELECT id FROM account WHERE username = ?), 0, 1, ?, ?, unix_timestamp(NOW()), NOW())"
Table 'auth.logs_ip_actions' doesn't exist
In mysql_stmt_prepare() id: 80, sql: "INSERT INTO account_muted VALUES (?, UNIX_TIMESTAMP(), ?, ?, ?)"
Table 'auth.account_muted' doesn't exist
In mysql_stmt_prepare() id: 82, sql: "DELETE FROM account_muted WHERE guid = ?"
Table 'auth.account_muted' doesn't exist
In mysql_stmt_prepare() id: 83, sql: "SELECT ba.id, UPPER(ba.email), ba.locked, ba.lock_country, ba.last_ip, ba.failed_logins, bab.unbandate > UNIX_TIMESTAMP() OR bab.unbandate = bab.bandate, bab.unbandate = bab.bandate, ba.sha_pass_hash, ba.v, ba.s, a.id, a.username, ab.unbandate > UNIX_TIMESTAMP() OR ab.unbandate = ab.bandate, ab.unbandate = ab.bandate, aa.gmlevel FROM battlenet_accounts ba LEFT JOIN battlenet_account_bans bab ON ba.id = bab.id LEFT JOIN account a ON ba.id = a.battlenet_account LEFT JOIN account_banned ab ON a.id = ab.id AND ab.active = 1 LEFT JOIN account_access aa ON a.id = aa.id AND aa.RealmID = -1 WHERE ba.email = ?"
Table 'auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 84, sql: "UPDATE battlenet_accounts SET v = ?, s = ? WHERE email = ?"
Table 'auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 85, sql: "UPDATE battlenet_accounts SET sessionKey = ?, online = ? WHERE id = ?"
Table 'auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 86, sql: "SELECT ba.id, UPPER(ba.email), ba.locked, ba.lock_country, ba.last_ip, ba.failed_logins, bab.unbandate > UNIX_TIMESTAMP() OR bab.unbandate = bab.bandate, bab.unbandate = bab.bandate, ba.sessionKey, a.id, a.username, ab.unbandate > UNIX_TIMESTAMP() OR ab.unbandate = ab.bandate, ab.unbandate = ab.bandate, aa.gmlevel FROM battlenet_accounts ba LEFT JOIN battlenet_account_bans bab ON ba.id =  bab.id LEFT JOIN account a ON ba.id = a.battlenet_account LEFT JOIN account_banned ab ON a.id = ab.id AND ab.active = 1 LEFT JOIN account_access aa ON a.id = aa.id AND aa.RealmID = -1 WHERE ba.email = ? AND a.username = ?"
Table 'auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 87, sql: "UPDATE battlenet_accounts SET failed_logins = failed_logins + 1 WHERE email = ?"
Table 'auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 88, sql: "UPDATE battlenet_accounts SET last_ip = ?, last_login = NOW(), locale = ?, failed_logins = 0, os = ? WHERE id = ?"
Table 'auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 89, sql: "SELECT rc.numchars, r.id, r.Region, r.Battlegroup, r.gamebuild FROM realmcharacters rc INNER JOIN realmlist r ON rc.realmid = r.id WHERE rc.acctid = ?"
Unknown column 'r.Region' in 'field list'
In mysql_stmt_prepare() id: 90, sql: "INSERT INTO battlenet_accounts (`email`,`sha_pass_hash`) VALUES (?, ?)"
Table 'auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 93, sql: "UPDATE battlenet_accounts SET v = '', s = '', sha_pass_hash = ? WHERE id = ?"
Table 'auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 94, sql: "SELECT 1 FROM battlenet_accounts WHERE id = ? AND sha_pass_hash = ?"
Table 'auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 95, sql: "UPDATE battlenet_accounts SET locked = ? WHERE id = ?"
Table 'auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 96, sql: "UPDATE battlenet_accounts SET lock_country = ? WHERE id = ?"
Table 'auth.battlenet_accounts' doesn't exist
Closing down DatabasePool 'auth'.
Asynchronous connections on DatabasePool 'auth' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'auth' closed.
Could not prepare statements of the Login database, see log for details.
Closing down DatabasePool 'auth'.
Asynchronous connections on DatabasePool 'auth' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'auth' closed.

**Comment by hero2880** [comment]
TrinityCore rev. 32b780bffd31+ 2016-09-23 01:41:44 +0200 (4.3.4 branch) (Win64, Release, Static) (authserver)
<Ctrl-C> to stop.

Using configuration file E:/434-ArkCORE/core/authserver.conf.
Using SSL version: OpenSSL 1.0.2d 9 Jul 2015 (library: OpenSSL 1.0.2d 9 Jul 2015)
Using Boost version: 1.60.0
Automatic database updates are disabled for all databases!
Opening DatabasePool 'ng_auth'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 5.6.27
MySQL server ver: 5.5.5-10.0.16-MariaDB 
Connected to MySQL database at 127.0.0.1
MySQL client library: 5.6.27
MySQL server ver: 5.5.5-10.0.16-MariaDB 
Connected to MySQL database at 127.0.0.1
DatabasePool 'ng_auth' opened successfully. 2 total connections running.
In mysql_stmt_prepare() id: 11, sql: "SELECT a.id, a.username, a.locked, a.lock_country, a.last_ip, a.failed_logins, ab.unbandate > UNIX_TIMESTAMP() OR ab.unbandate = ab.bandate, ab.unbandate = ab.bandate, aa.gmlevel, a.token_key, a.sha_pass_hash, a.v, a.s, a.battlenet_account FROM account a LEFT JOIN account_access aa ON a.id = aa.id LEFT JOIN account_banned ab ON ab.id = a.id AND ab.active = 1 WHERE a.username = ?"
Unknown column 'a.battlenet_account' in 'field list'
In mysql_stmt_prepare() id: 17, sql: "SELECT a.id, a.sessionkey, a.last_ip, a.locked, a.lock_country, a.expansion, a.mutetime, a.locale, a.recruiter, a.os, a.id, aa.gmLevel, bab.unbandate > UNIX_TIMESTAMP() OR bab.unbandate = bab.bandate, ab.unbandate > UNIX_TIMESTAMP() OR ab.unbandate = ab.bandate, r.id FROM account a LEFT JOIN account r ON a.id = r.recruiter LEFT JOIN battlenet_accounts ba ON a.battlenet_account = ba.id LEFT JOIN account_access aa ON a.id = aa.id AND aa.RealmID IN (-1, ?) LEFT JOIN battlenet_account_bans bab ON ba.id = bab.id LEFT JOIN account_banned ab ON a.id = ab.id AND ab.active = 1 WHERE a.username = ? ORDER BY aa.RealmID DESC LIMIT 1"
Table 'ng_auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 45, sql: "UPDATE account SET last_attempt_ip = ? WHERE username = ?"
Unknown column 'last_attempt_ip' in 'field list'
In mysql_stmt_prepare() id: 72, sql: "INSERT INTO logs_ip_actions (account_id,character_guid,type,ip,systemnote,unixtime,time) VALUES (?, ?, ?, (SELECT last_ip FROM account WHERE id = ?), ?, unix_timestamp(NOW()), NOW())"
Table 'ng_auth.logs_ip_actions' doesn't exist
In mysql_stmt_prepare() id: 73, sql: "INSERT INTO logs_ip_actions (account_id,character_guid,type,ip,systemnote,unixtime,time) VALUES (?, ?, ?, (SELECT last_attempt_ip FROM account WHERE id = ?), ?, unix_timestamp(NOW()), NOW())"
Table 'ng_auth.logs_ip_actions' doesn't exist
In mysql_stmt_prepare() id: 74, sql: "INSERT INTO logs_ip_actions (account_id,character_guid,type,ip,systemnote,unixtime,time) VALUES (?, ?, ?, ?, ?, unix_timestamp(NOW()), NOW())"
Table 'ng_auth.logs_ip_actions' doesn't exist
In mysql_stmt_prepare() id: 75, sql: "INSERT INTO logs_ip_actions (account_id,character_guid,type,ip,systemnote,unixtime,time) VALUES ((SELECT id FROM account WHERE username = ?), 0, 1, ?, ?, unix_timestamp(NOW()), NOW())"
Table 'ng_auth.logs_ip_actions' doesn't exist
In mysql_stmt_prepare() id: 80, sql: "INSERT INTO account_muted VALUES (?, UNIX_TIMESTAMP(), ?, ?, ?)"
Table 'ng_auth.account_muted' doesn't exist
In mysql_stmt_prepare() id: 82, sql: "DELETE FROM account_muted WHERE guid = ?"
Table 'ng_auth.account_muted' doesn't exist
In mysql_stmt_prepare() id: 83, sql: "SELECT ba.id, UPPER(ba.email), ba.locked, ba.lock_country, ba.last_ip, ba.failed_logins, bab.unbandate > UNIX_TIMESTAMP() OR bab.unbandate = bab.bandate, bab.unbandate = bab.bandate, ba.sha_pass_hash, ba.v, ba.s, a.id, a.username, ab.unbandate > UNIX_TIMESTAMP() OR ab.unbandate = ab.bandate, ab.unbandate = ab.bandate, aa.gmlevel FROM battlenet_accounts ba LEFT JOIN battlenet_account_bans bab ON ba.id = bab.id LEFT JOIN account a ON ba.id = a.battlenet_account LEFT JOIN account_banned ab ON a.id = ab.id AND ab.active = 1 LEFT JOIN account_access aa ON a.id = aa.id AND aa.RealmID = -1 WHERE ba.email = ?"
Table 'ng_auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 84, sql: "UPDATE battlenet_accounts SET v = ?, s = ? WHERE email = ?"
Table 'ng_auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 85, sql: "UPDATE battlenet_accounts SET sessionKey = ?, online = ? WHERE id = ?"
Table 'ng_auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 86, sql: "SELECT ba.id, UPPER(ba.email), ba.locked, ba.lock_country, ba.last_ip, ba.failed_logins, bab.unbandate > UNIX_TIMESTAMP() OR bab.unbandate = bab.bandate, bab.unbandate = bab.bandate, ba.sessionKey, a.id, a.username, ab.unbandate > UNIX_TIMESTAMP() OR ab.unbandate = ab.bandate, ab.unbandate = ab.bandate, aa.gmlevel FROM battlenet_accounts ba LEFT JOIN battlenet_account_bans bab ON ba.id =  bab.id LEFT JOIN account a ON ba.id = a.battlenet_account LEFT JOIN account_banned ab ON a.id = ab.id AND ab.active = 1 LEFT JOIN account_access aa ON a.id = aa.id AND aa.RealmID = -1 WHERE ba.email = ? AND a.username = ?"
Table 'ng_auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 87, sql: "UPDATE battlenet_accounts SET failed_logins = failed_logins + 1 WHERE email = ?"
Table 'ng_auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 88, sql: "UPDATE battlenet_accounts SET last_ip = ?, last_login = NOW(), locale = ?, failed_logins = 0, os = ? WHERE id = ?"
Table 'ng_auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 89, sql: "SELECT rc.numchars, r.id, r.Region, r.Battlegroup, r.gamebuild FROM realmcharacters rc INNER JOIN realmlist r ON rc.realmid = r.id WHERE rc.acctid = ?"
Unknown column 'r.Region' in 'field list'
In mysql_stmt_prepare() id: 90, sql: "INSERT INTO battlenet_accounts (`email`,`sha_pass_hash`) VALUES (?, ?)"
Table 'ng_auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 93, sql: "UPDATE battlenet_accounts SET v = '', s = '', sha_pass_hash = ? WHERE id = ?"
Table 'ng_auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 94, sql: "SELECT 1 FROM battlenet_accounts WHERE id = ? AND sha_pass_hash = ?"
Table 'ng_auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 95, sql: "UPDATE battlenet_accounts SET locked = ? WHERE id = ?"
Table 'ng_auth.battlenet_accounts' doesn't exist
In mysql_stmt_prepare() id: 96, sql: "UPDATE battlenet_accounts SET lock_country = ? WHERE id = ?"
Table 'ng_auth.battlenet_accounts' doesn't exist
Closing down DatabasePool 'ng_auth'.
Asynchronous connections on DatabasePool 'ng_auth' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'ng_auth' closed.
Could not prepare statements of the Login database, see log for details.
Closing down DatabasePool 'ng_auth'.
Asynchronous connections on DatabasePool 'ng_auth' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'ng_auth' closed.

**Comment by gpn39f** [comment]
you can't use trinity core to open arkcore ng database..

**Comment by hero2880** [comment]
Sorry,can't use TC core;so, what is it?Please explain in detail.Thanks!

**Comment by hero2880** [comment]
Oh,It suit for mangos core only.
