### ISSUE TITLE
Looking For  installation instructions

### ISSUE THREAD

**Issue by hero2880** [Arkania/ArkCORE-NG#186]
HI!Can anybody provide  instructions of installation? Forums can not  be registered.

**Comment by gpn39f** [comment]
you can send me a private message in forum.. then i help you with install..

**Comment by hero2880** [comment]
sorry,i can't register here,so i can't login forum. upset...
Would you simply talk about  it here?Thanks!

**Comment by gpn39f** [comment]
this hacked forum is a bad forum..
there are many people that receive email for every message written here..
maybe better you look at my private forum..  gpn39f.spdns.de/forum

**Comment by hero2880** [comment]
Thank you very much!this portal i can login.
