### ISSUE TITLE
server crash 

### ISSUE THREAD

**Issue by cnmir2** [Arkania/ArkCORE-NG#187]
server crash !
when you create a new  undead  character  then doing the  quest  : [The Shadow Grave]
after loot the quest item  server crash!

**Comment by gpn39f** [comment]
created new character, hunter..  
played quest without falure..
pls. send me a crash log

**Comment by cnmir2** [comment]
error logs:
SmartAIMgr::LoadSmartAIFromDB: Creature entry (72726) does not exist, skipped loading.
AchievementMgr::CompletedAchievement(5777). Player: Gecc (11)

myabe i have not the lastest db some  database structure is not up to date  or  some Tables doesn't exist.
such as:
Table `gameobject` has gameobject (GUID: 400781) with non existing gameobject entry 600047, skipped.
Possible FIX: INSERT INTO 'creature_loot_template' (insert dropped loot items for Creature 3. only found by sniff)
Table 'creature_loot_template' Entry 39397 does not exist but it is used by Creature 39397

ty very much frank:) could you send me the lastest the world.sql?? that will very appreciated

**Comment by gpn39f** [comment]
this is the fileserver for latest snapshoot..

https://drive.google.com/open?id=0B8q0yc6MkL0naTdpN2xiT2s1bTg

**Comment by cnmir2** [comment]
frank  use your world.sql  but also server crash  
1  when you create a new undead character then doing the quest : [The Shadow Grave]
after loot the quest item server crash!
2  you create two account  one doing the quest "The Shadow Grave"after loot the quest item the server not crash 
then you logo in the other account and also accept the same quest  "The Shadow Grave" this time  you go  into the quest loot item  site  wait some minute  the server crash!! 
3 when  i create third acount and not dong any quest  the server auto crash !

**Comment by cnmir2** [comment]
this is dberror 

LinkedRespawn: Creature '254315' linking to Creature '254168' on an unpermitted map.
game_event_save includes event save for non-worldevent id 33
game_event_save includes event save for non-worldevent id 34
game_event_save includes event save for non-worldevent id 35
game_event_save includes event save for non-worldevent id 36
game_event_save includes event save for non-worldevent id 37
game_event_save includes event save for non-worldevent id 38
game_event_save includes event save for non-worldevent id 39
game_event_save includes event save for non-worldevent id 40
game_event_save includes event save for non-worldevent id 41
game_event_save includes event save for non-worldevent id 43
game_event_save includes event save for non-worldevent id 44
game_event_save includes event save for non-worldevent id 45
game_event_save includes event save for non-worldevent id 46
game_event_save includes event save for non-worldevent id 47
Spell (ID: 82175) not have MECHANIC_DISCOVERY (28) value in Mechanic field in spell.dbc and not 100% chance random discovery ability but listed for spellId 82180 (and maybe more) in `skill_discovery_template` table
Spell (ID: 81275) not have MECHANIC_DISCOVERY (28) value in Mechanic field in spell.dbc and not 100% chance random discovery ability but listed for spellId 82180 (and maybe more) in `skill_discovery_template` table

> > Loaded 47 achievement references in 0 ms
> > Loaded 9803 achievement criteria and 952 guild achievement crieteria in 3 ms
> > Loaded 2420 additional achievement criteria data in 3 ms
> > Loaded 134 achievement rewards in 0 ms
> > Loaded 117 achievement reward locale strings in 1 ms
> > Loaded 0 realm first completed achievements in 0 ms
> > Script named 'npc_kezan_partygoer_35175_86' does not have a script name assigned in database.
> > AchievementMgr::CompletedAchievement(5777). Player: Geds (5)
> > LinkedRespawn: Creature '254315' linking to Creature '254168' on an unpermitted map.
> > game_event_save includes event save for non-worldevent id 33
> > game_event_save includes event save for non-worldevent id 34
> > game_event_save includes event save for non-worldevent id 35
> > game_event_save includes event save for non-worldevent id 36
> > game_event_save includes event save for non-worldevent id 37
> > game_event_save includes event save for non-worldevent id 38
> > game_event_save includes event save for non-worldevent id 39
> > game_event_save includes event save for non-worldevent id 40
> > game_event_save includes event save for non-worldevent id 41
> > game_event_save includes event save for non-worldevent id 43
> > game_event_save includes event save for non-worldevent id 44
> > game_event_save includes event save for non-worldevent id 45
> > game_event_save includes event save for non-worldevent id 46
> > game_event_save includes event save for non-worldevent id 47
> > Spell (ID: 82175) not have MECHANIC_DISCOVERY (28) value in Mechanic field in spell.dbc and not 100% chance random discovery ability but listed for spellId 82180 (and maybe more) in `skill_discovery_template` table
> > Spell (ID: 81275) not have MECHANIC_DISCOVERY (28) value in Mechanic field in spell.dbc and not 100% chance random discovery ability but listed for spellId 82180 (and maybe more) in `skill_discovery_template` table
> > Loaded 47 achievement references in 0 ms
> > Loaded 9803 achievement criteria and 952 guild achievement crieteria in 3 ms
> > Loaded 2420 additional achievement criteria data in 4 ms
> > Loaded 134 achievement rewards in 1 ms
> > Loaded 117 achievement reward locale strings in 1 ms
> > Loaded 0 realm first completed achievements in 0 ms
> > Script named 'npc_kezan_partygoer_35175_86' does not have a script name assigned in database.
> > AchievementMgr::CompletedAchievement(5777). Player: Testg (6)
> > GOSSIP_OPTION_TRAINER:: Player Testg (GUID: 6) request wrong gossip menu: 0 with wrong class: 1 at Creature: Bamm Megabomb (Entry: 34673, Trainer Class: 3)
> > GOSSIP_OPTION_TRAINER:: Player Testg (GUID: 6) request wrong gossip menu: 0 with wrong class: 1 at Creature: Bamm Megabomb (Entry: 34673, Trainer Class: 3)
> > AchievementMgr::CompletedAchievement(5777). Player: De (7)

**Comment by cnmir2** [comment]
frank if this is  my map vmap dbc or mmap problem???

**Comment by gpn39f** [comment]
look at forum: http://gpn39f.spdns.de/forum

**Comment by cnmir2** [comment]
i use your a b c d.zip file for map vmap dbc  mmap from old forum!

**Comment by cnmir2** [comment]
i am login in your forum!

**Comment by cnmir2** [comment]
frank the server crash when you accept the quest  The Shadow Grave you waiting the quest giving your a  npc to leading you to the quest item site  then server crash!

**Comment by cnmir2** [comment]
@gpn39f  test serveral times the problem also have if anyone could test it ??
when create a  undead character and inter into  the server ,do some quest or not  for some miniute  the server crash !  i test this problem when a  create a undead hunter and warior ,but i create the undead priest server not crash! why ??  if you  Encountered such a problem? but the worldserver have not Error Display！

**Comment by cnmir2** [comment]
i also test this problem use another computers when a enter  into the server  the npc show unkown npc!?

**Comment by gpn39f** [comment]
@cnmir2 i have checked it several times.. there is no failure to find..
maybe you should do a simple test:
go into navicat.. click on youre ng world
and choose dump with structure..
then you have produced same file, as you can download as snapshoot..
both should have same size!!
pls check the size of both files: ng_world from snapshoot, and from you're database..

**Comment by cnmir2** [comment]
frank  i will try !! and give feedback!! awesome ark ng

**Comment by ghost** [comment]
Confirmed, accepting this quest crashes the server. On rare occasions you can complete the quest, most of the time the server will just hang.

**Comment by cnmir2** [comment]
frank i  create a warlock complete the first quest  the server crash ! 

there is the log

No defined handler for opcode [CMSG_MOVE_FALL_RESET 0x310A (12554)] sent by [Player: Goy (Guid: 3, Account: 9)]
No defined handler for opcode [CMSG_MOVE_FALL_RESET 0x310A (12554)] sent by [Player: Goy (Guid: 3, Account: 9)]

**Comment by cnmir2** [comment]
i compile new source by vs2015 ! win32

**Comment by gpn39f** [comment]
retry now

**Comment by cnmir2** [comment]
frank  i try to compile using debug mode to test !

**Comment by cnmir2** [comment]
compile new source by vs2015 ! win32 also crash !

**Comment by shinebayar-g** [comment]
If this crash happens I'll provide bypass solution.
