### ISSUE TITLE
Worgen (string bug missions)

### ISSUE THREAD

**Issue by warlokowla** [Arkania/ArkCORE-NG#19]
after the third mission of the worgen not give more missions and fails the next phase.

**Comment by gpn39f** [comment]
gilneas is still in alpha state.. nobody has worked on it..
now I fix the instance of deadmines.. 
after this, gilneas is on the todo list..

**Comment by warlokowla** [comment]
but arkania.de is running the boot area of the worgen. LoL

**Comment by gpn39f** [comment]
this is not the arkcore used on this site.. the owner are using forgottencore on his server. only a few quest are ok, maybe 10, then you are teleported to stormwind,,

**Comment by warlokowla** [comment]
ok,  but there is no solution for the worgen can leave their racial gilneas? no matter how blizzlike, I'm planning to place a server with ArkCORE-NG
