### ISSUE TITLE
ng_world

### ISSUE THREAD

**Issue by Ramys** [Arkania/ArkCORE-NG#190]
ng_world does not install..

**Comment by gpn39f** [comment]
a failure description could be helpfull..

**Comment by Ramys** [comment]
to 44% to tdb lock
and it is not possible to install

**Comment by gpn39f** [comment]
youre shure this is a failure description??

ps:
have you done all updates from core/update/world ??

**Comment by Ramys** [comment]
This is error
Query:
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `size`, `Data0`, `Data1`, `Data2`, `Data3`, `Data4`, `Data5`, `Data6`, `Data7`, `Data8`, `Data9`, `Data10`, `Data11`, `Data12`, `Data13`, `Data14`, `Data15`, `Data16`, `Data17`, `Data18`, `Data19`, `Data20`, `Data21`, `Data22`, `Data23`, `Data24`, `Data25`, `Data26`, `Data27`, `Data28`, `Data29`, `Data30`, `Data31`, `unkInt32`, `AIName`, `ScriptName`, `WDBVerified`) VALUES (220864, 9, 3171, 'Iron Tomb', '', '', '', 1.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 18019)

Error occured at:2016-09-22 12:16:27
Line no.:1
Error Code: 1136 - Column count doesn't match value count at row 1

Error occured at:2016-10-31 14:25:41
Line no.:2148183
Error Code: 2006 - MySQL server has gone away

**Comment by gpn39f** [comment]
i think the error is : Error Code: 2006 - MySQL server has gone away
look at our snapshoot folder
there is a readme file to this error..

https://drive.google.com/drive/folders/0B8q0yc6MkL0naTdpN2xiT2s1bTg?usp=sharing
