### ISSUE TITLE
Npcs disappear

### ISSUE THREAD

**Issue by Ramys** [Arkania/ArkCORE-NG#191]
when entering stormwind NPCs disappear!
any suggestion?

**Comment by gpn39f** [comment]
yes i beleave there is a phase failure.. i will look at it when finished here in lost island..

**Comment by cnmir2** [comment]
yes  i also have this promblem only gm could see the npc!
@Ramys  if you have this problem when create a  undead character and inter into  the server ,do some quest or not  for some miniute  the server crash !  i test this problem when a  create a undead hunter and warior ,but i create the undead priest server not crash! why ??  if you  Encountered such a problem?
