### ISSUE TITLE
Crash in sholazar

### ISSUE THREAD

**Issue by Desarrollo-zeros** [Arkania/ArkCORE-NG#193]
Good excuse there is an error in the map sholazar the server falls when entering the x zone

Command: .tele sholazar [Player: Infierno (Guid: 14) (Account: 9) X: -9447.334 Y: -1299.607544 Z: 43.558819 O: 4.980857 Map: 
ArkCORE>Segmentation fault

![15134029_1511475832201342_965381121_o](https://cloud.githubusercontent.com/assets/23331674/20332688/a298f114-ab7b-11e6-94c2-a1237b9306ca.jpg)

**Comment by cnmir2** [comment]
@Desarrollo-zeros could you have this crash  condition when create a new undead character  play sometime the server crash

**Comment by Desarrollo-zeros** [comment]
![captura](https://cloud.githubusercontent.com/assets/23331674/20332944/3d5080e0-ab7d-11e6-9f1e-71a5191e0467.PNG)

**Comment by Desarrollo-zeros** [comment]
not @cnmir2

**Comment by gpn39f** [comment]
please close issue if fix is ok..
