### ISSUE TITLE
Visual bug in objects, speed drops, disappearance when restarting or dropping object server 

### ISSUE THREAD

**Issue by Desarrollo-zeros** [Arkania/ArkCORE-NG#194]
Hi when using gm fly on command and use modi speed 10++ die speed 50 and fly cuasa server overflow, pinfo command overflows the realm, Also When placing an object in the wow is normally seen and checked the DB I have the same is seen, but in the DB does not register it in the orientation part appears in 0, Also when restarting the server everything is lost you see nothing of the objects placed, but if there is a record in the DB of the objects, but no data in orientation
![image](https://cloud.githubusercontent.com/assets/23331674/20375730/fb1dcf84-ac4e-11e6-8c77-53777f809627.png)
![image](https://cloud.githubusercontent.com/assets/23331674/20375740/0bfd5842-ac4f-11e6-8be2-106f493bb15b.png)
![image](https://cloud.githubusercontent.com/assets/23331674/20375748/1a81f3a0-ac4f-11e6-8803-399d7385bbf2.png)

**Comment by Desarrollo-zeros** [comment]
ArkCORE>Player::addSpell: Non-existed in SpellStore spell #21184 request.
Player::_LoadMail - Mail (16) have not existed MailTemplateId (15415), remove at load
Segmentation fault

Error using command pinfo kills the kingdom
root@wow:~/Server/CataI/bin#

**Comment by cnmir2** [comment]
@Desarrollo-zeros    could you send me the auth.sql and characters.sql please ? i always got crash at undead start point ! i want to test if the crash is cause by that two database! i will very apreciated 
ty very much!

**Comment by Desarrollo-zeros** [comment]
Gracias Estaré posteado mas errores que encuentre que sean fatales para el source
