### ISSUE TITLE
crash pic show 

### ISSUE THREAD

**Issue by cnmir2** [Arkania/ArkCORE-NG#196]
![qq 20161118162504](https://cloud.githubusercontent.com/assets/14962131/20423520/baafd830-adab-11e6-8441-15c745f7f101.png)
![qq 20161118162441](https://cloud.githubusercontent.com/assets/14962131/20423523/bb21db1a-adab-11e6-9921-fe83a057f167.png)

![qq 20161118162659](https://cloud.githubusercontent.com/assets/14962131/20423541/e0a9e350-adab-11e6-936c-578403d00347.png)

**Comment by cnmir2** [comment]
in  gilneas when complete  this quest the server crash?


![Uploading QQ图片20161118164440.png…]()

**Comment by gpn39f** [comment]
fixed
