### ISSUE TITLE
Crash in firelands near raid portal.

### ISSUE THREAD

**Issue by ghost** [Arkania/ArkCORE-NG#198]
Compiled VS 2015 (Release 64bit)

When you arrive at firelands, everything seems to work great. Wait about 5 minutes and the server will terminate with no error.

ArkCORE4-NG rev. 1970-01-01 00:00:00 +0000 (unknown) (Win64, Release) (worldserver-daemon) ready...
Player::_LoadMail - Mail (1) have not existed MailTemplateId (4259), remove at load
Halting process...

**Comment by cnmir2** [comment]
hi @Xelpherpolis  firelands ？ could you give gps let me to test it ??

**Comment by ghost** [comment]
Just use .tele Firelands just standing here for a while caused the server to lock up, also going into the raid and then exiting made the server lockup and begin to shutdown.

Edit: CONFIRMED, Walking in to the raid instance and then out causes the server to shut down after 3 minutes. It is something to do with the raid.

ArkCORE4-NG rev. 1970-01-01 00:00:00 +0000 (unknown) (Win64, RelWithDebInfo) (worldserver-daemon) ready...
Player::_LoadMail - Mail (1) have not existed MailTemplateId (4259), remove at load
Halting process...

**Comment by cnmir2** [comment]
.tele  maybe .go  where ! could you give Explicit coordinates？

**Comment by ghost** [comment]
Use the command ".tele Firelands" you appear directly in front of the Firelands raid portal. Go inside, and come back out. After about 2 to 3 minutes the server will shut down.

This area also kills the server dead "Twilight Highlands" - Crashes Server

Edit: ALL RAIDS - Crash the server upon leaving them after 2 minutes.

ArkCORE4-NG rev. 1970-01-01 00:00:00 +0000 (unknown) (Win64, RelWithDebInfo) (worldserver-daemon) ready...
Player::_LoadMail - Mail (1) have not existed MailTemplateId (4259), remove at load
World Thread hangs, kicking out server!

(Why is the server not providing crash dumps, this is nearly impossible to pinpoint)

**Comment by cnmir2** [comment]
test it !server crash! @Xelpherpolis could you test other raild have same crash ?

**Comment by ghost** [comment]
Tested, all raids crash and teleporting to ICC (.tele ICC) crashes and (.tele citadel) crashes too.

**Comment by ghost** [comment]
I have a feeling some of these crashes could be to do with MYSQL, when I was using 5.6 these crashes occurred, now I have updated to 5.7 I am not getting any crashes (YET)

**Comment by cnmir2** [comment]
@Xelpherpolis  are you use the xammp?? or ?

**Comment by ghost** [comment]
https://dev.mysql.com/downloads/mysql/ (Get the latest version)

**Comment by cnmir2** [comment]
i will test it !!

**Comment by cnmir2** [comment]
@Xelpherpolis  your server not crash unil now  using the mysql 5.7??

**Comment by ghost** [comment]
So far it has been running good with MYSQL 5.7 

@cnmir2 have you tried mysql 5.7 yet?

**Comment by cnmir2** [comment]
today is busing i want to test it yesterday ! are the raids and dungeons have bugs?

**Comment by cnmir2** [comment]
i updata 5.7 also crash

**Comment by ghost** [comment]
Have you made sure to compile to the latest core? As a few fixes were posted yesterday.

**Comment by cnmir2** [comment]
maybe not this problem you first .tele icc then second time  not crash!

**Comment by cnmir2** [comment]
you compile  win32?

**Comment by ghost** [comment]
64bit Windows Release

**Comment by cnmir2** [comment]
how could you compile 64bit ?could you show some pics ?  ty

**Comment by cnmir2** [comment]
i compile 64x and test it

**Comment by cnmir2** [comment]
not crash  so far  using new compile

**Comment by cnmir2** [comment]
when i .tele citadel not crash but when i logout  the server crash !! today is busing i will go fuirther test  tomorrow

**Comment by gpn39f** [comment]
fixed
