### ISSUE TITLE
World Server Stopping Spell_phase  

### ISSUE THREAD

**Issue by Taaboy** [Arkania/ArkCORE-NG#199]
Server has no issues from repack (exe's) from your cloud and all updates to 2016_11_15_02.
Problem arises =
Latest Core compile and all updates applied , except with update 2016_11_15_03_world fails to insert text missing field .
if update not applied this world error
>> Loaded 30 phase areas in 0 ms.
Loading Spell Phase...
**[1054] Unknown column 'id' in 'field list'
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.**

**Comment by Taaboy** [comment]
But Great work to you all , and hats off to all,

**Comment by gpn39f** [comment]
the server update from 2016_11_07_01_world_434.sql
has a new structure for the spell_phase
there is the id inserted..

**Comment by Taaboy** [comment]
thank you fixed problem ,, the only script I missed...
