### ISSUE TITLE
Kezan Start Island PhaseId Updates required

### ISSUE THREAD

**Issue by Taaboy** [Arkania/ArkCORE-NG#202]
Kezan Start Area
Creature_Template Ids to Creature Guid: PhaseIds

Entry: 35236, 48806 .PhaseIds: 379 (Party Goers and  Waiters)
Entry: 35202 ,35200.PhaseIds:380  (Pirate Crashers ,Scared Party Goers)
Entry:  35238 PhaseIds:381 (After Party Goers)
Entry: 35234. PhaseIds: 383 Hired Looter
Entry  37602, 37683 ,35222(GUID:245957)  PhaseIds; 384  (Claims Adjuster , Villa Mook , Trade Prince on the Ship)

GameOjects Need to Phase

objects 168605 (Entry: 201736) - [Gasbot Control Panel X:-8422.509766 Y:1325.680054 Z:101.916000 MapId:648] PhaseIds: 382 383 384

objects 400902 (Entry: 187117) - [Stairway to Mercy X:-7867.640137 Y:1832.540039 Z:3.083700 MapId:648] PhaseId: 384

**Comment by gpn39f** [comment]
there are more phase work to do in core..
so if that is done, i will re-phase gilneas, kezan and lost-island..
