### ISSUE TITLE
Revision on Linux

### ISSUE THREAD

**Issue by Jiinx** [Arkania/ArkCORE-NG#21]
Linux git works slightly different than the windows version, in order to properly get versionstring, tags must be present.

Warning/Error:

> Could not find a proper repository signature (hash) - you may need to pull tags with git fetch -t
> Continuing anyway - note that the versionstring will be set to "unknown 1970-01-01 00:00:00 (Archived)"

Suggestion: push tags

```
git push origin --tags
```

**Comment by gpn39f** [comment]
I'm using git extension as gui for git.
in config I was search about this, and I can activate a script, used after pull, to execute git fetch -t
is this the neccasary command for this event??? or should I use git fetch without -t as mentioned in some tutorials..

**Comment by Jiinx** [comment]
git fetch -t would the solution on the users end, you as the author need to push tags

for git extensions; right click on repo, git extensions -> push
click on [tags] tab, and choose [all], click "push"

done

**Comment by gpn39f** [comment]
thanks.. :-) I will do that with next upload..

may I ask:
what will this do?? create a auto versions string, or only a hash, or a "timestring" tag???

**Comment by ghost** [comment]
Thank you jinx, I was wondering about the revision not showing. But in windows it won't show up as well... All the compilations I made have that lack

**Comment by Jiinx** [comment]
@gpn39f This only pushes the tags need so that versionstring can be populated with the hash properly.

@ethyrie, I don't use windows for this, so I am not aware if the same problem exists. If so, this should resolve for both.

**Comment by gpn39f** [comment]
not working for me..i was try different with pull and push, change some cmake macros.. but nothing brings the needed tag..

**Comment by Jiinx** [comment]
Now that tags have been push, revision shows on Linux.. good job!!

**Comment by gpn39f** [comment]
I have to take latest pushed element on github.
write the hash down.. puhhhhhaaaa....o long one.. :-)
go in my local repro and call from github console 
git tag -a v7.6.9 hash....
git push --tag
then go in cmake.. clear cache.. rerun cmake..
found tag.. traaraaa :-)
but now I think: this is bad allways doing so from console..  so I seek now a automated method..
