### ISSUE TITLE
quest  [Cities in Dust]27601  bug 

### ISSUE THREAD

**Issue by cnmir2** [Arkania/ArkCORE-NG#210]
http://www.wowhead.com/quest=27601/cities-in-dust

**Comment by Lumber-Jack-2** [comment]
these bugreports are shit. describe what should happen, include ids, screenshots, videos etc.

**Comment by cnmir2** [comment]
@frank  whether  my submits bugs  is simple?    if  you need the further details i will go on to give more details include ids  screenshots, videos !

@Rushor could you give a standard bug report pattern pls? 
these quest bugs is be easy to see !such as: you could add quest 27601 then go there to try!

**Comment by gpn39f** [comment]
point is: i have to reproduce the failure..
sometimes i have no character on same state as you..
so i have to create a new char.. what race??? what class?? what level???
then i have to add the quest or prequest, needed items..
you see.. i have to do much before i can start to look at youre failure..

and then: what i have to look at..  
missing item?? missing questgiver? no target?? 

have this in mind before you write the issue..
sometimes it is better to ask in forum: all git follower are receiving email for every issue you are writing to..

**Comment by cnmir2** [comment]
ok frank  ! i will submit the issure more details and let  you more easily to test !!  have good night!! :+1:
