### ISSUE TITLE
wolf start   npc  prince liam greymane will give you two quest but when you accept one  anther will not accept  

### ISSUE THREAD

**Issue by cnmir2** [Arkania/ArkCORE-NG#213]
wolf start      npc  prince liam greymane will give you two quest but when you accept one  anther will not accept  maybe not  a bug : 

![1](https://cloud.githubusercontent.com/assets/14962131/20662845/304926b4-b590-11e6-8006-0e32323fca40.png)
![2](https://cloud.githubusercontent.com/assets/14962131/20662848/31cc11c2-b590-11e6-91ec-143d9928e90e.png)
![3](https://cloud.githubusercontent.com/assets/14962131/20662849/32dff39e-b590-11e6-9ffe-a73219a5e088.png)

**Comment by gpn39f** [comment]
only one of the two quest you can do..
if you have taken one of the two quest , the other is hidden..

http://wow.gamepedia.com/Quest:You_Can%27t_Take_%27Em_Alone
