### ISSUE TITLE
Valley of Trials Warlock Immolate Quest

### ISSUE THREAD

**Issue by Taaboy** [Arkania/ArkCORE-NG#215]
Orc Start Area
Warlock Immolate Quest(25145)
Immolate not counting, the SQL entry looks good to my limited knowledge.
Target Dummy's casting immolate not counting to quest and unable to complete, in the normal account setting.

On another note Thank you for the great work you have been doing, and ty in advance for the fix's to come along

TAABOY

**Comment by gpn39f** [comment]
on upcoming WOD some of the starting quest: related to tranings dummy: are rewritten.
blizz* has changed questtext or changed wanted spellcast, or 
blizz* has removed part of quests..
and what i have seen: 
some of our quest-text are now from WOD..
so: the quest-text tell you, you have to learn spell A.. but core are waiting for old spell B.. 

to look at quest: you should never use wowhead.. this is maybe the source of the failure in our db..
better to use : https://cata-twinhead.twinstar.cz/

if you see more of this quest is wrong: please report them to..
i will repair this in next month..

**Comment by Taaboy** [comment]
No Problem , I used the internal .lookup quest id. I have applied to the new forums, just waiting for confirmation email.

**Comment by Taaboy** [comment]
Warlock Immolate Quest 25145 , Has wrong entry into the RequiredNpcOrGo1 Value set atm= 44820 but requires 44175 to work . no other changes required tested and quest works as it should , other quests for that dummy entry for quest RequireNpcOrGo1 may need to be looked at also

**Comment by gpn39f** [comment]
imported.. update on next upload..

**Comment by Taaboy** [comment]
TY
