### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Khell88** [Arkania/ArkCORE-NG#216]
Maybe this is an of topic but I already compile the source code the only thing that's keeping me from test it it's that I don't know where to get the DB. I'm interested in testing and contribute in this current work, so if any can help me to find a way to get de db I'll preciate that.

**Comment by gpn39f** [comment]
our forum is hacked.. the owner is missed..

so we have a little help-forum.. http://gpn39f.spdns.de/forum/

our monthly database snapshoot you can find here : 
https://drive.google.com/open?id=0B8q0yc6MkL0naTdpN2xiT2s1bTg
