### ISSUE TITLE
Warlock Spells Problems

### ISSUE THREAD

**Issue by Taaboy** [Arkania/ArkCORE-NG#217]
Warlock Spell (689) Drain Life - No return of life/health the use of the spell
Warlock Spell (1120) Drain Soul - No return of soul shards the use of the spell
Level 10 Orc Warlock

**Comment by Taaboy** [comment]
I have fixed and tested the warlock script for those 2 spell above and is working uploading you the warlock script to inspect it .  http://pastebin.com/GLuZR7Dv

**Comment by gpn39f** [comment]
can you send the sql part: for new 3 spell scripts ?

**Comment by Taaboy** [comment]
needs no new sql entrys   , they are the last three on the script above,

**Comment by gpn39f** [comment]
mmmhhh...
every spell script that has a class in script folder has a entry in table spell_script_names..
here you must insert the rank of the spell to..

the entry in table spell_script_names activate the script in script-manager..
without activating: no working script..

**Comment by Taaboy** [comment]
well ? it worked I checked wotlk , cata , mop spell_warlock.cpp and that was missing for that spells for them ,they were all the same entry's into all spell_warlock.cpp, there was more entry's but I was only looking at those 2 spells that had 3 entry's to get them working in the warlock script, I am not that experience with scripts so ,sorry if can 't shed anymore light to that. but it works and scales.(lvl 10 warlock to lvl15 in damage and returns , both soul shards and health.

**Comment by Taaboy** [comment]
i will try to mark them in a different color on the changes in pastebin

**Comment by Taaboy** [comment]
SPELL_WARLOCK_DRAIN_LIFE_HEALTH                 = 89653,
    SPELL_WARLOCK_SOULSHARD_ADD                     = 87388, 
    SPELL_WARLOCK_PANDEMIC                                 = 92931

**Comment by Taaboy** [comment]
made changes and named all last 3 before bottom of script, as above

**Comment by gpn39f** [comment]
pls open you table: "spell_script_names" in navicat or similar..

there you set filter to ScriptName
and search "OR" for the 3 names:

spell_warl_drain_life
spell_warl_drain_soul
spell_warl_pandemic

all lines you find in youre table, we must enter in our table to..

**Comment by Taaboy** [comment]
spell_warl_drain_life = are already in ng_world 
spell_warl_drain_soul = are already in ng_world
spell_warl_pandemic =i had to place in there to stop a error in the drain soul , not in ng_world

**Comment by Taaboy** [comment]
DELETE FROM `spell_script_names` WHERE `spell_id`=89420 AND `ScriptName`='spell_warl_drain_life';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (89420, 'spell_warl_drain_life');
DELETE FROM `spell_script_names` WHERE `spell_id`=689 AND `ScriptName`='spell_warl_drain_life';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (689, 'spell_warl_drain_life');
DELETE FROM `spell_script_names` WHERE `spell_id`=1120 AND `ScriptName`='spell_warl_drain_soul';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (1120, 'spell_warl_drain_soul');

**Comment by Taaboy** [comment]
ok fixed spell_warlock.cpp in pastebin , removed all reference to spell_warl_pandemic and fixed spell_warl_drain_soul , the sql entry's are already in ng_world , i have not added or changed it for those spell_script_names , check with your current base ng_world and they are in there already. and tested with warlock lvl 15 in game
