### ISSUE TITLE
Fix Quest 28138 - Human Infestation 

### ISSUE THREAD

**Issue by Taaboy** [Arkania/ArkCORE-NG#221]
-- Changed RequiredNpcOrGo1 From 47697 to 2269 --
https://github.com/Taaboy/DatabaseFixsCataArkcoreNG/tree/master/sql/quest_fixes

**Comment by gpn39f** [comment]
i have seen youre work.. 
please not delete complete npc, if you only have to change one value..
is heavy to compare this fix..

 Fix Quest 28114 Glorious Harvest --
 : here you add loot .. but the eagg is spawned by spell
https://cata-twinhead.twinstar.cz/?spell=88695

-- Fix Quest 28138 - Human Infestation--
here you change target npc to other type of npc.. this is a bad hack..
the npc 47697  has to be spawned by script.. i'm using core script for this..
(i have not looked near to the quest: maybe the npc has to be spawned by quest accept..)

-- Fix Quest 28146 Coastal Delicacies! --
impossible to verify this fix.. you delete 3 quest. 1 npc...  much better only change the value youre changing..

-- Quest 24992 To be awarded for 24993 continue SmartAI Fix --
our database is wrong.. the infiltrator has to be spawned by darkhound ( as you do in smartAI)
so the spawned infiltrator has to be deleted..
https://cata-twinhead.twinstar.cz/?npc=1547#abilities
