### ISSUE TITLE
How to summon npcbot in game?

### ISSUE THREAD

**Issue by mygithome002** [Arkania/ArkCORE-NG#229]
This is my worldserver.conf
....
Bot.EnableNpcBots = 1

**Comment by gpn39f** [comment]
try as GM
.help npcbot

or as startpoint
.npcbot helper

from the helper you can add/remove bots. change help modus or later change cloth or weapon..

**Comment by mygithome002** [comment]
Thank you !!

**Comment by mygithome002** [comment]
[http://i1.piimg.com/577587/21fd2a3e4dbc016as.jpg](url)

**Comment by mygithome002** [comment]
http://i1.piimg.com/577587/21fd2a3e4dbc016a.jpg
