### ISSUE TITLE
Death Knight startzone (Game breaking things)

### ISSUE THREAD

**Issue by ghost** [Arkania/ArkCORE-NG#23]
This need to be fixed in order to make ArkCORE-NG's DKs playable.

-Acherus as DK Startzone: The mount-npc that gets you up and down in acherus isn't working (Creature id 29488, guid 236848 and 236847)
-"How To Win Friends And Influence Enemies" quest isn't working since you can't really talk with anyone
-"A Meeting With Fate" doesn't bring you the suit and 'the black magic' making you die. A lot.

**Comment by gpn39f** [comment]
fixed npc 29488 for flight down
fixed npc 29501 for flight up
more will come

**Comment by ghost** [comment]
Thanks gpn :D
