### ISSUE TITLE
Compil Error Linux

### ISSUE THREAD

**Issue by KwazarFr** [Arkania/ArkCORE-NG#233]
Todays error when compiling the latest build.

Linux Debian 8

`[ 30%] Building CXX object src/server/game/CMakeFiles/game.dir/Chat/Chat.cpp.o
/home/servers/cata/ArkCORE-NG/src/server/game/Chat/Chat.cpp: In function ‘std::string str_tolower(std::string)’:
/home/servers/cata/ArkCORE-NG/src/server/game/Chat/Chat.cpp:89:71: error: no matching function for call to ‘transform(std::basic_string<char>::iterator, std::basic_string<char>::iterator, std::basic_string<char>::iterator, <unresolved overloaded function type>)’
    std::transform(text.begin(), text.end(), text.begin(), std::tolower);
                                                                       ^
/home/servers/cata/ArkCORE-NG/src/server/game/Chat/Chat.cpp:89:71: note: candidates are:
In file included from /usr/include/c++/4.9/algorithm:62:0,
                 from /usr/local/include/ace/Intrusive_List.inl:5,
                 from /usr/local/include/ace/Intrusive_List.h:128,
                 from /usr/local/include/ace/Cleanup.h:30,
                 from /usr/local/include/ace/Object_Manager_Base.h:28,
                 from /usr/local/include/ace/OS_NS_stdlib.inl:6,
                 from /usr/local/include/ace/OS_NS_stdlib.h:449,
                 from /usr/local/include/ace/OS_Memory.h:337,
                 from /usr/local/include/ace/OS_NS_Thread.h:36,
                 from /usr/local/include/ace/Thread_Mutex.h:31,
                 from /usr/local/include/ace/Atomic_Op.h:23,
                 from /usr/local/include/ace/Event_Handler.h:24,
                 from /usr/local/include/ace/Service_Object.h:24,
                 from /usr/local/include/ace/Task.h:17,
                 from /usr/local/include/ace/Svc_Handler.h:25,
                 from /home/servers/cata/ArkCORE-NG/src/server/game/Server/WorldSocket.h:31,
                 from PrecompiledHeaders/gamePCH.h:3:
/usr/include/c++/4.9/bits/stl_algo.h:4152:5: note: template<class _IIter, class _OIter, class _UnaryOperation> _OIter std::transform(_IIter, _IIter, _OIter, _UnaryOperation)
     transform(_InputIterator __first, _InputIterator __last,
     ^
/usr/include/c++/4.9/bits/stl_algo.h:4152:5: note:   template argument deduction/substitution failed:
/home/servers/cata/ArkCORE-NG/src/server/game/Chat/Chat.cpp:89:71: note:   couldn't deduce template parameter ‘_UnaryOperation’
    std::transform(text.begin(), text.end(), text.begin(), std::tolower);
                                                                       ^
In file included from /usr/include/c++/4.9/algorithm:62:0,
                 from /usr/local/include/ace/Intrusive_List.inl:5,
                 from /usr/local/include/ace/Intrusive_List.h:128,
                 from /usr/local/include/ace/Cleanup.h:30,
                 from /usr/local/include/ace/Object_Manager_Base.h:28,
                 from /usr/local/include/ace/OS_NS_stdlib.inl:6,
                 from /usr/local/include/ace/OS_NS_stdlib.h:449,
                 from /usr/local/include/ace/OS_Memory.h:337,
                 from /usr/local/include/ace/OS_NS_Thread.h:36,
                 from /usr/local/include/ace/Thread_Mutex.h:31,
                 from /usr/local/include/ace/Atomic_Op.h:23,
                 from /usr/local/include/ace/Event_Handler.h:24,
                 from /usr/local/include/ace/Service_Object.h:24,
                 from /usr/local/include/ace/Task.h:17,
                 from /usr/local/include/ace/Svc_Handler.h:25,
                 from /home/servers/cata/ArkCORE-NG/src/server/game/Server/WorldSocket.h:31,
                 from PrecompiledHeaders/gamePCH.h:3:
/usr/include/c++/4.9/bits/stl_algo.h:4189:5: note: template<class _IIter1, class _IIter2, class _OIter, class _BinaryOperation> _OIter std::transform(_IIter1, _IIter1, _IIter2, _OIter, _BinaryOperation)
     transform(_InputIterator1 __first1, _InputIterator1 __last1,
     ^
/usr/include/c++/4.9/bits/stl_algo.h:4189:5: note:   template argument deduction/substitution failed:
/home/servers/cata/ArkCORE-NG/src/server/game/Chat/Chat.cpp:89:71: note:   candidate expects 5 arguments, 4 provided
    std::transform(text.begin(), text.end(), text.begin(), std::tolower);
                                                                       ^
/home/servers/cata/ArkCORE-NG/src/server/game/Chat/Chat.cpp: In function ‘std::string str_trim(std::string&)’:
/home/servers/cata/ArkCORE-NG/src/server/game/Chat/Chat.cpp:112:37: error: invalid initialization of non-const reference of type ‘std::string& {aka std::basic_string<char>&}’ from an rvalue of type ‘std::string {aka std::basic_string<char>}’
     return str_ltrim(str_rtrim(text));
                                     ^
/home/servers/cata/ArkCORE-NG/src/server/game/Chat/Chat.cpp:94:13: note: in passing argument 1 of ‘std::string str_ltrim(std::string&)’
 std::string str_ltrim(std::string &s)
             ^
/home/servers/cata/ArkCORE-NG/src/server/game/Chat/Chat.cpp: In member function ‘std::string ChatHandler::GetKeyFromLink(std::string, std::string)’:
/home/servers/cata/ArkCORE-NG/src/server/game/Chat/Chat.cpp:1045:46: error: invalid initialization of non-const reference of type ‘std::string& {aka std::basic_string<char>&}’ from an rvalue of type ‘std::string {aka std::basic_string<char>}’
             if (str_trim(str_tolower(tok1[0])) == str_trim(str_tolower(linkTypes)))
                                              ^
/home/servers/cata/ArkCORE-NG/src/server/game/Chat/Chat.cpp:110:13: note: in passing argument 1 of ‘std::string str_trim(std::string&)’
 std::string str_trim(std::string &text)
             ^
/home/servers/cata/ArkCORE-NG/src/server/game/Chat/Chat.cpp:1045:82: error: invalid initialization of non-const reference of type ‘std::string& {aka std::basic_string<char>&}’ from an rvalue of type ‘std::string {aka std::basic_string<char>}’
             if (str_trim(str_tolower(tok1[0])) == str_trim(str_tolower(linkTypes)))
                                                                                  ^
/home/servers/cata/ArkCORE-NG/src/server/game/Chat/Chat.cpp:110:13: note: in passing argument 1 of ‘std::string str_trim(std::string&)’
 std::string str_trim(std::string &text)
             ^
src/server/game/CMakeFiles/game.dir/build.make:1457: recipe for target 'src/server/game/CMakeFiles/game.dir/Chat/Chat.cpp.o' failed
make[2]: *** [src/server/game/CMakeFiles/game.dir/Chat/Chat.cpp.o] Error 1
CMakeFiles/Makefile2:675: recipe for target 'src/server/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/server/game/CMakeFiles/game.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by gpn39f** [comment]
i have taken this from a c++ helpsite.. it's source from 2010.. so i think every compiler should do it.. 
but i have no linux.. so, can someone else help us to adapt this source to our linux members

**Comment by Jascharus** [comment]
I had the same errors. After a few hours of searching i found a tip for fix but i don't know if it a fix or a dirty workaround. What I remember from my search is that it have something to do with std an cctype that the compiler don´t know wich one he have to use.

Change on Line 89:
From:
`std::transform(text.begin(), text.end(), text.begin(), std::tolower);`
To:
`std::transform(text.begin(), text.end(), text.begin(), ::tolower);`

And on Line 110:
From:
`std::string str_trim(std::string &text) 
{
    return str_ltrim(str_rtrim(text));
}`
To:
`std::string str_trim(std::string text) 
{
    str_ltrim(text);
    str_rtrim(text);
    return text;
}`

With this Changes you can compile with Debian 8

**Comment by gpn39f** [comment]
mm.. pls check the 2.)  again.. 
the part return str_ltrim(str_rtrim(text))
is 
text=str_rtrim(text);
return  return str_ltrim(text);

in youre version is the function not change nothing.. the changed text from r_trim or l_trim  is not stored back.. the use of & is to tell the compiler to send the string and not the pointer to the function.. it is not used to return the changed text.. (but maybe do it??) gcc is not shure to.. and give us a failure.. 

why is linux give failure on trim, but not on similar written parts str_rtrim, str_ltrim..

to 1.)
pls tell me why linus is giving failure on command ::tolower, and not on command's isspace, not1, ptr_fun

**Comment by Jascharus** [comment]
Oh damn this happend if you copy something from the web without looking closely. 
This take the compiler without any error:
`std::string str_trim(std::string text) 
{
    text = str_ltrim(text);
    text = str_rtrim(text);
    return text;
}`

With this:
`std::string str_trim(std::string &text) 
{
    text = str_ltrim(text);
    text = str_rtrim(text);
    return text;
}`
give this errors:
Chat.cpp: In member function 'std::string ChatHandler::GetKeyFromLink(std::string, std::string)':
Chat.cpp:1048:46: error: invalid initialization of non-const reference of type 'std::string& {aka std::basic_string<char>&}' from an rvalue of type 'std::string {aka std::basic_string<char>}'
             if (str_trim(str_tolower(tok1[0])) == str_trim(str_tolower(linkTypes)))
Chat.cpp:110:13: note: in passing argument 1 of 'std::string str_trim(std::string&)'
 std::string str_trim(std::string &text)

And i understand not enough from c++ to figure out why

To 1.)
This two failure it give´s for std::tolower:
Chat.cpp:89:71: error: no matching function for call to 'transform(std::basic_string<char>::iterator, std::basic_string<char>::iterator, std::basic_string<char>::iterator, <unresolved overloaded function type>)'
    std::transform(text.begin(), text.end(), text.begin(), std::tolower);
and
Chat.cpp:89:71: note:   couldn't deduce template parameter '_UnaryOperation'
    std::transform(text.begin(), text.end(), text.begin(), std::tolower);

**Comment by gpn39f** [comment]
best not to mix & to much..

is linux compiling this? try:


std::string str_tolower(std::string text)
{
   std::transform(text.begin(), text.end(), text.begin(), ::tolower);
   return text;
}

`
// trim from start
std::string str_ltrim(std::string s) 
{
    s.erase(s.begin(), std::find_if(s.begin(), s.end(),
        std::not1(std::ptr_fun<int, int>(std::isspace))));
    return s;
}

// trim from end
std::string str_rtrim(std::string s) 
{
    s.erase(std::find_if(s.rbegin(), s.rend(),
        std::not1(std::ptr_fun<int, int>(std::isspace))).base(), s.end());
    return s;
}

// trim from both ends
std::string str_trim(std::string text) 
{
    text = str_rtrim(text);
    return str_ltrim(text);
}

`

**Comment by Jascharus** [comment]
Yes it do

**Comment by gpn39f** [comment]
if fixed, then please close it..
