### ISSUE TITLE
goblin zone quest

### ISSUE THREAD

**Issue by mygithome002** [Arkania/ArkCORE-NG#236]
second island :Enemies of enemies begin, NPCs can not dialogue

http://www.wowhead.com/quest=14234 "The Enemy of My Enemy"  :Aggra(only gm mode visible) cannot dialogue,quest cannot complete.  i  try updating the  DB creature_template ,still not work

**Comment by gpn39f** [comment]
there is no quest with this title..
please give us allways a link to wowhead or similar..
here a demo https://cata-twinhead.twinstar.cz/?zone=4720#quests

and then please tell us what for dialog you missing..

**Comment by mygithome002** [comment]
update!
