### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by mazdafil** [Arkania/ArkCORE-NG#238]
Server crash on quest 26646 when approaching the cave with a key or the pens of prisoners of war. No error messages. The server crashes both in Windows and in Linux

**Comment by gpn39f** [comment]
1.) mostly start worldserver.exe direct.. if then a crash occur, the console window is closes immediately... better is to create a start.bat and start this start.bat.. in my start.bat i have written:

`
del logs \ \*.*  (without space)

start /min authserver.exe
worldserver.exe

pause
`

if the server crash, the pause command will hold the console open, and you can read the last message from worldserver, that not is written in any log files..

2.) you can use from the snapshoot folder the debugx64 version.. if you have open the core in visual studio and a crash occur, you can switch the error message into visual studio.. then you are directly on the place that has done the crash..

**Comment by mazdafil** [comment]
Could you advise the best settings my.cnf? - I suspect that the reasons for the drops in the mysql. Tables and databases are very large, most likely something to do with this, even just to load the dumps already it is necessary to increase the limits

**Comment by gpn39f** [comment]
in snapshoot folder: 
look at root folder 
there a one text file: called: mysql error - the server is gone away.txt
there i describe this problem: to low buffer.
please try it and report.. :-)

**Comment by mazdafil** [comment]
When the engine starts debugx64 - asks some libraries for example ssl32eay32D.dll. What software products need to install?

**Comment by gpn39f** [comment]
look at our wiki..  http://gpn39f.spdns.de/wiki/index.php/Main_Page
its early beta stage.. but some infos are ready

look at "help and support"
and there "windows"

if youre find wrong data or you have better infos.. pls report.. thanks..

**Comment by mazdafil** [comment]
It is 100 percent related to mysql!!! Updated Ubuntu 14.04 to 16,04, mysql from version 5.5 to version 5.7 m. In the end, now I get it the server crash after you enter the command .account create test test. What OS and version of mysql are you???

**Comment by gpn39f** [comment]
the server has its own mysql inside.. trinity need to install a mysql server.. arkcore not..
only the openssl has to be installed.. and there NOT the newest, as the arkcore manual describes..

if the server crash, you have to send a crash report, as much as you can, so we can see what you are doing.. only to write "it's crash" is no good help..

the server you are using for database (xampp or similar?) have a own mysql, and own log files.. take a look in the log files to see for failure..

**Comment by mazdafil** [comment]
Earlier it was portable mysql 5.6 - it was a server crash. problem solved by installing the full distribution, version 5.5, downloaded from the official mysql site

**Comment by gpn39f** [comment]
fine..:-)

**Comment by mazdafil** [comment]
To be more precise we need a version 5.5.9 https://downloads.mysql.com/archives/community/ - the same as the version libmysql.dll in the folder release. I think this will solve most of the problems with the server crash

**Comment by gpn39f** [comment]
mmhh.. pls recheck you're version..
if i look at the date, the version 5.5.9 is Jan 26, 2011
the next version 5.5.10 is Mar 9, 2011
and the last server in the 5.5 stage is : 5.5.53 from Sep 29, 2016

in the manual for trinity the info is: all versions from 5.5.x are good.. so you're choise is ok, 
maybe the last version has less security problems?? and is more optimized..??

**Comment by mazdafil** [comment]
the problem is not solved - fall again when using spells of a set of marching or when a player is detected or Jorgensen orcs. debug do not work.

**Comment by mazdafil** [comment]
the problem is not solved - fall again when using spells of a set of marching or when a player is detected or Jorgensen orcs. debug do not work.

**Comment by mazdafil** [comment]
Could this be due to the fact as I tested this quest:
1 .levelup 80
2 .quest add 26646
3 .go creature 26548

**Comment by mazdafil** [comment]
![image](https://cloud.githubusercontent.com/assets/23290043/24058837/33eae3c6-0b7f-11e7-884a-21e64f86dff3.png)

**Comment by mazdafil** [comment]
TypeID GetTypeId() const { return m_objectTypeId; }
Object.h - line 274

**Comment by mazdafil** [comment]
Thank you. All work.

**Comment by gpn39f** [comment]
thanks for the info you has given..
quest, npc, location, level, 
and the info: crash at ranged (spell) attack start of player or jorgensen
then it was possible to find it quickly.. thanks to..
