### ISSUE TITLE
All of the chests in the Elvin forest empty

### ISSUE THREAD

**Issue by mazdafil** [Arkania/ArkCORE-NG#239]
All of the chests in the Elvin forest empty

**Comment by mazdafil** [comment]
You can take a dump from gameobject_loot_template TrinityCoreLegasy - the table structure is the same

**Comment by jubel02** [comment]
oh come oooon, srsly?

report something like Mage arcane shot deals lower damage or talent not working, with proof, suggestion etc!

**Comment by mazdafil** [comment]
Proof? Empty result of query SELECT * FROM `gameobject_loot_template` where entry=2843

**Comment by mazdafil** [comment]
Solution
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 117, 9.72, 1, 0, 1, 4);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 118, 4.11, 1, 0, 1, 6);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 159, 1.45, 1, 0, 1, 5);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 414, 2.2, 1, 0, 1, 4);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 765, 7.73, 1, 0, 1, 8);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 774, 11.35, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 783, 5.37, 1, 0, 1, 2);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 785, 5.46, 1, 0, 1, 4);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 818, 5.44, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 858, 3.47, 1, 0, 1, 7);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1179, 4.77, 1, 0, 1, 5);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1210, 8.28, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1429, 8.13, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1495, 8.15, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1497, 8.14, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1498, 8.14, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1499, 8.15, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1501, 8.21, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1502, 8.14, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1504, 8.17, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1506, 8.15, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1509, 8.15, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1510, 8.17, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1511, 8.22, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1512, 8.2, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1513, 8.16, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1514, 6.21, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1515, 6.17, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 1516, 6.19, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 2070, 6.77, 1, 0, 1, 4);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 2214, 6.15, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 2287, 6.21, 1, 0, 1, 4);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 2318, 6.96, 1, 0, 1, 6);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 2447, 6.77, 1, 0, 1, 6);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 2449, 6.78, 1, 0, 1, 5);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 2450, 6.52, 1, 0, 1, 4);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 2455, 6.18, 1, 0, 1, 8);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 2589, 6.94, 1, 0, 1, 6);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 2763, 6.18, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 2770, 6.32, 1, 0, 1, 6);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 2777, 6.17, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 2778, 6.2, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 2835, 6.46, 1, 0, 1, 6);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 2842, 6.44, 1, 0, 1, 4);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 2996, 6.19, 1, 0, 1, 6);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 3374, 6.14, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 3375, 6.14, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 3577, 6.26, 1, 0, 1, 2);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 4536, 6.7, 1, 0, 1, 3);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 4537, 6.11, 1, 0, 1, 4);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 4540, 6.71, 1, 0, 1, 4);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 4541, 6.05, 1, 0, 1, 4);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 4604, 6.73, 1, 0, 1, 4);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 4605, 6.17, 1, 0, 1, 4);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 61959, -19.96, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 61960, -20.02, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 61961, -19.99, 1, 0, 1, 1);
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `Chance`, `lootmode`, `groupid`, `mincount`, `maxcount`) VALUES (2843, 61962, -20.04, 1, 0, 1, 1);

**Comment by gpn39f** [comment]
its very big work to validate all data.. 
aokromes and his trinity 434 is good work, but there are much missing there to.. Russian ytdb  are good to..  
everyone is welcome to write a issue with necessary data to find and repair..
so write me the chest id, you found empty, (if there are quest items involved, report it)

here we have id 2843, (trinity empty, ytdb has data) imported from ytdb.. thanks....
