### ISSUE TITLE
Bug quest 26320

### ISSUE THREAD

**Issue by mazdafil** [Arkania/ArkCORE-NG#241]
Bug quest 26320 - when you use the incense burners nothing is happening

**Comment by mazdafil** [comment]
May be you can use these scripts? https://github.com/cooler-SAI/WoWSource434/blob/master/src/server/scripts/EasternKingdoms/zone_westfall.cpp

**Comment by mazdafil** [comment]
Have a database from version private emucoach - there's this quest works, is implemented smart_scripts. but I can't get him to move. May be you get?

INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42371, 0, 0, 7, 54, 0, 100, 0, 0, 0, 0, 0, 80, 4237100, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Vanessa VanCleef - On Spawn - Run Script');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42693, 0, 0, 6, 27, 0, 100, 0, 0, 0, 0, 0, 80, 4269300, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Vision of the Past - On Passenger Boarded Run Script');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42693, 0, 1, 0, 40, 0, 100, 0, 14, 42693, 0, 0, 80, 4269301, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Vision of the Past - On WP Reached Run Script');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42693, 0, 3, 0, 38, 0, 100, 0, 1, 1, 0, 0, 80, 4269302, 0, 0, 0, 0, 0, 1, 5, 0, 0, 0, 0, 0, 0, 'Vision of the Past - On Data Set 1 1 Run Script');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42693, 0, 4, 10, 38, 0, 100, 0, 3, 3, 0, 0, 53, 1, 42695, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Vision of the Past - On Data Set 3 3 Run Script');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42693, 0, 5, 0, 38, 0, 100, 0, 2, 2, 0, 0, 45, 2, 2, 0, 0, 0, 0, 9, 42699, 0, 45, 0, 0, 0, 0, 'Vision of the Past - On Data Set 2 2 on Alliance Warrior');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42693, 0, 6, 7, 61, 0, 100, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Vision of the Past - On Passenger Boarded Store Target');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42693, 0, 7, 0, 61, 0, 100, 0, 0, 0, 0, 0, 75, 59073, 4, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 'Vision of the Past - On Data Set Cast Aura');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42693, 0, 8, 9, 40, 0, 100, 0, 2, 42695, 0, 0, 28, 59073, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 'Vision of the Past - On WP reached Remove Aura');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42693, 0, 9, 0, 61, 0, 100, 0, 0, 0, 0, 0, 51, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Vision of the Past - On WP Reached Kill Vision');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42693, 0, 10, 0, 61, 0, 100, 0, 0, 0, 0, 0, 15, 26320, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 'Vision of the Past - On Data Set Give Credit');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42697, 0, 0, 0, 4, 0, 100, 3, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Edwin VanCleef - On Aggro - Say Line 0 (No Repeat) (Normal Dungeon)');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42697, 0, 1, 0, 0, 0, 100, 3, 0, 0, 0, 0, 11, 674, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Edwin VanCleef - In Combat - Cast \'Dual Wield\' (No Repeat) (Normal Dungeon)');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42697, 0, 2, 0, 0, 0, 100, 2, 2200, 14200, 8000, 17500, 11, 3391, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Edwin VanCleef - In Combat - Cast \'Thrash\' (No Repeat) (Normal Dungeon)');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42697, 0, 3, 0, 2, 0, 100, 3, 34, 66, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Edwin VanCleef - Between 34-66% Health - Say Line 1 (No Repeat) (Normal Dungeon)');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42697, 0, 4, 5, 2, 0, 100, 3, 26, 50, 0, 0, 11, 5200, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Edwin VanCleef - Between 26-50% Health - Cast \'VanCleef\'s Allies\' (No Repeat) (Normal Dungeon)');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42697, 0, 5, 0, 61, 0, 100, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Edwin VanCleef - Between 26-50% Health - Say Line 2 (No Repeat) (Normal Dungeon)');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42697, 0, 6, 0, 2, 0, 100, 3, 0, 33, 0, 0, 1, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Edwin VanCleef - Between 0-33% Health - Say Line 3 (No Repeat) (Normal Dungeon)');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42697, 0, 7, 8, 2, 0, 100, 3, 0, 25, 0, 0, 11, 5200, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Edwin VanCleef - Between 0-25% Health - Cast \'VanCleef\'s Allies\' (No Repeat) (Normal Dungeon)');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42697, 0, 8, 0, 61, 0, 100, 0, 0, 25, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Edwin VanCleef - Between 0-25% Health - Say Line 2 (No Repeat) (Normal Dungeon)');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42697, 0, 9, 0, 5, 0, 100, 2, 0, 0, 0, 0, 1, 4, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Edwin VanCleef - On Killed Unit - Say Line 4 (No Repeat) (Normal Dungeon)');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42697, 0, 10, 11, 6, 0, 100, 3, 0, 0, 0, 0, 1, 5, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Edwin VanCleef - On Just Died - Say Line 5 (No Repeat) (Normal Dungeon)');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42697, 0, 11, 0, 61, 0, 100, 3, 0, 0, 0, 0, 45, 1, 1, 0, 0, 0, 0, 9, 0, 0, 30, 0, 0, 0, 0, 'Edwin VanCleef - On Just Died - Set Data 1 1 (No Repeat) (Normal Dungeon)');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42699, 0, 0, 0, 4, 0, 100, 0, 0, 0, 0, 0, 11, 29060, 4, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 'Alliance Warrior - On Aggro Cast Taunt');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42699, 0, 1, 0, 0, 0, 100, 0, 2000, 2500, 4000, 4500, 11, 8078, 4, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 'Alliance Warrior - In Combat Cast Thunder Clap');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42699, 0, 2, 0, 0, 0, 100, 0, 2600, 2700, 4300, 4800, 11, 52221, 4, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 'Alliance Warrior - In Combat Cast Heroic Strike');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42699, 0, 3, 0, 38, 0, 100, 0, 1, 1, 0, 0, 80, 4269900, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Alliance Warrior - On Data set 1 1 Run Script');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (42699, 0, 4, 0, 52, 0, 100, 0, 3, 42699, 0, 0, 80, 4269901, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Alliance Warrior - On Data set 2 2 Run Script');

INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES (42693, 1, -101.765, -682.842, 43.6606, 'Vision of the Past WP 500 WP');
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES (42693, 2, -96.5786, -708.184, 39.2356, 'Vision of the Past WP 500 WP');
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES (42693, 3, -62.0791, -740.28, 36.4636, 'Vision of the Past WP 500 WP');
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES (42693, 4, -25.3967, -777.835, 33.479, 'Vision of the Past WP 500 WP');
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES (42693, 5, -3.32256, -807.12, 47.0686, 'Vision of the Past WP 500 WP');
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES (42693, 6, 5.08428, -825.908, 49.1787, 'Vision of the Past WP 500 WP');
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES (42693, 7, 2.97406, -835.41, 51.0165, 'Vision of the Past WP 500 WP');
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES (42693, 8, -4.52647, -844.855, 53.802, 'Vision of the Past WP 500 WP');
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES (42693, 9, -15.1821, -852.846, 56.3048, 'Vision of the Past WP 500 WP');
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES (42693, 10, -26.8472, -849.896, 54.4065, 'Vision of the Past WP 500 WP');
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES (42693, 11, -40.6878, -841.146, 50.7121, 'Vision of the Past WP 500 WP');
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES (42693, 12, -40.6878, -841.146, 50.7121, 'Vision of the Past WP 500 WP');
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES (42693, 13, -54.3356, -832.67, 47.1746, 'Vision of the Past WP 500 WP');
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES (42693, 14, -64.9755, -825.241, 46.2088, 'Vision of the Past WP 500 WP');

**Comment by gpn39f** [comment]
the problem is in the spell: if you click the item, the spell cast 79586 trigger 79587.. this should spawn vehicle 42693 and mount the player on seat 0.. 
the vehicle is spawned (not visible), and the player is called the VehicleJoinEvent for seat 0.. 
but then a InstallAccessory fails while player is not allowed as accessory.. the VehicleJoinEvent is deleted again.. before the vehicle::execute is called..
but why is the InstallAccessory  called??..it should not... 
there is no defined accessory in db, no npc_spellclick.. so why??

**Comment by mazdafil** [comment]
NSERT INTO npc_spellclick_spells  (npc_entry, spell_id, cast_flags, user_type) VALUES (42693, 86106, 2,0)

**Comment by mazdafil** [comment]
The console shows an error - Spell 90102 specified in npc_spellclick_spells is not a valid vehicle enter aura! What is a spell 90102?

**Comment by gpn39f** [comment]
this 90102 is from vehicle 47297: Lumbering Olaf.. (and passenger Helix 47296)
in our db we have 3 entries in npc_spellcleck_spells.. 
only (47297, 46598, 1, 0) is correct.. update comes in next push..

**Comment by mazdafil** [comment]
There may be a problem somewhere in the Vehicle.cpp/Vehicle.h?

**Comment by mazdafil** [comment]
and table vehicle_accessory_template 42693 should be?

**Comment by gpn39f** [comment]
i'm on debugging the structure..  what i see: 
on SpellEffect0: the vehicle::AddPassenger is called.. the VehicleJoinEvent is created
on SpellEffect1: the phase is changed, SetInPhase is called.. from there RemoveNotOwnSingleTargetAuras.. from there the VehicleJoinEvent is deleted..
now i have to look deeper in this phase handling.. maybe vehicle and passengers are short time in different phases.. then the passenger exit make sense..
note:
player spawn vehicle and has aura vehicle control.. there are no other passenger in this invisible vehicle.. so all data for accessory has to be empty..

**Comment by gpn39f** [comment]
yes.. the failure is in function Unit::SetInPhase.. there is the call of RemoveNotOwnSingleTargetAuras(0) 
this parameter is phaseId=0.. and this is wrong.. 
inside the function is the changed phase 231 compared with this parameter id=0.. therefor vehicle and passenger are in different phase.. aura is removed.. 
note:
trinity has same failure..
note: 
now we have to set all spawned npc's used in this vision to the new phaseId 231..

**Comment by mazdafil** [comment]
Quest works, but for some reason Edwin and Defias Blackguard appear in the stateroom, not on deck - and Vanessa and the Alliance do not appear at all.

**Comment by gpn39f** [comment]
look at the note:
now we have to set all spawned npc's used in this vision to the new phaseId 231..

this is work for one week.. the hole ship must be respawned for two different phases.. this is not done today..

**Comment by LKArthas** [comment]
it's true fixing that one was challenging but not impossible and the current bug that still have is when you end the quest and be phased out you can't exit the deadmines until logout, I was the one who fix that quest a long time ago and OFC won't work you have the script and the WP's but there's a lot of data there missing of the original query  :)

**Comment by mazdafil** [comment]
Great, all right.
