### ISSUE TITLE
Blackwing Descent - Nefarian boss

### ISSUE THREAD

**Issue by brian8544** [Arkania/ArkCORE-NG#242]
Nefarian boss crashes server + Nefarian doesn't have any text

>>

https://i.gyazo.com/4f934032840ff077f6703b2263836889.png

**Comment by brian8544** [comment]
https://i.gyazo.com/e671afad4e075d069bd4b4834143667f.jpg 

Text works + no crash. Although boss doesn't really work, neither does the platform

@gpn39f

**Comment by Artamedes** [comment]
@brian8544 because i's not coded correctly.. at all for that matter https://gist.github.com/Artamedes/3ceae50ce0249381f15ae129700652d5 this one is most correct one although not 100%
sorry for bump, maybe this can be usefull

**Comment by gpn39f** [comment]
thanks @Artamedes for the script part.. but a short look in our core: i see that our script is really old.. text are includet in script.. so mostly all text is missing in db.. and what is with all the spell script and dependencies with part in db.. all this will not work if i only copy/past youre script in our core without the sql db part..

**Comment by Artamedes** [comment]
It can be used for reference for how the encounter uses transports

**Comment by gpn39f** [comment]
yes.. i have stored it for future use.. i can see the writer of the script has used a sniff as source.. if you own sniffs (i need all i can get), please send me PM..
