### ISSUE TITLE
world SQL database is not included in source, but characters and auth are

### ISSUE THREAD

**Issue by knuxyl** [Arkania/ArkCORE-NG#247]
The world database is not included in the source with the other databases and updates and the only file close to this is a seemingly very too much database in https://drive.google.com/drive/folders/0B8q0yc6MkL0nM0NFdUc1WlY5QW8
which might not even be the right one

**Comment by shinebayar-g** [comment]
follow my fork

**Comment by gpn39f** [comment]
the snapshoot root folder is
https://drive.google.com/drive/folders/0B8q0yc6MkL0naTdpN2xiT2s1bTg
there you find all data i have collected over years from arkania core..
