### ISSUE TITLE
What is Fixed On Core ?

### ISSUE THREAD

**Issue by Nephelion** [Arkania/ArkCORE-NG#258]
i want know what is fixed on Source [core] ?
i check worgen that good fix .. 
some Quest on map Goof fix..
But
-End time Bug
-HOT Bug
-WOE Bug
and more dungeon have very bug issue

what is fix on source ? 
if source have good work on can help some SQL fix - smart and others for source
i need a good source to i work on it and run a game sv !

**Comment by gpn39f** [comment]
last 2 years i have fixed several core bug.. 
i have no idee how the bug's are named by other devs..
what i'm doing?? i sql fix a zone.. and if i find a core failure:  then i try to fix it to..
and sometime i'm lucky..
on redrige, gilneas and westfall i have seen now, i have to redo some scripts.. 
now with less core failure, some script has to been rewritten..
but you see.. i'm nearly alone.. 
so all help are welcome..

**Comment by Nephelion** [comment]
thats good for your SQL fix i check and have very good fixes
but source is not just SQL fix. need more COre fix - c++ 
for players dungeon and game play is important from quest gilnes

when u start fixing import dungeon like  end - hot - woe

**Comment by gpn39f** [comment]
i have no roadmap..
if you have good idees, come on our forum and tell us about..
so i can see what we need to implement this changes..
And to determine that my abilities are sufficient
