### ISSUE TITLE
The Wakening - crash client

### ISSUE THREAD

**Issue by cooler-SAI** [Arkania/ArkCORE-NG#26]
This quest crash client. When you use firsttime gossip menu, all good, the second time - we have a crash!
Core: https://github.com/Arkania/ArkCORE-NG/commit/2547423aa4aad909cf4f0e8af7f9b2a195ab48ff
Quest : http://www.wowhead.com/quest=24960/the-wakening

**Comment by gpn39f** [comment]
from looking about function, there is no part, where code may be unsafe..
what I think is bad: you can call the gossip without having the quest taken..
so I changed this visual part. 
if you talk with npc, the npc anwere first time with gossip and second time with spell window.. and then running away and despawn.. after some minutes respawn on homeposition.. are you now talking with npc as second talk?? or are you doing something special??

**Comment by cooler-SAI** [comment]
npc second talk

**Comment by gpn39f** [comment]
no further crash found here..
