### ISSUE TITLE
Actual world base

### ISSUE THREAD

**Issue by Undead02** [Arkania/ArkCORE-NG#270]
Where can I find the actual(current) world database, i can`t found in source

**Comment by yoandris-pr** [comment]
https://drive.google.com/drive/folders/0B8q0yc6MkL0nbEEtbGJETVBSOVE

**Comment by Undead02** [comment]
This error Error Code: 2006 - MySQL server has gone away 
when I try execute db

**Comment by gpn39f** [comment]
in folder are some textfile on different place: called: my server has gone away
please read it..

**Comment by Undead02** [comment]
Now another error, Error Code: 1067 - Invalid default value for 'start_time' 
Download 2017/Snapshot current

**Comment by Undead02** [comment]
Loading Transports...
[1054] Unknown column 'phaseId' in 'field list'
Your database structure is not up to date. Please make sure you've executed all
queries in the sql/updates folders.
Perphaps i forgot an update

**Comment by gpn39f** [comment]
you are using a new mysql server > 5.5.. 
in wiki for all core <= 548 you can read, you have to use 5.5.x for server and install ..

use snapshoot from 2017/05, its newer as the current snapshoot form /04

**Comment by yoandris-pr** [comment]
i need some of you skype users?

**Comment by gpn39f** [comment]
we have a shortbox in our forum..
http://gpn39f.spdns.de/forum/
