### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by ghost** [Arkania/ArkCORE-NG#271]
when i run sql>base>auth.sql in heidisql program i get an error :
SQL Error (1293): Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

![kepkivagas](https://user-images.githubusercontent.com/29596828/27377011-0c3d350a-5674-11e7-9002-915c18bf7146.JPG)

How can i solve this ??

**Comment by gpn39f** [comment]
its saved with navicat.. 
i will look at this..

**Comment by ghost** [comment]
thank you :)

**Comment by gpn39f** [comment]
no errors here using current heidi version in windows 10..
i go into heidiSql, create new database coose: name: ng_auth.. Collation: utf8_unicode_ci 
then i choose load sql file from icon-menu
and click on RUN button..
its end with report window: 45 warnings..
but none errors.. all data are present..
 
note: it's importend to have the correct Collation.. 

note: use snapshoot from 2017, Jun 1 !!!! older can have failure..

**Comment by gpn39f** [comment]
pls report what you have done :-).. thanks..
