### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by neltharionorg** [Arkania/ArkCORE-NG#273]
Hello, i want to try your core but i cant find database and also im getting 403 error on http://gpn39f.spdns.de/forum2/

**Comment by gpn39f** [comment]
sorry .. is forum1.. only our wiki is now wiki2

**Comment by neltharionorg** [comment]
i can connect to wiki2 but it asks me to login cant find registration page

**Comment by gpn39f** [comment]
the security against spam was to high.. 
i forgot to whitelist login site :-)
now should be good

**Comment by neltharionorg** [comment]
yea i registred now but i cant find database download links

**Comment by gpn39f** [comment]
wiki first site.. look at bottom.. there are all links..
you need the link to my google snapshot folder..
i made a fresh folder some minutes ago..
