### ISSUE TITLE
Exe

### ISSUE THREAD

**Issue by ghost** [Arkania/ArkCORE-NG#274]
Hello

I built this source on windows 10 with visual studio 2017 without ace 
and everything went fine without any error.

After this operation
I run the authserver.exe and then worldserver.exe
and i got this error: 

![kepkivagas](https://user-images.githubusercontent.com/29596828/32959006-7a848ec0-cbc0-11e7-8d76-8d4d562f2782.JPG)

can you help me to solve this ?

**Comment by gpn39f** [comment]
mmhh.. 
windows 10,  last update, it has a new defender part.. 
some tools, that store data in a own path, are now denied..
mostly of this tools was stored in c:\progam or windows\desktop..
both are not allowed anymore

you have to store such tools on other path.. as c:\arkania  or e:\wow
on this path the new defender has no restrictions..

**Comment by ghost** [comment]
okay i will try to move that folder to other place

**Comment by ReinerrHUN** [comment]
same error

**Comment by ghost** [comment]
okay i found the problem, all working fine

**Comment by gpn39f** [comment]
tell

**Comment by ghost** [comment]
virus defender block these files and cant running :)

**Comment by gpn39f** [comment]
what virus defender? Name?? Part??
where are the server files stored?

**Comment by ghost** [comment]
avast because of wrong settings

**Comment by gpn39f** [comment]
ok.. thanks..

**Comment by ghost** [comment]
the files place didnt cause promlems

**Comment by ghost** [comment]
can you upload a full database to the latest version ?

**Comment by gpn39f** [comment]
is on snapshoot..

https://drive.google.com/drive/folders/0B8q0yc6MkL0naTdpN2xiT2s1bTg

forum 
http://gpn39f.spdns.de/forum1/

**Comment by ghost** [comment]
thank you
