### ISSUE TITLE
arkcoredb world

### ISSUE THREAD

**Issue by CrossUCI** [Arkania/ArkCORE-NG#275]
Hi guys, sorry for my bad english , i know that in the last issues about the world database is closed, but i read the post , and i go to the link of google drive, there, i download ArkDB_r7.8.0_CATA_4.3.4_19-10-2014, because in the folder of Arkcore-NG, the databases are empty, but y download too, i install the database and the world is 420 Mb, but there are some table that not exists, for example archaeology_digsites_template, archaeology_positions_template, guild_challenges, guild_challenges_rewards , and i fix it copy the query of the empty database,  but there are other problems in creature_template dont exists the column mindmg, maxdmg, attackpower, and i asking if some one dont have the full world database in a link that i can download for example in mega with a free account you have 50gb of storage, greettings, i expects some answers

**Comment by gpn39f** [comment]
if you look at the main site, we have there a link to our forum and the storage.. look at the bottom..
on the moment i'm working on a table editor, nobody else is helping, so the database ng is not changed since october 17..
