### ISSUE TITLE
Quest in The Barrens

### ISSUE THREAD

**Issue by meguk123** [Arkania/ArkCORE-NG#28]
Hi, more quest in The Barrens not work, who have some fixes for this?
Thanks

**Comment by gpn39f** [comment]
pls send a wiki link like
https://cata-twinhead.twinstar.cz/?search=The+Barrens#quests
and report WHAT is not working..

**Comment by meguk123** [comment]
http://ru.wowhead.com/quest=13613
http://ru.wowhead.com/quest=13612
http://ru.wowhead.com/quest=13621
and etc, all quest in this chain

**Comment by gpn39f** [comment]
the area looks very bad.. 
so I start with clean up.. 
setup correct phase, aura and npc's..
so I'm started, but it will take a while until finish this work..

**Comment by graham79** [comment]
All quests fixed.
