### ISSUE TITLE
DBError.log

### ISSUE THREAD

**Issue by GMKyle** [Arkania/ArkCORE-NG#291]
There are a lots or errors in DBErrors.log related with gameobject_loot_template, I started to work in some of them but i found gameobjects like Stolen Cargo (http://wowhead.com/object=142181/) and others that i suspect are deprecated or don't exists in KATA. I don't know what to do next, i want to help but now i needed to xD. Sorry for my english and best regards .

**Comment by gpn39f** [comment]
if you look at our snapshot folder, you find the latest  compiled core and database from 2017.. 
there should be only two error left on booting ..

**Comment by GMKyle** [comment]
OK I will update my db sorry and thx for the quickly response, do you had a ToDo list? If that so, can you share it? I have time xD. Like i said i want to help.

**Comment by gpn39f** [comment]
No there is no ToDo list.. i look at the issues and take/choose a zone and starting playing this zone from first quest.. many places there are double spawn, npc have to much or to less attack power, its missing creature text, gossip,, questgiver and ender are not allway's correct.. so i start to prepare a new zone this ways.. if you see a quest is broken, you can write a issue, obtain all data from wowhead and other wiki.. so later if i'm finish my editor,  we can easy finish all this quest with the prepared data.... collect all this data, is taking many hour.. its cost more time to get all this parameter, as write the fix itself..
