### ISSUE TITLE
DB errors

### ISSUE THREAD

**Issue by CrossUCI** [Arkania/ArkCORE-NG#292]
Hey frank you have a chance to publish  your database, in the lastest core in the console appear a lot of errors, and i wan to know if that is ts just me

[DBErrors.log](https://github.com/Arkania/ArkCORE-NG/files/2065534/DBErrors.log)

**Comment by gpn39f** [comment]
mmhh i have not worked on gameobject loot.. 
take a look into the latest commit.. are there changes to the db??

**Comment by CrossUCI** [comment]
I just say  i have the core of january, i use database snaptshot of september and the updates from the core and give me those error in the console.

**Comment by graham79** [comment]
It seems this stems from the update
 https://github.com/Arkania/ArkCORE-NG/commit/4977b86b949d515c20db9a71cf4badac9bb95467
Installed many new gameobjects,  The update sql did contain an update gameobject_loot_template and have invalid data that need correct.

**Comment by graham79** [comment]
Also my db  ArkDB 7.9.26 - 2017-SEP-01 for ArkCORE4 NG 

Has much Pandorian data, also much DEPRECIATED: data probably import from other patch at some point? say Trinity 3.5.3 and some 5.x.xx DB. It is no major problem provided you can tailor your DB to suite your needs/config.

**Comment by CrossUCI** [comment]
Closed
