### ISSUE TITLE
Secondary Skills.

### ISSUE THREAD

**Issue by graham79** [Arkania/ArkCORE-NG#295]
On my server the skills like cooking,fishing and first aid do not save to DB. start with 1/75 and practise raise level too 40/75...if player log out and later log in all seconday skills are back to 1/75?

Payers keep the spells learnt but not skill progress.

**Comment by ReyDonovan** [comment]
fix https://github.com/Arkania/ArkCORE-NG/pull/298/commits/93c25cb24dfa94d067923461accb32a29abfdf37

**Comment by gpn39f** [comment]
may i ask: what does OpenSSL have to do with the fact that the secondary skills are not stored in the database ???

**Comment by ReyDonovan** [comment]
what?

**Comment by gpn39f** [comment]
the question is: the skills like cooking,fishing and first aid do not save to DB. 
and youre answer is : replace the OpenSSL
and i ask you: what has the OpenSSL to do with the sec skill..

**Comment by ReyDonovan** [comment]
https://github.com/ReyDonovan/ArkCORE-NG/commit/93c25cb24dfa94d067923461accb32a29abfdf37

**Comment by ReyDonovan** [comment]
this commit is included in the OpenSSL pull

**Comment by graham79** [comment]
Update: I experient with character, If I give him materials to raise skill to 75/75 and gain next rank, Journeyman 1/150  then he can log out and skill rank and progress is saved to the DB. It seems only the first rank, apprentice 1/75 is affected by this bug.

**Comment by graham79** [comment]
Update#2  I found out that fishing skill is affected most. The reason is your fishing skill 356 is not added to the DB when you first learn fishing rank 0 apprentice. If you check character_skills table, cooking, first aid skills appear here with rank and skill level, but after learn fishing is not present in the skills list, I suspect wrong spells used by trainer. I very much doubt it is the code, that has not been changed. I you add the skill to your characters skills list manually, your progress is then saved on logout.

**Comment by graham79** [comment]
Update#2  I found out that fishing skill is affected most. The reason is your fishing skill 356 is not added to the DB when you first learn fishing rank 0 apprentice. If you check character_skills table, cooking, first aid skills appear here with rank and skill level, but after learn fishing is not present in the skills list, I suspect wrong spells used by trainer. I very much doubt it is the code, that has not been changed. I you add the skill to your characters skills list manually, your progress is then saved on logout.

**Comment by graham79** [comment]
Udate: the problem still persist despite commit by Ray.
b9c463ad385fcfbabd5451b521a75bc671a3f1aa

after more test, found that ALL Professions are affected.

**Comment by graham79** [comment]
Update: problem seems to be fixed now.
