### ISSUE TITLE
[BUG] Eye for an Eye

### ISSUE THREAD

**Issue by CrossUCI** [Arkania/ArkCORE-NG#305]
Class: Paladin
Spec: Retribution
What should do : All magic attacks against you have a [20%/40%] chance to cause 30% of the damage taken back to the attacker as well.
What does : Nothing

**Comment by graham79** [comment]
To make things clearer.
There are 3 eye for an eye spells in our DBC files.
ID - 9799 Eye for an Eye (Rank 1)
Rank 1 20% chance to proc, gives 30% of damage taken back to enemy.
ID - 25988 Eye for an Eye (Rank 2)
Rank 2 40% chance to proc, gives 30% of damage taken back to enemy.
and this one maybe connected to paladin or not.
ID - 25997 Eye for an Eye
Description: All magical attacks against you have a chance to cause a percentage of the damage back to the attacker as well.
But this spell only target enemy 
Effect 0: Id 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
BasePoints = 1
Targets (6, 0) (TARGET_UNIT_TARGET_ENEMY, NO_TARGET)

hope this helps.

**Comment by gpn39f** [comment]
if i look on the script, it's only a call on the ranked 1 spell -9799
what does this spell?? call the base spell 25988 with given damage.. 
if the base spell is not working, all spells are not working 
so maybe we have to add the spell 25988 and give the random damage value to target????
