### ISSUE TITLE
[BUG] Inquisition

### ISSUE THREAD

**Issue by CrossUCI** [Arkania/ArkCORE-NG#309]
Class: Paladin
Spec: Retribution
What should do : Consumes all Holy Power to increase your Holy Damage by 30%. Lasts 4 sec per charge of Holy Power consumed.
What does : Only lasts 4 sec even with 2 or 3 charge.
1 charge of holy power : must lasts 4 * 1 sec , last 4 sec
2 charge of holy power : must lasts 4 * 2 sec , last 4 sec
3 charge of holy power : must lasts 4 * 3 sec , last 4 sec

**Comment by CrossUCI** [comment]
Maybe this can help you

class spell_pal_inquisition : public SpellScript
{
    PrepareSpellScript(spell_pal_inquisition);

    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return ValidateSpellInfo({ SPELL_PALADIN_DIVINE_PURPOSE_PROC });
    }

    void ChangeDuration()
    {
        Unit* caster = GetCaster();
        if (!caster)
            return;

        if (Aura* aura = caster->GetAura(GetSpellInfo()->Id))
        {
            uint8 power = caster->HasAura(SPELL_PALADIN_DIVINE_PURPOSE_PROC) ? 2 : caster->GetPower(POWER_HOLY_POWER);
            int32 duration = aura->GetDuration();
            duration += duration * power;
            aura->SetDuration(duration);
        }

    }

    void Register() override
    {
        AfterHit += SpellHitFn(spell_pal_inquisition::ChangeDuration);
    }
};

**Comment by gpn39f** [comment]
are this correct link's to wiki???

https://cata-twinhead.twinstar.cz/?spell=84963
https://wow.gamepedia.com/Paladin_builds   https://wow.gamepedia.com/Inquisition_(paladin_ability)
https://www.wowdb.com/spells/84963-inquisition

**Comment by CrossUCI** [comment]
The link to wowpedia and the wowdb are for Battle for Azeroth expansion not for Cataclysm , but twinhead is correct.

**Comment by CrossUCI** [comment]
The Inquisition now works with the charge of the sacred power, but instead than 4 seconds it lasts 6, it is necessary to return to work in the duration

**Comment by gpn39f** [comment]
if i look at the script then we have 2 lines.. the duration has allways a value of 4000ms.. 
the power is 2 when the player has the aura SPELL_PALADIN_DIVINE_PURPOSE_PROC (so the duration is 8000 ms)
if not, the power has the power-value from POWER_HOLY_POWER  
you know what range this player->GetPower(POWER_HOLY_POWER)  can have ?????? (0..1..2..3..) or (1..2..3..) ?? both are integer values so the result are one of  (0.. 4.. 8..12..) sec

**Comment by CrossUCI** [comment]
SPELL_PALADIN_DIVINE_PURPOSE_PROC when the player has the aura must be as if 3 holy power, in fact i believe that this talent need a spell script.

The following attacks have a % chance to cause your next Holy Power ability to consume no Holy Power and to cast as if 3 Holy Power were consumed:

- Judgement
- Exorcism
- Templar's Verdict
- Divine Storm
- Inquisition
- Holy Wrath
- Hammer of Wrath

**Comment by gpn39f** [comment]
again.. in what step returns the holy power ??
have we a 0 and this are 0 power
or are the lowest power 1 ??? so we have never a 0 value here...

if the holy power has 3 steps.. then the return value can be (0..1..2) or (1..2..3)
and this are not equal..

then we can have 4 steps.. where 0 is 0.. and 1 is first stack.. 2=2 and 3=3 stack...

i know my english is very bad.. but it is imported that we speek from same values..

**Comment by CrossUCI** [comment]
When you cast Cruzader Strike this spell generate one holy power in the retribution specialization, for example if the player do not cast ever Cruzader Strike , Inquisition is not available because require at less one charge of holy power.

**Comment by gpn39f** [comment]
ok. the spell generate one hole power..
if i then  call the function GetPower(POWER_HOLY_POWER) what is the function returns??
a 0 for indicate that we have 1 power
or 1 for indicate that we have 1 power

look at the text on console.. there you see the answer, if you test the spell..
