### ISSUE TITLE
[BUG] Templar Verdict

### ISSUE THREAD

**Issue by CrossUCI** [Arkania/ArkCORE-NG#310]
Class : Paladin
Spec : Retribuition
What should do : An instant weapon attack that causes a percentage of weapon damage. Consumes all charges of Holy Power to increase damage dealt:
1 Holy Power: 30% Weapon Damage
2 Holy Power: 90% Weapon Damage
3 Holy Power: 225% Weapon Damage
What does : with one holy power do damage as two holy power, with two holy power do damage as three holy power and with three holy power do damage as one holy power.

**Comment by gpn39f** [comment]
spell 85256  Templar's Verdict is now part of paladin script..
is the fix ok??

**Comment by CrossUCI** [comment]
i have to look it, last time work with errors as i said with one charge work as two , with two charge as three and three charge as one charge

**Comment by gpn39f** [comment]
so we have again same question.. returns the function GetPower(POWER_HOLY_POWER)) a range starting with 0 or 1..

now the script is using start-range as 0.. in you're description is the startrange 1.. 
so i upload now the script as you say.. let us look what we can fix :-)

**Comment by CrossUCI** [comment]
Start in range 0 because if you dont cast an spell that generate holy power you never have the range 1

**Comment by gpn39f** [comment]
if i start in 0 then you have no change at before.. i have included a text for each loop.. you can see on console or server.log what power value and what damage value the function is set..

**Comment by CrossUCI** [comment]
Fixed now works fine console show
The Paladin SetHitDamage Power : 1 Damage 50
The Paladin SetHitDamage Power : 2 Damage 150
The Paladin SetHitDamage Power : 3 Damage 375
:)

**Comment by gpn39f** [comment]
super.. now please look into spell  "spell_pal_shield_of_the_righteous"
here you find the wrong info that GetPower returns 0.1.2
so i bet this computed value is wrong to
 
1.) as base is used : 400% from player->GetTotalAttackPowerValue(BASE_ATTACK)
on other core i found : int32 damage = GetHitDamage();
so maybe the damage base is to much???? to hight??? or allways same maximum value????
and the GetHitDamage is the better base????

2.) the wrong multiplicator from power

**Comment by CrossUCI** [comment]
I will look right now , you can use this addon Dr Damage this addons is very helpfull , in the spell it show what is the damage that has to be and i you put the mouse over the spell it said avg crit, etc

**Comment by CrossUCI** [comment]
This is what i see, and i believe that is very wrong 
1 Holy Power :  715 damage , how much is doing 12720,  0_0
2 Holy Power :  2145 damage, how much is doing 25440, 0_0
3 Holy Power :  4290 damage, how much is doing 42400, 0_0

and this is withouth the talent Sacret Duty : Your Judgement and Avenger´s of Shield have 50 % chance of making your next Shield of Rightheous a critical strike. Lasts 10sec

1 Holy Power : 30528 damage
2 Holy Power : 61056 damage
3 Holy Power : 101760 damage

Imposible , 0_0

**Comment by gpn39f** [comment]
ok.. i have reworked some of the spell.. and set a output into console/server.log for each.. 
best to close this issue and start new one if neccessary

**Comment by CrossUCI** [comment]
Nice work frank, fixed Shield of the Rigtheous damage, inquisition duration  and templar verdict damage, i believe that we can close both issue
