### ISSUE TITLE
Quest 13949 'Crossroads Caravan Pickup' not scripted

### ISSUE THREAD

**Issue by gpn39f** [Arkania/ArkCORE-NG#32]
here the data i found

quest : https://cata-twinhead.twinstar.cz/?quest=13949
giver: https://cata-twinhead.twinstar.cz/?npc=34258
ender: https://cata-twinhead.twinstar.cz/?npc=5907

kodo front:  https://cata-twinhead.twinstar.cz/?npc=34430
kodo mount: https://cata-twinhead.twinstar.cz/?npc=34432

provided item: https://cata-twinhead.twinstar.cz/?item=46714

spells not shure:
ID - 50630 Eject All Passengers
ID - 61286 World Generic Dismount/Cancel Shapeshift
ID - 65466 Ride Caravan Kodo
ID - 65485 Mount Caravan Kodo Cue (Part 01)
ID - 65486 Summon Kodo Part 1
ID - 65487 Mount Up
ID - 65493 Giddyap
ID - 65494 Call a Pack Kodo
ID - 65557 Dismount Caravan Kodo Cue (Part 01)
ID - 65561 Quest Complete

SMSG_PLAY_MUSIC   ID:  24675

SMSG_PET_SPELLS_MESSAGE
Spell: 65479 (Shoot)
[0] unk20: 61286
[1] unk20: 65487
[2] unk20: 65493
Guid: Type: Vehicle Entry: 34438 (Riding Shotgun) 

more???

**Comment by gpn39f** [comment]
i have assembled mostly of the quest..
the Player is sitting backward on kodo but have empty Hands.. how can i add a weapon to player.. move it from bag to equipment_slot_ranged ?? but how??

**Comment by MeliodasLIVE** [comment]
did you check if there is a visual spell effect for it?

**Comment by gpn39f** [comment]
the Aura 65466  give the weopon..

**Comment by MeliodasLIVE** [comment]
so you found it right ?

**Comment by gpn39f** [comment]
yes.. now i fight with the core.. i spawn 34487
http://www.wowhead.com/npc=34487/razormane-raider
and i let the npc following the pack kodo for 6 secounds and then, if a vehicle place is free, the raider enter the kodo..
all is visuall fine, but i can't let the npc running.. so i'm using the command  "me->SetSpeed(MOVE_WALK, 4.0f);"  but this look's bad.. (walking with high Speed).. 
But how can i set a npc to change his speed from walk to run???

**Comment by MeliodasLIVE** [comment]
DB or Core-side?

**Comment by Lumber-Jack-2** [comment]
me->setwalk(true);
or
me->setwalk(false);

see https://github.com/TrinityCore/TrinityCore/blob/92b08fc74b368e9512c5238d91e381b6df644219/src/server/scripts/Northrend/zone_howling_fjord.cpp#L125
for example

**Comment by gpn39f** [comment]
@MeliodasLIVE  : core script

@Rushor  : i'm stumbled over this function many times and have tried to find the different between trinity and arkcore.. what i can see it: the SetWalk function is only set/remove the movement flag and prepare the opcode in handler.. then the send function is called, here is allway used the walk opcode.. 
today i have written a sniff from arkcore.. and i find nothing about this opcodes, so maybe there is nothing send?? i must investigate more time in this.. help is needed :-)

**Comment by MeliodasLIVE** [comment]
Im sorry that I can't help you my friend, im DB Dev.
Hope you will find, and fix the Issue what u are looking for.

**Comment by gpn39f** [comment]
fixed in last update..
thanks to all helpers..
