### ISSUE TITLE
excellent work

### ISSUE THREAD

**Issue by SangredeHeroes** [Arkania/ArkCORE-NG#33]
excellent work
I'd like you you add crossfaction bg   and duel reset ????

**Comment by gpn39f** [comment]
I'm noop in core programming..
small things are ok.. but big imports are not possible.. maybe later..

**Comment by Lumber-Jack-2** [comment]
look at https://gist.github.com/irancore/10913800 for xfaction :)

**Comment by gpn39f** [comment]
i have tryed to import it.. 
but: some used trinity functions have different behavior and arguments..
so it's not possible to import it directly..
i will try to understand what happens.. what is meaning of cross faction, and where is this allowed..
