### ISSUE TITLE
Project discord

### ISSUE THREAD

**Issue by pangolp** [Arkania/ArkCORE-NG#330]
Good evening. Is there any discord where you talk about the project or is it abandoned?

**Comment by gpn39f** [comment]
i have created a discord server named 'Arkcore NG', but last 2 years there are no traffik there... 
some weeks ago i was receive a message from Arkania github, that i'm being locked out from a old server admin.. so the project is now dead.. maybe i restart it on my own github account somewhere in the future..

**Comment by pangolp** [comment]
If I can compile it in Debian 10, I'll try to collaborate in whatever I can. Thank you for the information.

**Comment by gpn39f** [comment]
there are several linux member that have tryed to compile.. but maybe none was able to do... but none have reported how they did...  you are welcome to help...

**Comment by pangolp** [comment]
In the case of skyfire, it was a problem of incompatibility of libraries. In the case of the core this, not yet tested, but if you have a discord, I can send you the screen screens that come up. My user is Stevej#5879
