### ISSUE TITLE
npc not visible

### ISSUE THREAD

**Issue by ter884** [Arkania/ArkCORE-NG#34]
![default](https://cloud.githubusercontent.com/assets/6825541/11768616/cdd18fa0-a1e3-11e5-89cd-ad95cb0b76b5.PNG)

it can be seen only in GM mode, he's full of life

It must see the players, the target should be dead

**Comment by SangredeHeroes** [comment]
valso I feel the same   deathwing ,murozond

npc are many who can not tagger

**Comment by gpn39f** [comment]
fixed

**Comment by SangredeHeroes** [comment]
gpn39f 
the points of valué that should give the random dungeon also wrong

**Comment by gpn39f** [comment]
pls tell more.. what random dungeon?? what value??
if you not mean this thief on the picture, then please open a new issue...
and give more info.. as a link to wowhead.. 
additional info are welcome..
