### ISSUE TITLE
Training Dummy

### ISSUE THREAD

**Issue by ter884** [Arkania/ArkCORE-NG#35]
bug. Training Dummy, turn toward the player when the player walks around.

**Comment by ter884** [comment]
SetCombatMovement(false);

**Comment by gpn39f** [comment]
fixed..

**Comment by ter884** [comment]
bug. Training Dummy die

**Comment by gpn39f** [comment]
fixed.. :-)

**Comment by ter884** [comment]
the player remains in battle, if you take a very cloves

**Comment by ter884** [comment]
https://bitbucket.org/ter884/arkania_ng-fork/commits/32fa7cf5607463a80ca44945324bd83d27e75244#Lsrc/server/scripts/World/npc_trainings_dummy.cppT187

**Comment by gpn39f** [comment]
there are some trainings quest with 1,2,3,or 5 attacks to finish the quest.. 
so what are you prefer.. remove aggro after each attack or if quest are done?

**Comment by ter884** [comment]
it doesn't hurt jobs
