### ISSUE TITLE
NPC very Powerful

### ISSUE THREAD

**Issue by cooler-SAI** [Arkania/ArkCORE-NG#39]
NPC's in Tirisfal Glades too many powerful! They can kill player with 2-3 hits. I think they have incorrect damage values! ( DB updated to 19.12.2015)

**Comment by gpn39f** [comment]
I have found many many more in more zones.. 
pls give me some ids where you found values wrong..
then can I check.. have I found mostly :-)

**Comment by cooler-SAI** [comment]
http://www.wowhead.com/npc=1934/tirisfal-farmer
http://www.wowhead.com/npc=1935/tirisfal-farmhand
http://www.wowhead.com/npc=1543/vile-fin-puddlejumper
http://www.wowhead.com/npc=1547/decrepit-darkhound

I think there more, this I tested 100%

**Comment by gpn39f** [comment]
on update folder, in zip file from 12/2015 you find a update file, 3.9 MB in size..
all npc's you give above, are changed down to new values..
so please check: have you imported this fix?
more values are now prepared and I upload them after more test.. (but not for you npc's)
if you have imported all, pls send me the values you find in youre database..

**Comment by cooler-SAI** [comment]
used this https://drive.google.com/folderview?id=0B1cfdttdMeqKUTlFYmNFVEVzT1U&usp=sharing&tid=0B1cfdttdMeqKUUhVUEZEYXJGN2s

ng_world_2015_12_10.zip

with all updates and this NPC's (look up) have wrong values in Damage column

P>S> reapplyed 3.9 MB 2015_12_08_01_world.sql, nothing changed

**Comment by gpn39f** [comment]
yes.. I found more..

**Comment by gpn39f** [comment]
I hope, now are mostly found for rank0 and level 2 to 50.. I think: maybe are few left,  that have wrong level or ranking.. so tell me, if somewhere found more: but give me the link for the npc.. all table compare is done, up to level 50.. so without link I can't find it..

**Comment by cooler-SAI** [comment]
ok,deal
