### ISSUE TITLE
SQL update

### ISSUE THREAD

**Issue by ter884** [Arkania/ArkCORE-NG#46]
https://github.com/Arkania/ArkCORE-NG/commit/e9183f4b1abb16238aaade3d7577c996e3c83e9a#diff-c1178343d4dc5137906dc651c89e3d9bR21
where SQL update, or something I missed?

**Comment by gpn39f** [comment]
it's in my working folder. 
I'm not ready with the correct phase behaviour..
until now I have worked with you diff.. first compile are 10 min ago.. installed them manually.. but until now there are no change on client.. so I'm searching deeper now..
the phase.dbc and phasexgroup.dbc is loading correct.. so this part is ok..

**Comment by gpn39f** [comment]
ups.. but now are  terrainswapmap and worldMapAreaSwap not sends values to client.. so i change this part back..
