### ISSUE TITLE
table creature_template_outfits

### ISSUE THREAD

**Issue by ter884** [Arkania/ArkCORE-NG#48]
in the kernel there is no support table creature_template_outfits or remove it or add a patch to the kernel for its implementation

**Comment by gpn39f** [comment]
hmm.. there are none of the databases I have, that have this table.. our table has no valid 434 content.. 
have you data for this table??
if not: then we can delete this table..

**Comment by ter884** [comment]
for this table need this patch http://rochet2.github.io/Dress%20NPCs.html

**Comment by gpn39f** [comment]
ok.. then I try to import it..

**Comment by gpn39f** [comment]
done..
