### ISSUE TITLE
Server breaks after click on "find a new quest" (that fancy hey look here's another quest thing)

### ISSUE THREAD

**Issue by WoweePaw** [Arkania/ArkCORE-NG#5]
The Server stops working after ~1-3 Minutes. worldserver.exe runs and doesn't crash but does no longer react on commands like kick , server shutdown and so on. These messages appear:
- Player::addSpell: Non-existed in SpellStore spell #75461 request.
- Received unhandled opcode [CMSG_GUILD_SET_ACHIEVEMENT_TRACKING 0x1027 (4135)] from...
- SmartScript: Entry 24656 has events but no events added to list because of instance flags.

I've found out that it only stops working if you click on the "find a new quest" stuff...maybe breaks the character?

**Comment by Exodius** [comment]
CMSG_GUILD_SET_ACHIEVEMENT_TRACKING
https://github.com/DDuarte/TrinityCore/commit/7ec22c534e8120f2f877e8d31bc3168faccff5ec

**Comment by gpn39f** [comment]
This behaviour is only using some AddOn tools. I merged DDuartes commit, so now D3thw0lf can check it.
