### ISSUE TITLE
earthmother

### ISSUE THREAD

**Issue by adsprosto** [Arkania/ArkCORE-NG#51]
not working talent earthmother for hill druid 51179 51180 51181

**Comment by gpn39f** [comment]
on wowhead i can't find Talents from earthmother.. so please give us some links like thisone:
http://www.wowhead.com/quest=10670/tear-of-the-earthmother
http://www.wowhead.com/forums&topic=51441/about-the-talent-gift-of-the-earthmother
http://www.wowhead.com/forums&topic=46134/gift-of-the-earthmother
frank

**Comment by adsprosto** [comment]
http://cata.openwow.com/spell=51179 / http://cata.openwow.com/spell=51180 / http://cata.openwow.com/spell=51181

**Comment by ter884** [comment]
https://github.com/cooler-SAI/TER-Server/blob/54e519df0eeac32ee88e2bbc8fba95fc1a92305d/src/server/scripts/Spells/spell_druid.cpp#L531

**Comment by adsprosto** [comment]
if code of ter server npc not summoning

**Comment by adsprosto** [comment]
import of ter druid's spells to arkcore

**Comment by gpn39f** [comment]
done..
