### ISSUE TITLE
Jan Database ZIP Title

### ISSUE THREAD

**Issue by Talmeron** [Arkania/ArkCORE-NG#53]
In Honor of Murdock who died today and created Debian.....and of course Ubuntu....and any update to linux software ever. I Suggest the Jan zip be titled appropriately.

**Comment by gpn39f** [comment]
you are welcome to help tune our Arkania NG core to compile errorfree on debiam and/or ubuntu.
some member has reported failure in GNU Compiler Settings and cmake commands..
this could be a good memento to Murdock..

**Comment by Talmeron** [comment]
Compiles fine. Has done.

**Comment by gpn39f** [comment]
thanks..
