### ISSUE TITLE
Guild crash

### ISSUE THREAD

**Issue by cooler-SAI** [Arkania/ArkCORE-NG#57]
Last core build crash https://github.com/Arkania/ArkCORE-NG/commit/59310bfad64ef78ffe0d4881b0691bb818eaf13e
when I create Guild I have Client crash

**Comment by gpn39f** [comment]
i have started with received a guild note..
have signed it, by 4 members
have registered the guild
now i'm guild master with all new guild Windows

no Crash.. 
can we receive a crash dump??
and what you have done??

**Comment by gpn39f** [comment]
yes, on next server loading the Startup Crash.. missing defintion in tabel character->characters->achievementpoint
first search on Google is without target..
