### ISSUE TITLE
Goblin Starting Zone

### ISSUE THREAD

**Issue by cooler-SAI** [Arkania/ArkCORE-NG#59]
This area really need fix, special for Phases, is it real to fix this zone? Thanks anyway

**Comment by gpn39f** [comment]
you can see on worgen Zone, that we are finish many problems regarding worldswapmap and areaswapmap.
but i see on hyjal - hatchery, that not allways the correct swap map is enabled by core.
roger has found a possible correlation: our Tools extract not all data correct. 
i have tryed to find tools that works on other emulators...(to find failure) without luck..
Problem is: swapmap switch not to correct map/zone/area so areatrigger and teleporter are not fire Events!!!

to answer you're question:
1.)  if you only mean phases.. yes we can do all, what we Need..  
2.)  if you mean swap map: no, noll all:  some things works correct, some works not..

**Comment by maxtros** [comment]
also gilneas, worgen's start zone it's broken again...wrong phases

**Comment by gpn39f** [comment]
look at Forum entrys.. only start up quest upto Phase 2 is made ready.. up to quest where you are bite first time..

**Comment by gpn39f** [comment]
Crash on goblin Zone: wrong npc_spellclick..
fixed
