### ISSUE TITLE
Druid

### ISSUE THREAD

**Issue by adsprosto** [Arkania/ArkCORE-NG#61]
Not Correct work spell's: mushroom and energy in moon spec

**Comment by gpn39f** [comment]
there are 40 different spells with mushroom inside..
so please give a link to the spell you mean..
and say different what is wrong..
and insert only 1 error in each issue you start..

**Comment by adsprosto** [comment]
cata.openwow.com/spell=88747 this spell a mushroom

**Comment by gpn39f** [comment]
there was several failure in scripts.
so now are wild mushroom spell working in principe..
please check..
