### ISSUE TITLE
Death Knight

### ISSUE THREAD

**Issue by adsprosto** [Arkania/ArkCORE-NG#62]
Not work bonus in blood Presence and frost Presence and unholy Presence

**Comment by gpn39f** [comment]
there are 9 different blood Presence..
please help me to find easely the spell you mean.. give me an link..
and what Bonus.. some blood Presence starts other spell, some has less cost and some have more damage..
tell me what you miss..

**Comment by adsprosto** [comment]
http://cata.openwow.com/spell=63611 blood Presence
http://cata.openwow.com/spell=50365 rank 1
http://cata.openwow.com/spell=50371 rank 2
http://cata.openwow.com/spell=63621 frost Presence
http://cata.openwow.com/spell=50384 rank 1
http://cata.openwow.com/spell=50385 rank 2
http://cata.openwow.com/spell=63622 unholy Presence
http://cata.openwow.com/spell=50391 rank 1
http://cata.openwow.com/spell=50392 rank 2

**Comment by gpn39f** [comment]
on game i see: all 3 Bonus i can select..
on the script i see, the spells 63611, 63621, 63622 are triggered later as improved spell..
if i look in our db, the spell you learn is 48263, 48265, 48266 
and this spell are castet on select.. and work internally as the should..
after this there are 1000 different Bonus, glyphs, auras that can have additional effect.. 
None other core like trinity, Mangos, ter884, has other values, as our core has..
so please.. say precise:  what there are wrong..
