### ISSUE TITLE
guild and gold can be retrieve by fellows in the guild

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#69]
When you belong to a guild a grant some gold to be retrieve by the member, the gold you give is written to be gold
but it is a copper multipluyer
to sumarise when on the guild you say you can retrieve 100 gold, you take 100 copper ...

**Comment by gpn39f** [comment]
i have started a guild with 3 member..
as Chef i go into bank and buy 2 guild Slots.. first 100 Gold next 250 Gold..
i buy into guild 30 Gold
i take 10 Gold... 
buy and take different amount...
but the amount of Money in my pocket and in bank are allways correct..
no places he take Gold as copper..

pls describe what you doing somewhat else as i doing..

**Comment by firelook** [comment]
I allow as leader to my fellow to redraw 1000 gold per day
=> this is not at all what they can take nearly 30 gold per day

P.S.
as an example if you have my dump
as a leader I have allowed 1000 Gold
=> chamani / calyssi can redraw max 30 (not exactly this amount, but can not go at all to 1000)

**Comment by gpn39f** [comment]
now i'm confused.. is the Problem the max Gold???
i understand until now:  that if you take 30 Gold from guild,  that the guild go correct down from 1000 Gold to 970 Gold, but in you're moneybag are only 30 copper added..

**Comment by firelook** [comment]
no, as a guild master you allow your guild member to redraw gold from the bank
in my example I allow 1000 gold per day
and they can not redraw this amount from the bank ( or repair for this amount)

**Comment by gpn39f** [comment]
but youself can do it?? it's also only member that see this failure

**Comment by firelook** [comment]
every people / level in the guild are stuck with a limitation which is different from the limitation you put in the guild tab ( P.S. try my dump ;) => do you need a more recent ? )

**Comment by gpn39f** [comment]
ok.. i tryed as member.. i can buy into guild, but if i take out, nothing happens.. 
the guild amount not dec and my amount not inc
internally does the dayly amount counter inc.. when the member have takeing all he may take out.. the take field is gray..

then: if i insert as Chef.. into properties... the dayly amount of Money, the value in field is allway set back to 0.. i can't see the actuell value.. it's allways 0.. 

i will try to take sniff to see what packets are send..

**Comment by firelook** [comment]
as a guild master you have to put an amount (in gold) in the special panel for your fellows, the amount you allow to be redraw let's say 100
then as a fellow of your guild try to go to the bank and redraw from your guildbank => you will seee that you can not redraw 100 gold daily

**Comment by gpn39f** [comment]
"as a guild master you have to put an amount (in gold) in the special panel for your fellows, the amount you allow to be redraw let's say 100"

the entry is not the member itself ??? (i will search again on member)
i found only fields for Status like:  beginners, member, master, admin...  
found on properties >> info >> Options

and there the value is not shown as is... it's going back to 0..

**Comment by firelook** [comment]
this was working before, I have just tested and it is stuck to 0 if you try to change
=> a regression ;)

**Comment by gpn39f** [comment]
has you the date from core/db where you test are ok??

**Comment by firelook** [comment]
unfortunately a long time ago, I have no clues (I do not rembember at all) (a year perhaps)

**Comment by firelook** [comment]
find the pb ?

**Comment by gpn39f** [comment]
no.. i really hope that someone read here our problem and has a solution..

**Comment by firelook** [comment]
hum, !!! christmas is not tomorrow ;)

P.S.
the fact to put a number was working "before"
but after  the redraw was another problem but at least is was working, now nothing so ...

**Comment by gpn39f** [comment]
found a part, where Gold amount is divide down to copper.. 
now the value is stored correct as Gold and viewed correct in member properties..
can you please check.. are all Errors gone??

**Comment by firelook** [comment]
good news, I will checked.

**Comment by firelook** [comment]
1/ ok first problem is solved regarding the fact that now we redraw the money ingold
2/ now we need to resolve the new problem regarding the fact we have a regression and we can not put the number of gold graphically for the guild (by the way which table is loacted this number)

**Comment by gpn39f** [comment]
??  graphically 
can u send a Picture via pm

**Comment by firelook** [comment]
using the client to enter the amount of gold the group of the guild can redraw
=> nowadays you can not enter any values it allways put 0

**Comment by gpn39f** [comment]
ok.. i see.. open guild bank window on Tresor in bank, i can pay Money into bank.. the field "redraw" from bank is allways gray..

**Comment by gpn39f** [comment]
thats make it more different..  let us see:
1.) the value stored in db are "max Gold pr day" and is a value in Gold. 
2.) the Gold value shown in window as "max Gold pr day" is a Gold value to, but some other window's give you as smallest value: copper
3.) so: all other work, (and all intern computing) with this money_max_value must be done in copper..

**Comment by gpn39f** [comment]
please check :-)

**Comment by firelook** [comment]
testing, seems good. I propose to close this as a general topic and come back with some specific problems if needed
