### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by Darkiu** [Arkania/ArkCORE-NG#7]
I found interesting this emulator and want to help in its development. I use linux to compile. Do I have to have some consideration when compiling? Do any requirement or something?

A greeting.

---

Me ha parecido interesante este emulador y quiero ayudar en su desarrollo. Utilizo linux para compilar. ¿Tengo que tener algo cuenta a la hora de compilar? ¿Algun requisito o algo?

Un saludo.

**Comment by gpn39f** [comment]
Hi Darkiu
you are welcome to our forum http://forums.arkania.net
in our wiki we have a section for Linux http://forums.arkania.net/wiki/index/
