### ISSUE TITLE
npc : Vlagga Freyfeather <Wind Rider Master>

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#71]
the npc
http://www.wowhead.com/npc=18930/vlagga-freyfeather#abilities
doesn't give you the flight to thrallmar

**Comment by gpn39f** [comment]
looking on the tables Shows a wrong entry in conditions..
please try to update

`
update conditions set ConditionsTypeOrReference=8 where sourceTypeOrReference=15 and SourceGroup=7938 and SourceEntry=0 and sourceId=0;
update conditions set ConditionsTypeOrReference=9 where sourceTypeOrReference=15 and SourceGroup=7938 and SourceEntry=1 and sourceId=0;

`

**Comment by gpn39f** [comment]
imported.. please check..

**Comment by firelook** [comment]
perfect
