### ISSUE TITLE
xp outlands

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#72]
if you are 59 and you kill a mob in outlands you received more than 2000 xp
if you are 60 the same kills give you less than 300
How the rule is working ?
http://wow.gamepedia.com/Mob_experience
http://wow.gamepedia.com/Experience_point
http://www.wowhead.com/zones=8

**Comment by gpn39f** [comment]
on Player.cpp there is the given xp computet..
on function _reward_xp you have compute step 4.2.3
calculate Expansion Penalty..
here is computet: (for my demo:  mob entry 18079)
Player Level 59 has lower *_Expansion *_as mob.. xp Points will stay as is
Player Level 60 has same *_Expansion *_as mob  xp Points / 10 <<<<< this happens to you

the *_Expansion *_is stored in creature_template exp
and our table has her 0: 
ytdb has 1
ter884 db has 0
cooler db has 0
trinity has 1

the error is in our db.. it seems that some Mobs in our db are stored in wrong exp.
i will try to filter this entry..

**Comment by gpn39f** [comment]
imported and uploaded.. pls check..

**Comment by firelook** [comment]
yes it is working for area 70, 
still investigating for level 80

**Comment by gpn39f** [comment]
same mob?? same Player Level 59/60??

**Comment by firelook** [comment]
still playing / testing => it is ok
