### ISSUE TITLE
db: Adarrah

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#73]
this pnj is missing
http://fr.wowhead.com/npc=44833/adarrah#objective-of

**Comment by gpn39f** [comment]
found here on Position

.go xyz -8920.7 -2261.42 8.96093

**Comment by firelook** [comment]
this seems not the right one if you look at wowhead ?

their is a "Budd" bu that's all

**Comment by gpn39f** [comment]
this is the entry in db:
105185  44833   22403   0   -8920,7 -2261,42    8,96093 5,84685 500
there i tok the Position..
and the guid is correct to the adarrah that standing there..
what are you missing???

**Comment by firelook** [comment]
unfortunately it doesn't work :
https://drive.google.com/open?id=0B95KCF0FxhCxNzR0dGVSS2E0RzA

**Comment by gpn39f** [comment]
yes ok.. she has Aura ID - 80797 Generic Quest Invisibility 5
updates spell_area for area 980..
now she is visible like the whole carawane..

**Comment by firelook** [comment]
perfect
