### ISSUE TITLE
log : trinity

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#75]
I have a strange thing in my logs:

`Player 28 discovered a new area: 3547
Player 28 discovered a new area: 3838
Player 28 discovered a new area: 3802
Player 28 discovered a new area: 3796
Player gain 2132 xp (+ 1066 Rested Bonus). Rested points=223874.000000
Player gain 2132 xp (+ 1066 Rested Bonus). Rested points=222808.000000
Player gain 2132 xp (+ 1066 Rested Bonus). Rested points=221742.000000
Entry 29245 not found in`trinity_string` table.
Prevented sending of UNKNOWN_OPCODE to [Player: Chamani (Guid: 28, Account: 19)]

Entry 29245 not found in `trinity_string` table.
Prevented sending of UNKNOWN_OPCODE to [Player: Chamani (Guid: 28, Account: 19)]

AchievementMgr::CompletedAchievement(862). Player: Chamani (28)
Player 28 discovered a new area: 3797
No defined handler for opcode [CMSG_MOVE_WATER_WALK_ACK 0x3B00 (15104)] sent by
[Player: Chamani (Guid: 28, Account: 19)]
No defined handler for opcode [CMSG_MOVE_WATER_WALK_ACK 0x3B00 (15104)] sent by
[Player: Chamani (Guid: 28, Account: 19)]
Player 28 discovered a new area: 3835`

I thought it as ark ;)

**Comment by gpn39f** [comment]
i tell you only what i read on core..:
it seems you have a big value from rested Points: 223874 Points..
i have no Idee what this is, how you have stored this value.. but you have!!!
if you receive xp, you can double it, if you have rested Points to do so.. and you have..
so you receive 1066 xp for discover a new area and you double it by youre rested points.. so you earn 2132 Points..
and you new rested Points are -1066 Points less...

the error trinity string entry 29245 is maybe a core failure..
it should shurly return a broadcast text string 29245 and this has text about achievement
and not a text from table arkcore_string
i will look at this later.

the opcode error  "No defined handler for opcode"
is a ack message from Client and dropped by our core..
so it's ok..

**Comment by firelook** [comment]
and also we use trinity names ;)

**Comment by firelook** [comment]
change trinity to ark
