### ISSUE TITLE
db : Silkwing Cocoons

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#76]
you can not give it back when you have finish the quest : 
http://www.wowhead.com/quest=10617/silkwing-cocoons

something is strange in this area some monsters with same name are friends, other are ennemies
perhaps a horde / alliance problem ?

**Comment by graham79** [comment]
update quest_template set SpecialFlags=0 where id=10617;

**Comment by gpn39f** [comment]
we have updated this as @graham79 say.. it's some day ago.. is it ok???

**Comment by firelook** [comment]
ok
