### ISSUE TITLE
DB/Bug Dungeon : blackrock-spire

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#77]
Due to the fact I put everything here I re test, I transfer this "challenge" from arkania
http://www.wowhead.com/zone=1583/blackrock-spire

=> dungeon under huge construction

**Comment by graham79** [comment]
My db and game has full blackrock spire, all mobs spawned, indeed. so is gpn39f's DB is full of mobs.

**Comment by gpn39f** [comment]
my english is really bad.. and Google translate help not..
what you mean with: "so is gpn39f's DB is full of Mobs"

**Comment by graham79** [comment]
I meant that your DB is the same as mine, and I thought you said you had been in blackrock and all the creatures are spawned?
This is Roger btw :)

**Comment by firelook** [comment]
Roger => use the db from gpn39f you will will a little difference with your db ;)

**Comment by gpn39f** [comment]
can we Close this ???

**Comment by firelook** [comment]
I will redo again but it is ok
