### ISSUE TITLE
Quest - The Last Wave of Survivors

### ISSUE THREAD

**Issue by cooler-SAI** [Arkania/ArkCORE-NG#79]
This Quest Doesn't work

http://www.wowhead.com/quest=13518/the-last-wave-of-survivors

**Comment by graham79** [comment]
hmm, I will give gpn39f the scripts.

**Comment by graham79** [comment]
what part of the quest doesnt work cooler?
do the npc's give credit to quest when right clicked?
do you get credit for all npc's but still can't hand it in?

**Comment by cooler-SAI** [comment]
I can talk with NPC's and nothing Happened - need ossip Menu and cosmetic Rescue Complete
