### ISSUE TITLE
db : A Furious Catch

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#80]
you can take the quest : 
http://fr.wowhead.com/quest=26565/une-prise-furieuse-retiree
but noway to catch it

**Comment by graham79** [comment]
I look in fishing loot for item needed and it appears there is no fishing loot with item. So impossible to catch that fish`
This quest was removed in 4.0.3 so it's up to @gpn39f to either add the loot or disable the quest.

**Comment by firelook** [comment]
commited
