### ISSUE TITLE
db : looks-like-a-tauren-pirate-to-me

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#81]
These objects are not sold
http://www.wowhead.com/quest=26630/looks-like-a-tauren-pirate-to-me

**Comment by graham79** [comment]
The cow head is not supposed to be sold, it is obtained from a cow in BootyBay.
I need to give gpn the script for the cow...sigh!.

**Comment by gpn39f** [comment]
it's  a gossip menu.. 11741 and 11742..
i'm trying how to configure with the spell 81311

**Comment by firelook** [comment]
ok

**Comment by firelook** [comment]
in sql
