### ISSUE TITLE
db : daily quest cooking / fishing

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#83]
it seems their is few daily quest in these categories.

example : 
Awilo Lon'gomba
http://www.wowhead.com/npc=29631/awilo-longomba#starts
nearly none

for the others (nearly ok but you do not have all often, allways the same and 1 or 2)
http://wowwiki.wikia.com/wiki/Daily_cooking_quests
http://wow.gamepedia.com/Daily_cooking_quests

no fishing daily quest
example
http://fr.wowhead.com/npc=43239/razgar

**Comment by gpn39f** [comment]
1) Awilo Lon'gomba
failure: the items are not marked as questitems.. (and have 100% chance) so you can obtain the object w/o quest.. 
but some glasses Standing around are our halv full glasses.. them i can obtain.. i Need 6 glasses..
the cheese i found by traider..
using the provided tablet.... and servere on questtaker.. all ok..

**Comment by firelook** [comment]
quite strange, I never manage to have these quests from Awilo Lon'gomba
- Cheese for Glowergold
- Convention at the Legerdemain
- Infused Mushroom Meatloaf
- Mustard Dogs!
- Sewer Stew
  I have none

**Comment by gpn39f** [comment]
mmhhh... i made no Change in worldserver.conf, and have not changed raid or Group quest behavior

**Comment by graham79** [comment]
are those quests pooled?

**Comment by firelook** [comment]
"mmhhh... i made no Change in worldserver.conf, and have not changed raid or Group quest behavior"
=> you can see these 5 quests ?

**Comment by graham79** [comment]
I can see those quests just fine, you do need a certain level of cooking to see them tho.

**Comment by gpn39f** [comment]
@graham79 if you mean that you found a error, pls give us the quest id.. we will check it..
@firelook have you more quest in this issue??

**Comment by firelook** [comment]
I need to find more information for fishing quest.
Regarding cooking I need to investigate more
I will re open when I have more concrete
