### ISSUE TITLE
db : ragveil

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#84]
ragveil in zangar can not be taken
http://www.wowhead.com/item=22787/ragveil
and you nearly have nothing (should be a lot)

**Comment by graham79** [comment]
you say "and you nearly have nothing (should be a lot)"
That implies that ragveil can be taken. so please explain more.
thankyou :)

**Comment by firelook** [comment]
1/ their is a bug, you can not take zangar (of course you have herbalism)
2/ you should have a "lot" to be taken and you have nearly nothing (I suspect some are missing on the ground)

**Comment by graham79** [comment]
I think I found the problem, In our DB we have 2x gameobjects named ragveil, this one http://www.wowhead.com/object=181275/ragveil  has only 4 spawns. 
This one, object=183043 has 163 spawns BUT no loot.
data1 needs to be set to 18043 where entry is 18043 then loot added from loot_template of object =181275

**Comment by firelook** [comment]
thanks, gpn39f your turn ? ;)

**Comment by firelook** [comment]
commited
