### ISSUE TITLE
db : character table in character database

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#86]
it is not a big issue, but a remark
when you are online, you have no longer a 1 but a number (30 ,45, ...) in the table character
is it normal ?

**Comment by gpn39f** [comment]
you are great...
on first look all is ok here.. 0=offline, 1=online..
same for single or with bot..
but looking in core, i see that the last value he write is a 32 bit value.. and should be a 8 bit value..
so i compare the tables with our core value's and:
yes.. on Import from trinity there is being corupted the order of the last 5 Elements..
one part is the achievement Points..
maybe we have found 2 failure that has disturbed us.. :-)

**Comment by graham79** [comment]
That sounds like the problem with my rogue that has consol error "out of range value in "online" column, then doesnt save any character progress.

**Comment by gpn39f** [comment]
roger. can you check it???

**Comment by graham79** [comment]
If I select my rogue character when she is online from `characters` it shows `online`=0. so core is not even seeing character as being online. 
For some reason the core has started saving characters progress now, may because I had deleted the toon and to test it I had to run insert sql in characters with diff guid and slightly diff name.

This was tested before I updated source code so your recent fix is not in core.

**Comment by graham79** [comment]
OK, I attempted to relearn talents and add some items that the character used to have. ported to orgrim and right away got the error in consol log, I logged out and everything I had done after teleporting was not saved to characters.

**Comment by gpn39f** [comment]
you say   "got the error in consol log,"
pls rewrite the error.. so i have the correct one.. :-)

**Comment by graham79** [comment]
are you kidding? the error is loooong..lol ok consol error.
SQL(p): UPDATE characters SET name='Roquer',race=2,class=4,gender=1,level=65,xp=201106,money=2725729,playerBytes=50594816,playerBytes2=16777217,playerFlags=8,map=1,instance_id=0,instance_mode_mask=0,position_x=6779.1,position_y=-4667.58,position_z=723.863,orientation=3.70575,trans_x=0,trans_y=0,trans_z=0,trans_o=0,transguid=0,taximask='0 16 81 1 0 0 16 0 16 128 112 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 32 0 0 0 0 0 0 0 0 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 128 1 0 0 0 0 0 0 0 1 0 0 0 0 0 32 0 24 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ',cinematic=1,totaltime=236869,leveltime=151639,rest_bonus=356250,logout_time=1456519086,is_logout_resting=0,resettalents_cost=0,resettalents_time=0,talentTree='183 0 ',extra_flags=1,stable_slots=0,at_login=0,zone=618,death_expire_time=1453897568,taxi_path='',totalKills=0,todayKills=0,yesterdayKills=0,chosenTitle=0,watchedFaction=4294967295,drunk=0,health=3139,power1=100,power2=0,power3=0,power4=0,power5=0,latency=0,speccount=1,activespec=0,exploredZones='1611268097 22097920 2936012804 2147680646 4215556 0 134479872 0 1107297316 536871040 536870912 65536 0 8192 0 4227072 32 8388608 64 8192 117440514 1572960 8 537133073 536870912 0 570835553 134217752 0 1610711040 8 1024 0 0 0 0 0 0 0 0 0 0 0 131072 0 0 0 0 0 0 0 0 0 0 134217728 0 0 0 0 0 0 0 0 0 0 0 0 512 0 0 0 0 0 0 0 0 0 269484032 8388608 2129928 0 0 262656 2151677952 2080 0 0 0 0 0 0 0 0 67108864 65536 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 10485760 0 0 0 0 0 0 0 0 1024 0 0 74898 0 8194 0 16 2147483648 0 0 0 4194304 268435456 0 0 0 0 0 0 0 0 0 201326592 0 0 0 0 0 0 0 0 0 0 0 ',equipmentCache='0 0 0 0 0 0 0 0 13897 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ',knownTitles='0 0 0 0 0 0 0 0 ',actionBars=14,grantableLevels=0,achievementPoint=0,ratedBGWins=60,ratedBGLoose=60,ratedBGRating=790,online=790 WHERE guid=9
 [ERROR]: [1264] Out of range value for column 'online' at row 1
Unhandled MySQL errno 1264. Unexpected behaviour possible.

**Comment by graham79** [comment]
I've noticed a mistake in the sql.
Theres no column "online" in the update sql.

**Comment by gpn39f** [comment]
is the last value: online=790 WHERE guid=9

**Comment by gpn39f** [comment]
this is the player.cpp from line 21062.. pls check youre core..
and the online value in table has to be 0 or 1.. so if you start the core, no old high value is loadet into store..  

`
  stmt->setUInt8(index++, GetByteValue(PLAYER_FIELD_BYTES, 2));
        stmt->setUInt32(index++, m_grantableLevels);
        stmt->setUInt32(index++, GetAchievementPoints());

```
    stmt->setUInt32(index++, GetRatedBGWins());
    stmt->setUInt32(index++, GetRatedBGLoose());
    stmt->setUInt32(index++, GetRatedBGRating());

    stmt->setUInt8(index++, IsInWorld() && !GetSession()->PlayerLogout() ? 1 : 0);

    // Index
    stmt->setUInt32(index++, GetGUIDLow());
```

`

**Comment by graham79** [comment]
Is that the player.cpp AFTER your fix or before it.
my lines are slightly diff.

**Comment by graham79** [comment]
![notepad](https://cloud.githubusercontent.com/assets/2817044/13366498/79458bf0-dcd3-11e5-9cf0-6c1e3c956650.jpg)

**Comment by gpn39f** [comment]
you have the old one.. 
are the changes not applyed in github???? i will check it..

**Comment by firelook** [comment]
in waiting you can change the structure of the table, and changing online to a long

**Comment by gpn39f** [comment]
this not good.. online is a boolean value.. so you have only 0 and 1.. it's good we receive failure.. then we can correct the error..

on github the patch is applyed correct..  if roger apply it manuelly.. then the order is correct and the crash is gone..

**Comment by firelook** [comment]
it is a temporary measure ;)

**Comment by graham79** [comment]
good morning.
I will update my source code and recompile and come back with the results :+1:

**Comment by graham79** [comment]
After recompile and update DB my rogue character is now being saved to DB. So I would say fix is good :+1:

**Comment by firelook** [comment]
ok
