### ISSUE TITLE
core : guild issue regarding it's progress

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#89]
the guild seems stuck regarding it's progress
https://dl.dropboxusercontent.com/u/82706346/giuild1.jpg
you can see daily is 7807 k / 7807 (100%) => never reset
in progress 2852 k => never clim any more

this was working because our guild is level 4

I thought it was linked to GuildAdvancement.ResetHour, but we have that since few days so ....

**Comment by gpn39f** [comment]
can you look at youre values in characters.characters database? what values you see for the last 4 values.. this values are not in trinity wiki.. so what are this values for.. Special value AchievementPoint

**Comment by firelook** [comment]
which table / column please ?

the dump of my database
https://drive.google.com/file/d/0BwdnAQ0FVZnaR0dhRGxvaDhnQWs/view?usp=sharing

**Comment by gpn39f** [comment]
characters.characters.AchievementPoint

**Comment by firelook** [comment]
750 for one characters,395,70 for others

**Comment by graham79** [comment]
hmm, interesting, only one of my characters has points in that column, and none of my characters belong to a guild. also none of my characters have ever been in a battleground but some of them have points in ratedbgwins, ratedbgloose and ratedbgrating column's.

**Comment by gpn39f** [comment]
can you see a correlation between this value and you achievement??
in core it's loaded together with guild member data..

**Comment by gpn39f** [comment]
@graham79 : starting from last update, there are valid data stored here.. before: here was stored 0/1 for online..
1.) so we have to prevent wrong old data.. 
2.) see what kind of value here should be stored

**Comment by firelook** [comment]
I have given the value that I have and others from the same guild have
=> I do not think this is the right column you are looking for
=> it seems the guild doesn't convert daily / hourly (a parameter in world.conf ?) into a normal ladder

again this was working before 
=> we manage to climb up to level 4 ;)

**Comment by firelook** [comment]
any ideas ?
guild is important for some people ;)
;)

**Comment by graham79** [comment]
please post a link to pastebin showing the guild settings in your world conf. :)

**Comment by firelook** [comment]
it seems the code correction is working, we are testing
should close it soon !!!!

**Comment by firelook** [comment]
no it doesn't work
we go back to 0 => reset is working
but we can not get any xp anymore

**Comment by graham79** [comment]
when you complete a quest do you see your character get guild rep and does the characters guild rep scale up after quest complete?

**Comment by gpn39f** [comment]
i have not seen message.  should i see?? and what should i see????
i look at database and see that values are stored..
i set breakpoints in core (on function GiveXP) and see that *_quest with give xp *_ has part of 25% adding to guild (less value are 1 point)
and some quest  give questXp / 450 for guild
this is the way i have testet the guild xp.. but ofcores should it be visible in Status bar how many Points you have or you want for next Level.. but you have 2 Million Points, it Show a value like 2500K.. so you need 1000 Points bevor you see a new value..

**Comment by graham79** [comment]
I think it's my addon "Carbonite" reports any rep gains in the chat channel in blue text.
When you open your guild window, you should see bottom left your progress bar for reputation with your guild.. not sure if the bar has a tool tip showing points.

**Comment by firelook** [comment]
I close this issues: I continue to test this week end
