### ISSUE TITLE
db : Hanah Chantesud (flight master)

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#92]
http://fr.wowhead.com/npc=43073/hanah-chantesud
doesn't work as a flight master

**Comment by graham79** [comment]
same thing as other f/master.
update gossip_menu_option set option_id=4,npc_option_npcflag=8192 where id=0 and menu_id=12428;

**Comment by graham79** [comment]
update gossip_menu_option set option_id=1,npc_option_npcflag=1 where id=2 and menu_id=12428;

**Comment by firelook** [comment]
ok so I close it
