### ISSUE TITLE
db : Wetlands 4.x Bunny

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#93]
http://www.wowhead.com/npc=42100/wetlands-4-x-bunny
this rabbit is in the paluns, invisible, too high level and kill every body

**Comment by graham79** [comment]
which flag components does that contain gpn39f ?
unit_flags=33587968

**Comment by gpn39f** [comment]
Value taken from trinity and ytdb and enable:

256 Immune to pc 
512 Immune to npc
32768 unk15
33554432 not selectable

**Comment by firelook** [comment]
ok
