### ISSUE TITLE
Spell script not passing validation.

### ISSUE THREAD

**Issue by graham79** [Arkania/ArkCORE-NG#94]
https://cata-twinhead.twinstar.cz/?spell=46378
spell_windsoul_totem_aura,   did not match dbc effect data - handler bound to hook `OnEffectRemove` of aurascript won't be executed.

**Comment by gpn39f** [comment]
you have the wrong spell.. the script in core is 
https://cata-twinhead.twinstar.cz/?spell=46374
and here you generate a kill credit with spell 46378

**Comment by graham79** [comment]
thanks gpn39f
