### ISSUE TITLE
Currency for players. Core

### ISSUE THREAD

**Issue by graham79** [Arkania/ArkCORE-NG#97]
I have been testing this out. Now I find there is no way to add currencys to a character unless you use GM .mod currency command. The core treat Miscellaneous category currency different to dungeon/raid currency.  Currency such as "chefs award" =81 is category miscellaneous and can be added through quest currency reward.
Currency such as "justice points/Valor points" for some reason are handled differently by the core and cannot be added to player by any method at all, not quest reward, nor creature kill reward. 
In the Trinity 434 core and Arkcore2 406 plus Arkcore4 the Core read the creature_onkill_reward / creature_onkill_reputation table which have currencyId columns and delivered the ammount of currency set in the entry.
Our core ArkcoreNG ignores the currency columns for both the creature_onkill_reputation AND currency_loot table. The currency_loot table seems to be a table added by a developer in an attempt to allow currency to be passed to players on creature kill but seems to be totally ignored by the core.

ALSO. The core treat each category different. 
miscellaneous cat=1 can be rewarded on a 1 per 1 basis in a quest template. eg: CurrencyCount1=1.

dungeon/raid cat= 22  for some reason unknown is divided by the core. eg, if you use gm .mod currency 395 (justice points) x1 you get none. The min value that will give points is 100 which give 1 point.
add 100 gives 1point
add1000 gives 10 points
add 10000 gives 100 points.
These currencys are ignored by the core when added to quest rewards or creature on death rewards.

What part of core handles currencys?

**Comment by gpn39f** [comment]
i have no Idee.. never worked with currencys.. so i must reading me to the knowledge..

pls send me the places of difference between cores you found  and a little note what you think this part does..

**Comment by graham79** [comment]
I have given upload link in conversation to gpn39f in conversation on forums. first part of fix for dungeon and raid currency points.

**Comment by graham79** [comment]
Justice points are now dropping from creatures after we get the values set in creature_onkill_reputation.

**Comment by graham79** [comment]
Dungeon and raid points now are given by quest on a 1:! basis. 
Mission accomplished.
Issue now closed.
