### ISSUE TITLE
db : Alpine Hare

### ISSUE THREAD

**Issue by firelook** [Arkania/ArkCORE-NG#99]
I have these errors for this creature:
http://www.wowhead.com/npc=61690/alpine-hare

`CreatureTextMgr: Could not find Text for Creature Alpine Hare (Entry 48935, GUID 62534) in 'creature_text' table. Ignoring.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.
SmartScript::ProcessAction: Entry 14390 SourceType 0, Event 8, Link Event 9 not found or invalid, skipped.`

**Comment by graham79** [comment]
update smart_scripts set link=0 where id=8 and entryorguid=14390;
update smart_scripts set event_param2=5 where id in(8,9) and entryorguid=14390;
as for CreatureTextMgr: Could not find Text for Creature Alpine Hare (Entry 48935, GUID 62534) in 'creature_text' table. Ignoring. that creature has no smart_script. no clue

**Comment by firelook** [comment]
thanks

**Comment by firelook** [comment]
ok
